package {{packageName}}.config;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.aop.interceptor.AsyncUncaughtExceptionHandler;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.scheduling.annotation.AsyncConfigurer;
import org.springframework.scheduling.annotation.EnableAsync;
import org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor;

import java.util.concurrent.Executor;

/**
 * Asynchronous processing configuration for {{serviceNameTitleCase}}
 *
 * Configures thread pools for async event handling and background processing.
 * Generated by Enterprise CLI - customize thread pool settings as needed.
 */
@Configuration
@EnableAsync
public class AsyncConfig implements AsyncConfigurer {

    private static final Logger logger = LoggerFactory.getLogger(AsyncConfig.class);

    /**
     * Main async executor for domain event processing
     */
    @Override
    @Bean(name = "asyncTaskExecutor")
    public Executor getAsyncExecutor() {
        ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();

        // Core pool configuration
        executor.setCorePoolSize(5);
        executor.setMaxPoolSize(20);
        executor.setQueueCapacity(100);

        // Thread naming
        executor.setThreadNamePrefix("{{serviceName}}-async-");

        // Graceful shutdown
        executor.setWaitForTasksToCompleteOnShutdown(true);
        executor.setAwaitTerminationSeconds(30);

        // Rejection policy
        executor.setRejectedExecutionHandler(new java.util.concurrent.ThreadPoolExecutor.CallerRunsPolicy());

        executor.initialize();

        logger.info("Configured async task executor with core pool size: {}, max pool size: {}",
            executor.getCorePoolSize(), executor.getMaxPoolSize());

        return executor;
    }

    /**
     * Dedicated executor for event processing
     */
    @Bean(name = "eventExecutor")
    public Executor eventExecutor() {
        ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();

        // Event processing specific configuration
        executor.setCorePoolSize(3);
        executor.setMaxPoolSize(10);
        executor.setQueueCapacity(50);

        // Thread naming
        executor.setThreadNamePrefix("{{serviceName}}-event-");

        // Graceful shutdown
        executor.setWaitForTasksToCompleteOnShutdown(true);
        executor.setAwaitTerminationSeconds(20);

        // Keep alive time for idle threads
        executor.setKeepAliveSeconds(60);
        executor.setAllowCoreThreadTimeOut(true);

        executor.initialize();

        logger.info("Configured event executor with core pool size: {}, max pool size: {}",
            executor.getCorePoolSize(), executor.getMaxPoolSize());

        return executor;
    }

    /**
     * Dedicated executor for audit operations
     */
    @Bean(name = "auditExecutor")
    public Executor auditExecutor() {
        ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();

        // Audit operations configuration
        executor.setCorePoolSize(2);
        executor.setMaxPoolSize(5);
        executor.setQueueCapacity(200);

        // Thread naming
        executor.setThreadNamePrefix("{{serviceName}}-audit-");

        // Graceful shutdown
        executor.setWaitForTasksToCompleteOnShutdown(true);
        executor.setAwaitTerminationSeconds(45);

        executor.initialize();

        logger.info("Configured audit executor with core pool size: {}, max pool size: {}",
            executor.getCorePoolSize(), executor.getMaxPoolSize());

        return executor;
    }

    /**
     * Global exception handler for async operations
     */
    @Override
    public AsyncUncaughtExceptionHandler getAsyncUncaughtExceptionHandler() {
        return new CustomAsyncExceptionHandler();
    }

    /**
     * Custom exception handler for async operations
     */
    private static class CustomAsyncExceptionHandler implements AsyncUncaughtExceptionHandler {

        private final Logger logger = LoggerFactory.getLogger(CustomAsyncExceptionHandler.class);

        @Override
        public void handleUncaughtException(Throwable throwable, java.lang.reflect.Method method, Object... objects) {
            logger.error("Async method execution failed. Method: {}.{}, Parameters: {}",
                method.getDeclaringClass().getSimpleName(),
                method.getName(),
                java.util.Arrays.toString(objects),
                throwable);

            // Add custom exception handling logic here
            // Examples:
            // - Send alerts for critical failures
            // - Implement retry mechanisms
            // - Store failed operations for manual review
            // - Update monitoring metrics
        }
    }

    /**
     * Configuration for scheduled tasks
     */
    @Bean(name = "scheduledExecutor")
    public Executor scheduledExecutor() {
        ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();

        // Scheduled tasks configuration
        executor.setCorePoolSize(2);
        executor.setMaxPoolSize(4);
        executor.setQueueCapacity(10);

        // Thread naming
        executor.setThreadNamePrefix("{{serviceName}}-scheduled-");

        // Graceful shutdown
        executor.setWaitForTasksToCompleteOnShutdown(false);
        executor.setAwaitTerminationSeconds(10);

        executor.initialize();

        logger.info("Configured scheduled executor with core pool size: {}, max pool size: {}",
            executor.getCorePoolSize(), executor.getMaxPoolSize());

        return executor;
    }
}