package {{packageName}}.config;

import com.github.benmanes.caffeine.cache.Caffeine;
import org.springframework.cache.CacheManager;
import org.springframework.cache.annotation.EnableCaching;
import org.springframework.cache.caffeine.CaffeineCacheManager;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Primary;

import java.time.Duration;

/**
 * Cache Configuration for {{serviceNameTitleCase}}
 *
 * Configures local caching with Caffeine for improved performance.
 * Provides different cache configurations for various data types.
 * Generated by Enterprise CLI - customize according to your caching requirements.
 */
@Configuration
@EnableCaching
public class CacheConfig {

    /**
     * Primary Cache Manager using Caffeine
     */
    @Bean
    @Primary
    public CacheManager cacheManager() {
        CaffeineCacheManager cacheManager = new CaffeineCacheManager();

        // Configure default cache settings
        cacheManager.setCaffeine(defaultCacheBuilder());

        // Register cache names
        cacheManager.setCacheNames(
                "{{domain}}s",           // {{domainTitleCase}} entities
                "{{domain}}sSearch",     // Search results
                "{{domain}}sCount",      // Count queries
                "metadata",              // Application metadata
                "userSessions",          // User session data
                "configurations"         // Configuration data
        );

        return cacheManager;
    }

    /**
     * Default cache configuration
     */
    private Caffeine<Object, Object> defaultCacheBuilder() {
        return Caffeine.newBuilder()
                .maximumSize(1000)                    // Maximum 1000 entries
                .expireAfterWrite(Duration.ofMinutes(30))   // Expire after 30 minutes
                .expireAfterAccess(Duration.ofMinutes(10))  // Expire after 10 minutes of no access
                .recordStats();                       // Enable statistics
    }

    /**
     * Cache for {{domainTitleCase}} entities
     * Optimized for frequent reads with medium TTL
     */
    @Bean
    public CacheManager {{domain}}CacheManager() {
        CaffeineCacheManager cacheManager = new CaffeineCacheManager("{{domain}}s");

        cacheManager.setCaffeine(Caffeine.newBuilder()
                .maximumSize(500)                     // Up to 500 {{domain}}s
                .expireAfterWrite(Duration.ofMinutes(15))   // Refresh every 15 minutes
                .expireAfterAccess(Duration.ofMinutes(5))   // Remove unused after 5 minutes
                .recordStats());

        return cacheManager;
    }

    /**
     * Cache for search results
     * Short TTL for dynamic data
     */
    @Bean
    public CacheManager searchCacheManager() {
        CaffeineCacheManager cacheManager = new CaffeineCacheManager("{{domain}}sSearch");

        cacheManager.setCaffeine(Caffeine.newBuilder()
                .maximumSize(200)                     // Limit search result cache
                .expireAfterWrite(Duration.ofMinutes(5))    // Short TTL for search results
                .expireAfterAccess(Duration.ofMinutes(2))   // Quick cleanup
                .recordStats());

        return cacheManager;
    }

    /**
     * Cache for count and aggregation queries
     * Medium TTL for statistical data
     */
    @Bean
    public CacheManager countCacheManager() {
        CaffeineCacheManager cacheManager = new CaffeineCacheManager("{{domain}}sCount");

        cacheManager.setCaffeine(Caffeine.newBuilder()
                .maximumSize(100)                     // Limited count cache
                .expireAfterWrite(Duration.ofMinutes(10))   // Moderate TTL
                .recordStats());

        return cacheManager;
    }

    /**
     * Cache for application metadata and configuration
     * Long TTL for rarely changing data
     */
    @Bean
    public CacheManager metadataCacheManager() {
        CaffeineCacheManager cacheManager = new CaffeineCacheManager("metadata", "configurations");

        cacheManager.setCaffeine(Caffeine.newBuilder()
                .maximumSize(50)                      // Small cache for metadata
                .expireAfterWrite(Duration.ofHours(1))      // Long TTL for static data
                .recordStats());

        return cacheManager;
    }

    /**
     * Cache for user sessions
     * Balanced settings for user data
     */
    @Bean
    public CacheManager userSessionCacheManager() {
        CaffeineCacheManager cacheManager = new CaffeineCacheManager("userSessions");

        cacheManager.setCaffeine(Caffeine.newBuilder()
                .maximumSize(1000)                    // Support many concurrent users
                .expireAfterWrite(Duration.ofMinutes(30))   // Session timeout
                .expireAfterAccess(Duration.ofMinutes(15))  // Activity-based expiry
                .recordStats());

        return cacheManager;
    }

    /**
     * Cache statistics and monitoring bean
     */
    @Bean
    public CacheStatsService cacheStatsService() {
        return new CacheStatsService();
    }

    /**
     * Service for cache statistics and monitoring
     */
    public static class CacheStatsService {

        /**
         * Get cache statistics for monitoring
         */
        public String getCacheStats(CacheManager cacheManager) {
            if (cacheManager instanceof CaffeineCacheManager) {
                CaffeineCacheManager caffeineCacheManager = (CaffeineCacheManager) cacheManager;
                StringBuilder stats = new StringBuilder();

                caffeineCacheManager.getCacheNames().forEach(cacheName -> {
                    var cache = caffeineCacheManager.getCache(cacheName);
                    if (cache != null && cache.getNativeCache() instanceof com.github.benmanes.caffeine.cache.Cache) {
                        var caffeineCache = (com.github.benmanes.caffeine.cache.Cache<?, ?>) cache.getNativeCache();
                        var cacheStats = caffeineCache.stats();

                        stats.append(String.format(
                                "Cache: %s - Size: %d, Hits: %d, Misses: %d, Hit Rate: %.2f%%\n",
                                cacheName,
                                caffeineCache.estimatedSize(),
                                cacheStats.hitCount(),
                                cacheStats.missCount(),
                                cacheStats.hitRate() * 100
                        ));
                    }
                });

                return stats.toString();
            }
            return "Cache statistics not available";
        }

        /**
         * Clear all caches
         */
        public void clearAllCaches(CacheManager cacheManager) {
            cacheManager.getCacheNames().forEach(cacheName -> {
                var cache = cacheManager.getCache(cacheName);
                if (cache != null) {
                    cache.clear();
                }
            });
        }

        /**
         * Clear specific cache
         */
        public void clearCache(CacheManager cacheManager, String cacheName) {
            var cache = cacheManager.getCache(cacheName);
            if (cache != null) {
                cache.clear();
            }
        }
    }
}