package {{packageName}}.config;

import {{packageName}}.enterprise.patterns.EnterpriseMetricsCollector;
import {{packageName}}.enterprise.patterns.MetricsCollector;
import io.micrometer.core.instrument.MeterRegistry;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * 🤖 ENTERPRISE INFRASTRUCTURE - DO NOT MODIFY
 *
 * Configuration for Enterprise Infrastructure components
 * Provides Spring beans for enterprise patterns
 *
 * Generated by Enterprise CLI - Infrastructure layer
 */
@Configuration
public class EnterpriseInfrastructureConfig {

    /**
     * 🤖 Metrics Collector bean
     */
    @Bean
    public MetricsCollector metricsCollector(MeterRegistry meterRegistry) {
        return new EnterpriseMetricsCollector(meterRegistry);
    }
}