package {{packageName}}.config;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.web.client.RestTemplateBuilder;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.client.ClientHttpRequestInterceptor;
import org.springframework.web.client.RestTemplate;
import org.springframework.web.reactive.function.client.ExchangeFilterFunction;
import org.springframework.web.reactive.function.client.WebClient;
import reactor.core.publisher.Mono;

import java.time.Duration;
import java.util.List;

/**
 * External Service Integration Configuration for {{serviceNameTitleCase}}
 *
 * Configures RestTemplate and WebClient for external service calls.
 * Includes timeout, retry, and logging configurations.
 * Generated by Enterprise CLI - customize endpoints and settings as needed.
 */
@Configuration
public class ExternalServiceConfig {

    private static final Logger logger = LoggerFactory.getLogger(ExternalServiceConfig.class);

    @Value("${app.external.timeout:30000}")
    private int timeoutMs;

    @Value("${app.external.retry-attempts:3}")
    private int retryAttempts;

    /**
     * RestTemplate configuration for synchronous HTTP calls
     */
    @Bean
    public RestTemplate restTemplate(RestTemplateBuilder builder) {
        return builder
                .setConnectTimeout(Duration.ofMillis(timeoutMs))
                .setReadTimeout(Duration.ofMillis(timeoutMs))
                .interceptors(restTemplateLoggingInterceptor())
                .build();
    }

    /**
     * WebClient configuration for reactive HTTP calls
     */
    @Bean
    public WebClient webClient() {
        return WebClient.builder()
                .defaultHeader(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON_VALUE)
                .defaultHeader(HttpHeaders.USER_AGENT, "{{serviceNameTitleCase}}/1.0")
                .filter(webClientLoggingFilter())
                .filter(webClientErrorFilter())
                .build();
    }

    /**
     * WebClient for a specific external service
     * Example: User service integration
     */
    @Bean
    public WebClient userServiceWebClient(@Value("${app.external.user-service.base-url:http://localhost:8081}") String baseUrl) {
        return WebClient.builder()
                .baseUrl(baseUrl)
                .defaultHeader(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON_VALUE)
                .defaultHeader(HttpHeaders.USER_AGENT, "{{serviceNameTitleCase}}/1.0")
                .filter(webClientLoggingFilter())
                .filter(webClientErrorFilter())
                .build();
    }

    /**
     * WebClient for another external service
     * Example: Notification service integration
     */
    @Bean
    public WebClient notificationServiceWebClient(@Value("${app.external.notification-service.base-url:http://localhost:8082}") String baseUrl) {
        return WebClient.builder()
                .baseUrl(baseUrl)
                .defaultHeader(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON_VALUE)
                .defaultHeader(HttpHeaders.USER_AGENT, "{{serviceNameTitleCase}}/1.0")
                .filter(webClientLoggingFilter())
                .filter(webClientErrorFilter())
                .build();
    }

    /**
     * RestTemplate logging interceptor
     */
    private ClientHttpRequestInterceptor restTemplateLoggingInterceptor() {
        return (request, body, execution) -> {
            if (logger.isDebugEnabled()) {
                logger.debug("RestTemplate Request: {} {} - Body: {}",
                    request.getMethod(), request.getURI(), new String(body));
            }

            long startTime = System.currentTimeMillis();
            var response = execution.execute(request, body);
            long duration = System.currentTimeMillis() - startTime;

            if (logger.isDebugEnabled()) {
                logger.debug("RestTemplate Response: {} {} - Status: {} - Duration: {}ms",
                    request.getMethod(), request.getURI(), response.getStatusCode(), duration);
            }

            return response;
        };
    }

    /**
     * WebClient logging filter
     */
    private ExchangeFilterFunction webClientLoggingFilter() {
        return ExchangeFilterFunction.ofRequestProcessor(clientRequest -> {
            if (logger.isDebugEnabled()) {
                logger.debug("WebClient Request: {} {}", clientRequest.method(), clientRequest.url());
            }
            return Mono.just(clientRequest);
        });
    }

    /**
     * WebClient error handling filter
     */
    private ExchangeFilterFunction webClientErrorFilter() {
        return ExchangeFilterFunction.ofResponseProcessor(clientResponse -> {
            if (clientResponse.statusCode().isError()) {
                logger.warn("WebClient Error Response: {} - Status: {}",
                    clientResponse.request().getURI(), clientResponse.statusCode());
            }
            return Mono.just(clientResponse);
        });
    }

    /**
     * Configuration properties for external services
     */
    public static class ExternalServiceProperties {
        private String baseUrl;
        private int timeoutMs = 30000;
        private int retryAttempts = 3;
        private boolean circuitBreakerEnabled = true;

        // Getters and setters
        public String getBaseUrl() { return baseUrl; }
        public void setBaseUrl(String baseUrl) { this.baseUrl = baseUrl; }

        public int getTimeoutMs() { return timeoutMs; }
        public void setTimeoutMs(int timeoutMs) { this.timeoutMs = timeoutMs; }

        public int getRetryAttempts() { return retryAttempts; }
        public void setRetryAttempts(int retryAttempts) { this.retryAttempts = retryAttempts; }

        public boolean isCircuitBreakerEnabled() { return circuitBreakerEnabled; }
        public void setCircuitBreakerEnabled(boolean circuitBreakerEnabled) {
            this.circuitBreakerEnabled = circuitBreakerEnabled;
        }
    }
}