package {{packageName}}.config;

import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Configuration;

/**
 * Configuration class to enable type-safe configuration properties
 *
 * Enables all configuration properties classes for dependency injection.
 * Generated by Enterprise CLI - add new properties classes here as needed.
 */
@Configuration
@EnableConfigurationProperties({
    ApplicationProperties.class
})
public class PropertiesConfig {

    // This class serves as a central place to enable all configuration properties
    // No additional implementation needed - Spring Boot will handle the rest
}