package {{packageName}}.config;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.scheduling.annotation.EnableScheduling;
import org.springframework.scheduling.annotation.SchedulingConfigurer;
import org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler;
import org.springframework.scheduling.config.ScheduledTaskRegistrar;

import java.util.concurrent.Executor;

/**
 * Scheduling Configuration for {{serviceNameTitleCase}}
 *
 * Configures thread pool for scheduled tasks and enables scheduling.
 * Provides custom executor for background task execution.
 * Generated by Enterprise CLI - customize pool settings as needed.
 */
@Configuration
@EnableScheduling
public class SchedulingConfig implements SchedulingConfigurer {

    private static final Logger logger = LoggerFactory.getLogger(SchedulingConfig.class);

    @Override
    public void configureTasks(ScheduledTaskRegistrar taskRegistrar) {
        taskRegistrar.setScheduler(taskExecutor());
    }

    /**
     * Task scheduler configuration
     */
    @Bean
    public Executor taskExecutor() {
        ThreadPoolTaskScheduler scheduler = new ThreadPoolTaskScheduler();

        // Pool configuration
        scheduler.setPoolSize(5);
        scheduler.setThreadNamePrefix("{{serviceName}}-scheduler-");

        // Graceful shutdown
        scheduler.setWaitForTasksToCompleteOnShutdown(true);
        scheduler.setAwaitTerminationSeconds(30);

        // Rejection policy
        scheduler.setRejectedExecutionHandler(new java.util.concurrent.ThreadPoolExecutor.CallerRunsPolicy());

        scheduler.initialize();

        logger.info("Configured task scheduler with pool size: {}", scheduler.getPoolSize());

        return scheduler;
    }

    /**
     * Dedicated scheduler for long-running tasks
     */
    @Bean
    public ThreadPoolTaskScheduler longRunningTaskScheduler() {
        ThreadPoolTaskScheduler scheduler = new ThreadPoolTaskScheduler();

        // Configuration for long-running tasks
        scheduler.setPoolSize(3);
        scheduler.setThreadNamePrefix("{{serviceName}}-long-task-");
        scheduler.setWaitForTasksToCompleteOnShutdown(true);
        scheduler.setAwaitTerminationSeconds(60);

        scheduler.initialize();

        logger.info("Configured long-running task scheduler with pool size: {}", scheduler.getPoolSize());

        return scheduler;
    }
}