package {{packageName}}.repository;

import {{packageName}}.entity.{{domainTitleCase}};
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

/**
 * Spring Data JPA Repository for {{domainTitleCase}} entity
 *
 * Enhanced repository with JPA Specification support for complex queries.
 * Use {{domainTitleCase}}Specification for type-safe dynamic queries.
 * Generated by Enterprise CLI - add custom query methods as needed.
 */
@Repository
public interface {{domainTitleCase}}Repository extends JpaRepository<{{domainTitleCase}}, String>,
                                                     JpaSpecificationExecutor<{{domainTitleCase}}> {

    /**
     * Find {{domain}} by name (case-insensitive)
     */
    Optional<{{domainTitleCase}}> findByNameIgnoreCase(String name);

    /**
     * Find all {{domain}}s containing the given text in name or description
     */
    @Query("SELECT e FROM {{domainTitleCase}} e WHERE " +
           "LOWER(e.name) LIKE LOWER(CONCAT('%', :searchText, '%')) OR " +
           "LOWER(e.description) LIKE LOWER(CONCAT('%', :searchText, '%'))")
    List<{{domainTitleCase}}> findByNameOrDescriptionContaining(@Param("searchText") String searchText);

    /**
     * Find {{domain}}s created after the specified date
     */
    List<{{domainTitleCase}}> findByCreatedAtAfter(LocalDateTime date);

    /**
     * Find {{domain}}s by name pattern (case-insensitive)
     */
    List<{{domainTitleCase}}> findByNameContainingIgnoreCase(String namePattern);

    /**
     * Check if {{domain}} exists by name (case-insensitive)
     */
    boolean existsByNameIgnoreCase(String name);

    /**
     * Count {{domain}}s created after the specified date
     */
    long countByCreatedAtAfter(LocalDateTime date);

    /**
     * Find active {{domain}}s (custom business logic example)
     * This is a placeholder - customize based on your business rules
     */
    @Query("SELECT e FROM {{domainTitleCase}} e WHERE e.description IS NOT NULL AND e.description != ''")
    List<{{domainTitleCase}}> findActive{{domainTitleCase}}s();

    // ================================
    // Specification-based Query Examples
    // ================================
    // These methods demonstrate how to use Specification for complex queries
    // Use {{domainTitleCase}}Specification class for building dynamic queries

    /**
     * Advanced search using Specification
     * Example of how to use {{domainTitleCase}}Specification.search()
     */
    default Page<{{domainTitleCase}}> findWithAdvancedSearch(String name, String description,
                                                           LocalDateTime createdAfter,
                                                           LocalDateTime createdBefore,
                                                           Boolean hasDescription,
                                                           Pageable pageable) {
        {{packageName}}.specification.{{domainTitleCase}}Specification.Builder builder =
            {{packageName}}.specification.{{domainTitleCase}}Specification.builder();

        if (name != null && !name.trim().isEmpty()) {
            builder.withName(name);
        }
        if (description != null && !description.trim().isEmpty()) {
            builder.withDescription(description);
        }
        if (createdAfter != null) {
            builder.createdAfter(createdAfter);
        }
        if (createdBefore != null) {
            builder.createdBefore(createdBefore);
        }
        if (hasDescription != null) {
            builder.withDescription(hasDescription);
        }

        return findAll(builder.build(), pageable);
    }

    /**
     * Global text search using Specification
     * Searches across name and description fields
     */
    default List<{{domainTitleCase}}> findByGlobalSearch(String searchText) {
        if (searchText == null || searchText.trim().isEmpty()) {
            return findAll();
        }

        Specification<{{domainTitleCase}}> spec = {{packageName}}.specification.{{domainTitleCase}}Specification
            .globalSearch(searchText);

        return findAll(spec);
    }

    /**
     * Find {{domain}}s created in a specific time range using Specification
     */
    default List<{{domainTitleCase}}> findCreatedBetween(LocalDateTime startDate, LocalDateTime endDate) {
        Specification<{{domainTitleCase}}> spec = {{packageName}}.specification.{{domainTitleCase}}Specification
            .createdBetween(startDate, endDate);

        return findAll(spec);
    }

    /**
     * Complex business query example using Specification
     * Find active {{domain}}s created in the last week
     */
    default List<{{domainTitleCase}}> findActive{{domainTitleCase}}sLastWeek() {
        Specification<{{domainTitleCase}}> spec = {{packageName}}.specification.{{domainTitleCase}}Specification
            .active{{domainTitleCase}}sLastWeek();

        return findAll(spec);
    }
}