package {{packageName}}.repository;

import {{packageName}}.entity.{{domainTitleCase}};
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

/**
 * Spring Data JPA Repository for {{domainTitleCase}} entity
 *
 * This is a sample repository generated by Enterprise CLI.
 * Add custom query methods according to your business requirements.
 */
@Repository
public interface {{domainTitleCase}}Repository extends JpaRepository<{{domainTitleCase}}, String> {

    /**
     * Find {{domain}} by name (case-insensitive)
     */
    Optional<{{domainTitleCase}}> findByNameIgnoreCase(String name);

    /**
     * Find all {{domain}}s containing the given text in name or description
     */
    @Query("SELECT e FROM {{domainTitleCase}} e WHERE " +
           "LOWER(e.name) LIKE LOWER(CONCAT('%', :searchText, '%')) OR " +
           "LOWER(e.description) LIKE LOWER(CONCAT('%', :searchText, '%'))")
    List<{{domainTitleCase}}> findByNameOrDescriptionContaining(@Param("searchText") String searchText);

    /**
     * Find {{domain}}s created after the specified date
     */
    List<{{domainTitleCase}}> findByCreatedAtAfter(LocalDateTime date);

    /**
     * Find {{domain}}s by name pattern (case-insensitive)
     */
    List<{{domainTitleCase}}> findByNameContainingIgnoreCase(String namePattern);

    /**
     * Check if {{domain}} exists by name (case-insensitive)
     */
    boolean existsByNameIgnoreCase(String name);

    /**
     * Count {{domain}}s created after the specified date
     */
    long countByCreatedAtAfter(LocalDateTime date);

    /**
     * Find active {{domain}}s (custom business logic example)
     * This is a placeholder - customize based on your business rules
     */
    @Query("SELECT e FROM {{domainTitleCase}} e WHERE e.description IS NOT NULL AND e.description != ''")
    List<{{domainTitleCase}}> findActive{{domainTitleCase}}s();
}