package {{packageName}}.camel;

import {{packageName}}.dto.{{domainTitleCase}}Request;
import {{packageName}}.dto.{{domainTitleCase}}Response;
import {{packageName}}.service.{{domainTitleCase}}Service;
import org.apache.camel.builder.RouteBuilder;
import org.apache.camel.component.jackson.JacksonDataFormat;
import org.apache.camel.model.dataformat.JsonLibrary;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 * Apache Camel Routes for {{domainTitleCase}} integration
 *
 * This is a sample route configuration generated by Enterprise CLI.
 * Configure integration patterns according to your requirements.
 */
@Component
public class {{domainTitleCase}}Routes extends RouteBuilder {

    private static final Logger logger = LoggerFactory.getLogger({{domainTitleCase}}Routes.class);

    @Autowired
    private {{domainTitleCase}}Service {{domain}}Service;

    @Override
    public void configure() throws Exception {

        // Configure JSON data format
        JacksonDataFormat jsonFormat = new JacksonDataFormat();
        jsonFormat.setUnmarshalType({{domainTitleCase}}Request.class);

        // Exception handling
        onException(Exception.class)
                .handled(true)
                .log(LoggingLevel.ERROR, logger, "Error processing {{domain}} message: ${exception.message}")
                .setHeader("CamelHttpResponseCode", constant(500))
                .setBody(constant("{\"error\":\"Internal server error\",\"message\":\"${exception.message}\"}"))
                .setHeader("Content-Type", constant("application/json"));

        // Route 1: Process {{domain}} creation requests from queue/topic
        from("direct:process-{{domain}}-creation")
                .routeId("{{domain}}-creation-route")
                .log(LoggingLevel.INFO, logger, "Processing {{domain}} creation request")
                .unmarshal().json(JsonLibrary.Jackson, {{domainTitleCase}}Request.class)
                .validate(body().isNotNull())
                .validate(simple("${body.name} != null"))
                .bean({{domain}}Service, "create{{domainTitleCase}}")
                .marshal().json(JsonLibrary.Jackson)
                .log(LoggingLevel.INFO, logger, "Successfully created {{domain}}: ${body}");

        // Route 2: Process {{domain}} update requests
        from("direct:process-{{domain}}-update")
                .routeId("{{domain}}-update-route")
                .log(LoggingLevel.INFO, logger, "Processing {{domain}} update request for ID: ${header.{{domain}}Id}")
                .unmarshal().json(JsonLibrary.Jackson, {{domainTitleCase}}Request.class)
                .validate(body().isNotNull())
                .validate(header("{{domain}}Id").isNotNull())
                .process(exchange -> {
                    String {{domain}}Id = exchange.getIn().getHeader("{{domain}}Id", String.class);
                    {{domainTitleCase}}Request request = exchange.getIn().getBody({{domainTitleCase}}Request.class);

                    {{domainTitleCase}}Response response = {{domain}}Service.update{{domainTitleCase}}({{domain}}Id, request)
                            .orElseThrow(() -> new RuntimeException("{{domainTitleCase}} not found with ID: " + {{domain}}Id));

                    exchange.getIn().setBody(response);
                })
                .marshal().json(JsonLibrary.Jackson)
                .log(LoggingLevel.INFO, logger, "Successfully updated {{domain}}: ${body}");

        // Route 3: Process {{domain}} deletion requests
        from("direct:process-{{domain}}-deletion")
                .routeId("{{domain}}-deletion-route")
                .log(LoggingLevel.INFO, logger, "Processing {{domain}} deletion request for ID: ${header.{{domain}}Id}")
                .validate(header("{{domain}}Id").isNotNull())
                .process(exchange -> {
                    String {{domain}}Id = exchange.getIn().getHeader("{{domain}}Id", String.class);
                    boolean deleted = {{domain}}Service.delete{{domainTitleCase}}({{domain}}Id);

                    if (!deleted) {
                        throw new RuntimeException("{{domainTitleCase}} not found with ID: " + {{domain}}Id);
                    }

                    exchange.getIn().setBody("{\"message\":\"{{domainTitleCase}} deleted successfully\",\"id\":\"" + {{domain}}Id + "\"}");
                    exchange.getIn().setHeader("Content-Type", "application/json");
                })
                .log(LoggingLevel.INFO, logger, "Successfully deleted {{domain}} with ID: ${header.{{domain}}Id}");

        // Route 4: Sync {{domain}}s to external system (example)
        from("timer://{{domain}}-sync?period=300000") // Every 5 minutes
                .routeId("{{domain}}-sync-route")
                .log(LoggingLevel.INFO, logger, "Starting {{domain}} synchronization")
                .bean({{domain}}Service, "getAll{{domainTitleCase}}s()")
                .marshal().json(JsonLibrary.Jackson)
                .to("log:{{domain}}-sync?level=DEBUG")
                // Add your external system endpoint here
                // .to("http://external-system/api/{{domain}}s")
                .log(LoggingLevel.INFO, logger, "{{domainTitleCase}} synchronization completed");

        // Route 5: Health check route
        from("timer://{{domain}}-health?period=60000") // Every minute
                .routeId("{{domain}}-health-route")
                .process(exchange -> {
                    long count = {{domain}}Service.getAll{{domainTitleCase}}s().size();
                    exchange.getIn().setBody("{\"service\":\"{{domain}}-service\",\"status\":\"healthy\",\"{{domain}}Count\":" + count + "}");
                    exchange.getIn().setHeader("Content-Type", "application/json");
                })
                .to("log:{{domain}}-health?level=DEBUG");

        // Route 6: Error notification route
        from("direct:{{domain}}-error-notification")
                .routeId("{{domain}}-error-notification-route")
                .log(LoggingLevel.ERROR, logger, "{{domainTitleCase}} service error: ${body}")
                .setBody(simple("{\"service\":\"{{domain}}-service\",\"error\":\"${body}\",\"timestamp\":\"${date:now:yyyy-MM-dd'T'HH:mm:ss}\"}"))
                .setHeader("Content-Type", constant("application/json"))
                // Add notification endpoint here (email, Slack, etc.)
                // .to("smtp://notification@company.com")
                .to("log:{{domain}}-error?level=ERROR");

        // Route 7: Search route (example of complex processing)
        from("direct:search-{{domain}}s")
                .routeId("{{domain}}-search-route")
                .log(LoggingLevel.INFO, logger, "Searching {{domain}}s with criteria: ${header.searchText}")
                .validate(header("searchText").isNotNull())
                .process(exchange -> {
                    String searchText = exchange.getIn().getHeader("searchText", String.class);
                    exchange.getIn().setBody({{domain}}Service.search{{domainTitleCase}}s(searchText));
                })
                .marshal().json(JsonLibrary.Jackson)
                .log(LoggingLevel.INFO, logger, "Search completed, found ${header.CamelSplitSize} {{domain}}s");
    }
}