package {{packageName}}.service;

import {{packageName}}.dto.{{domainTitleCase}}Request;
import {{packageName}}.dto.{{domainTitleCase}}Response;
import {{packageName}}.entity.{{domainTitleCase}};
import {{packageName}}.mapper.{{domainTitleCase}}Mapper;
import {{packageName}}.repository.{{domainTitleCase}}Repository;
import {{packageName}}.service.impl.{{domainTitleCase}}ServiceImpl;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

/**
 * Unit tests for {{domainTitleCase}}Service
 *
 * Tests all business logic without external dependencies using Mockito.
 * Generated by Enterprise CLI - customize according to your business requirements.
 */
@ExtendWith(MockitoExtension.class)
@DisplayName("{{domainTitleCase}} Service Tests")
class {{domainTitleCase}}ServiceTest {

    @Mock
    private {{domainTitleCase}}Repository {{domain}}Repository;

    @Mock
    private {{domainTitleCase}}Mapper {{domain}}Mapper;

    @InjectMocks
    private {{domainTitleCase}}ServiceImpl {{domain}}Service;

    private {{domainTitleCase}} test{{domainTitleCase}};
    private {{domainTitleCase}}Request test{{domainTitleCase}}Request;
    private {{domainTitleCase}}Response test{{domainTitleCase}}Response;

    @BeforeEach
    void setUp() {
        // Setup test entities
        test{{domainTitleCase}} = new {{domainTitleCase}}();
        test{{domainTitleCase}}.setId("test-id-123");
        test{{domainTitleCase}}.setName("Test {{domainTitleCase}}");
        test{{domainTitleCase}}.setDescription("Test description");
        test{{domainTitleCase}}.setCreatedAt(LocalDateTime.now().minusDays(1));
        test{{domainTitleCase}}.setUpdatedAt(LocalDateTime.now());
        test{{domainTitleCase}}.setVersion(1L);

        // Setup test DTOs
        test{{domainTitleCase}}Request = new {{domainTitleCase}}Request();
        test{{domainTitleCase}}Request.setName("Test {{domainTitleCase}}");
        test{{domainTitleCase}}Request.setDescription("Test description");

        test{{domainTitleCase}}Response = new {{domainTitleCase}}Response();
        test{{domainTitleCase}}Response.setId("test-id-123");
        test{{domainTitleCase}}Response.setName("Test {{domainTitleCase}}");
        test{{domainTitleCase}}Response.setDescription("Test description");
        test{{domainTitleCase}}Response.setCreatedAt(test{{domainTitleCase}}.getCreatedAt());
        test{{domainTitleCase}}Response.setUpdatedAt(test{{domainTitleCase}}.getUpdatedAt());
    }

    @Test
    @DisplayName("Should create {{domain}} successfully")
    void shouldCreate{{domainTitleCase}}Successfully() {
        // Given
        when({{domain}}Repository.existsByNameIgnoreCase(test{{domainTitleCase}}Request.getName()))
                .thenReturn(false);
        when({{domain}}Repository.save(any({{domainTitleCase}}.class)))
                .thenReturn(test{{domainTitleCase}});

        // When
        {{domainTitleCase}}Response result = {{domain}}Service.create{{domainTitleCase}}(test{{domainTitleCase}}Request);

        // Then
        assertThat(result).isNotNull();
        assertThat(result.getName()).isEqualTo(test{{domainTitleCase}}Request.getName());
        assertThat(result.getDescription()).isEqualTo(test{{domainTitleCase}}Request.getDescription());

        verify({{domain}}Repository).existsByNameIgnoreCase(test{{domainTitleCase}}Request.getName());
        verify({{domain}}Repository).save(any({{domainTitleCase}}.class));
    }

    @Test
    @DisplayName("Should throw exception when creating {{domain}} with existing name")
    void shouldThrowExceptionWhenCreating{{domainTitleCase}}WithExistingName() {
        // Given
        when({{domain}}Repository.existsByNameIgnoreCase(test{{domainTitleCase}}Request.getName()))
                .thenReturn(true);

        // When & Then
        assertThatThrownBy(() -> {{domain}}Service.create{{domainTitleCase}}(test{{domainTitleCase}}Request))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("{{domainTitleCase}} with name")
                .hasMessageContaining("already exists");

        verify({{domain}}Repository).existsByNameIgnoreCase(test{{domainTitleCase}}Request.getName());
        verify({{domain}}Repository, never()).save(any({{domainTitleCase}}.class));
    }

    @Test
    @DisplayName("Should get {{domain}} by ID successfully")
    void shouldGet{{domainTitleCase}}ByIdSuccessfully() {
        // Given
        String {{domain}}Id = "test-id-123";
        when({{domain}}Repository.findById({{domain}}Id))
                .thenReturn(Optional.of(test{{domainTitleCase}}));

        // When
        Optional<{{domainTitleCase}}Response> result = {{domain}}Service.get{{domainTitleCase}}ById({{domain}}Id);

        // Then
        assertThat(result).isPresent();
        assertThat(result.get().getId()).isEqualTo({{domain}}Id);
        assertThat(result.get().getName()).isEqualTo(test{{domainTitleCase}}.getName());

        verify({{domain}}Repository).findById({{domain}}Id);
    }

    @Test
    @DisplayName("Should return empty when {{domain}} not found by ID")
    void shouldReturnEmptyWhen{{domainTitleCase}}NotFoundById() {
        // Given
        String {{domain}}Id = "non-existent-id";
        when({{domain}}Repository.findById({{domain}}Id))
                .thenReturn(Optional.empty());

        // When
        Optional<{{domainTitleCase}}Response> result = {{domain}}Service.get{{domainTitleCase}}ById({{domain}}Id);

        // Then
        assertThat(result).isEmpty();

        verify({{domain}}Repository).findById({{domain}}Id);
    }

    @Test
    @DisplayName("Should get all {{domain}}s successfully")
    void shouldGetAll{{domainTitleCase}}sSuccessfully() {
        // Given
        List<{{domainTitleCase}}> {{domain}}List = Arrays.asList(test{{domainTitleCase}}, test{{domainTitleCase}});
        when({{domain}}Repository.findAll())
                .thenReturn({{domain}}List);

        // When
        List<{{domainTitleCase}}Response> result = {{domain}}Service.getAll{{domainTitleCase}}s();

        // Then
        assertThat(result).hasSize(2);
        assertThat(result.get(0).getName()).isEqualTo(test{{domainTitleCase}}.getName());

        verify({{domain}}Repository).findAll();
    }

    @Test
    @DisplayName("Should get all {{domain}}s with pagination successfully")
    void shouldGetAll{{domainTitleCase}}sWithPaginationSuccessfully() {
        // Given
        Pageable pageable = PageRequest.of(0, 10);
        List<{{domainTitleCase}}> {{domain}}List = Arrays.asList(test{{domainTitleCase}});
        Page<{{domainTitleCase}}> {{domain}}Page = new PageImpl<>({{domain}}List, pageable, 1);
        when({{domain}}Repository.findAll(pageable))
                .thenReturn({{domain}}Page);

        // When
        Page<{{domainTitleCase}}Response> result = {{domain}}Service.getAll{{domainTitleCase}}s(pageable);

        // Then
        assertThat(result.getContent()).hasSize(1);
        assertThat(result.getTotalElements()).isEqualTo(1);
        assertThat(result.getContent().get(0).getName()).isEqualTo(test{{domainTitleCase}}.getName());

        verify({{domain}}Repository).findAll(pageable);
    }

    @Test
    @DisplayName("Should update {{domain}} successfully")
    void shouldUpdate{{domainTitleCase}}Successfully() {
        // Given
        String {{domain}}Id = "test-id-123";
        {{domainTitleCase}}Request updateRequest = new {{domainTitleCase}}Request();
        updateRequest.setName("Updated {{domainTitleCase}}");
        updateRequest.setDescription("Updated description");

        {{domainTitleCase}} updated{{domainTitleCase}} = new {{domainTitleCase}}();
        updated{{domainTitleCase}}.setId({{domain}}Id);
        updated{{domainTitleCase}}.setName(updateRequest.getName());
        updated{{domainTitleCase}}.setDescription(updateRequest.getDescription());
        updated{{domainTitleCase}}.setCreatedAt(test{{domainTitleCase}}.getCreatedAt());
        updated{{domainTitleCase}}.setUpdatedAt(LocalDateTime.now());

        when({{domain}}Repository.findById({{domain}}Id))
                .thenReturn(Optional.of(test{{domainTitleCase}}));
        when({{domain}}Repository.existsByNameIgnoreCase(updateRequest.getName()))
                .thenReturn(false);
        when({{domain}}Repository.save(any({{domainTitleCase}}.class)))
                .thenReturn(updated{{domainTitleCase}});

        // When
        Optional<{{domainTitleCase}}Response> result = {{domain}}Service.update{{domainTitleCase}}({{domain}}Id, updateRequest);

        // Then
        assertThat(result).isPresent();
        assertThat(result.get().getName()).isEqualTo(updateRequest.getName());
        assertThat(result.get().getDescription()).isEqualTo(updateRequest.getDescription());

        verify({{domain}}Repository).findById({{domain}}Id);
        verify({{domain}}Repository).save(any({{domainTitleCase}}.class));
    }

    @Test
    @DisplayName("Should return empty when updating non-existent {{domain}}")
    void shouldReturnEmptyWhenUpdatingNonExistent{{domainTitleCase}}() {
        // Given
        String {{domain}}Id = "non-existent-id";
        when({{domain}}Repository.findById({{domain}}Id))
                .thenReturn(Optional.empty());

        // When
        Optional<{{domainTitleCase}}Response> result = {{domain}}Service.update{{domainTitleCase}}({{domain}}Id, test{{domainTitleCase}}Request);

        // Then
        assertThat(result).isEmpty();

        verify({{domain}}Repository).findById({{domain}}Id);
        verify({{domain}}Repository, never()).save(any({{domainTitleCase}}.class));
    }

    @Test
    @DisplayName("Should delete {{domain}} successfully")
    void shouldDelete{{domainTitleCase}}Successfully() {
        // Given
        String {{domain}}Id = "test-id-123";
        when({{domain}}Repository.existsById({{domain}}Id))
                .thenReturn(true);

        // When
        boolean result = {{domain}}Service.delete{{domainTitleCase}}({{domain}}Id);

        // Then
        assertThat(result).isTrue();

        verify({{domain}}Repository).existsById({{domain}}Id);
        verify({{domain}}Repository).deleteById({{domain}}Id);
    }

    @Test
    @DisplayName("Should return false when deleting non-existent {{domain}}")
    void shouldReturnFalseWhenDeletingNonExistent{{domainTitleCase}}() {
        // Given
        String {{domain}}Id = "non-existent-id";
        when({{domain}}Repository.existsById({{domain}}Id))
                .thenReturn(false);

        // When
        boolean result = {{domain}}Service.delete{{domainTitleCase}}({{domain}}Id);

        // Then
        assertThat(result).isFalse();

        verify({{domain}}Repository).existsById({{domain}}Id);
        verify({{domain}}Repository, never()).deleteById({{domain}}Id);
    }

    @Test
    @DisplayName("Should search {{domain}}s successfully")
    void shouldSearch{{domainTitleCase}}sSuccessfully() {
        // Given
        String searchText = "test";
        List<{{domainTitleCase}}> {{domain}}List = Arrays.asList(test{{domainTitleCase}});
        when({{domain}}Repository.findByNameOrDescriptionContaining(searchText))
                .thenReturn({{domain}}List);

        // When
        List<{{domainTitleCase}}Response> result = {{domain}}Service.search{{domainTitleCase}}s(searchText);

        // Then
        assertThat(result).hasSize(1);
        assertThat(result.get(0).getName()).isEqualTo(test{{domainTitleCase}}.getName());

        verify({{domain}}Repository).findByNameOrDescriptionContaining(searchText);
    }

    @Test
    @DisplayName("Should check if {{domain}} exists by name")
    void shouldCheckIf{{domainTitleCase}}ExistsByName() {
        // Given
        String {{domain}}Name = "Test {{domainTitleCase}}";
        when({{domain}}Repository.existsByNameIgnoreCase({{domain}}Name))
                .thenReturn(true);

        // When
        boolean result = {{domain}}Service.exists{{domainTitleCase}}ByName({{domain}}Name);

        // Then
        assertThat(result).isTrue();

        verify({{domain}}Repository).existsByNameIgnoreCase({{domain}}Name);
    }

    @Test
    @DisplayName("Should convert entity to response DTO correctly")
    void shouldConvertEntityToResponseCorrectly() {
        // When - using mapper directly since convertToResponse is protected
        {{domainTitleCase}}Response result = {{domain}}Mapper.toResponse(test{{domainTitleCase}});

        // Then
        assertThat(result).isNotNull();
        assertThat(result.getId()).isEqualTo(test{{domainTitleCase}}.getId());
        assertThat(result.getName()).isEqualTo(test{{domainTitleCase}}.getName());
        assertThat(result.getDescription()).isEqualTo(test{{domainTitleCase}}.getDescription());
        assertThat(result.getCreatedAt()).isEqualTo(test{{domainTitleCase}}.getCreatedAt());
        assertThat(result.getUpdatedAt()).isEqualTo(test{{domainTitleCase}}.getUpdatedAt());
    }

    @Test
    @DisplayName("Should convert request DTO to entity correctly")
    void shouldConvertRequestToEntityCorrectly() {
        // When
        {{domainTitleCase}} result = {{domain}}Service.convertToEntity(test{{domainTitleCase}}Request);

        // Then
        assertThat(result).isNotNull();
        assertThat(result.getName()).isEqualTo(test{{domainTitleCase}}Request.getName());
        assertThat(result.getDescription()).isEqualTo(test{{domainTitleCase}}Request.getDescription());
        assertThat(result.getId()).isNull(); // Should be null for new entities
    }
}