package {{packageName}}.repository;

import {{packageName}}.entity.{{domainTitleCase}};
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager;
import org.springframework.test.context.ActiveProfiles;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.*;

/**
 * Simple repository layer tests for {{domainTitleCase}}Repository
 *
 * Uses @DataJpaTest for lightweight JPA testing with H2 database.
 * Generated by Enterprise CLI.
 */
@DataJpaTest
@ActiveProfiles("test")
@DisplayName("{{domainTitleCase}} Repository Tests")
class {{domainTitleCase}}RepositoryTest {

    @Autowired
    private TestEntityManager entityManager;

    @Autowired
    private {{domainTitleCase}}Repository {{domain}}Repository;

    private {{domainTitleCase}} test{{domainTitleCase}}1;
    private {{domainTitleCase}} test{{domainTitleCase}}2;

    @BeforeEach
    void setUp() {
        // Setup test entities
        test{{domainTitleCase}}1 = new {{domainTitleCase}}();
        test{{domainTitleCase}}1.setName("First Test {{domainTitleCase}}");
        test{{domainTitleCase}}1.setDescription("First test description");
        test{{domainTitleCase}}1.setBusinessId("BUS-001");
        test{{domainTitleCase}}1.setStatus("ACTIVE");

        test{{domainTitleCase}}2 = new {{domainTitleCase}}();
        test{{domainTitleCase}}2.setName("Second Test {{domainTitleCase}}");
        test{{domainTitleCase}}2.setDescription("Second test description");
        test{{domainTitleCase}}2.setBusinessId("BUS-002");
        test{{domainTitleCase}}2.setStatus("ACTIVE");

        // Persist test entities
        entityManager.persistAndFlush(test{{domainTitleCase}}1);
        entityManager.persistAndFlush(test{{domainTitleCase}}2);
    }

    @Test
    @DisplayName("Should save and retrieve {{domain}} successfully")
    void shouldSaveAndRetrieve{{domainTitleCase}}Successfully() {
        // Given
        {{domainTitleCase}} new{{domainTitleCase}} = new {{domainTitleCase}}();
        new{{domainTitleCase}}.setName("New {{domainTitleCase}}");
        new{{domainTitleCase}}.setDescription("New description");
        new{{domainTitleCase}}.setBusinessId("BUS-003");
        new{{domainTitleCase}}.setStatus("ACTIVE");

        // When
        {{domainTitleCase}} saved{{domainTitleCase}} = {{domain}}Repository.save(new{{domainTitleCase}});

        // Then
        assertThat(saved{{domainTitleCase}}).isNotNull();
        assertThat(saved{{domainTitleCase}}.getId()).isNotNull();
        assertThat(saved{{domainTitleCase}}.getName()).isEqualTo("New {{domainTitleCase}}");
    }

    @Test
    @DisplayName("Should find {{domain}} by name ignore case")
    void shouldFind{{domainTitleCase}}ByNameIgnoreCase() {
        // When
        Optional<{{domainTitleCase}}> found = {{domain}}Repository.findByNameIgnoreCase("FIRST TEST {{domainTitleCase}}");

        // Then
        assertThat(found).isPresent();
        assertThat(found.get().getName()).isEqualTo("First Test {{domainTitleCase}}");
    }

    @Test
    @DisplayName("Should find {{domain}}s by name or description containing text")
    void shouldFind{{domainTitleCase}}sByNameOrDescriptionContaining() {
        // When
        List<{{domainTitleCase}}> found = {{domain}}Repository.findByNameOrDescriptionContaining("test");

        // Then
        assertThat(found).hasSize(2);
        assertThat(found).extracting({{domainTitleCase}}::getName)
                .contains("First Test {{domainTitleCase}}", "Second Test {{domainTitleCase}}");
    }

    @Test
    @DisplayName("Should find {{domain}}s created after specific date")
    void shouldFind{{domainTitleCase}}sCreatedAfterSpecificDate() {
        // Given
        LocalDateTime yesterday = LocalDateTime.now().minusDays(1);

        // When
        List<{{domainTitleCase}}> found = {{domain}}Repository.findByCreatedAtAfter(yesterday);

        // Then
        assertThat(found).hasSize(2);
    }

    @Test
    @DisplayName("Should find {{domain}}s by name pattern containing")
    void shouldFind{{domainTitleCase}}sByNamePatternContaining() {
        // When
        List<{{domainTitleCase}}> found = {{domain}}Repository.findByNameContainingIgnoreCase("FIRST");

        // Then
        assertThat(found).hasSize(1);
        assertThat(found.get(0).getName()).isEqualTo("First Test {{domainTitleCase}}");
    }

    @Test
    @DisplayName("Should check if {{domain}} exists by name ignore case")
    void shouldCheckIf{{domainTitleCase}}ExistsByNameIgnoreCase() {
        // When
        boolean exists = {{domain}}Repository.existsByNameIgnoreCase("first test {{domain}}");

        // Then
        assertThat(exists).isTrue();
    }

    @Test
    @DisplayName("Should count {{domain}}s created after specific date")
    void shouldCount{{domainTitleCase}}sCreatedAfterSpecificDate() {
        // Given
        LocalDateTime yesterday = LocalDateTime.now().minusDays(1);

        // When
        long count = {{domain}}Repository.countByCreatedAtAfter(yesterday);

        // Then
        assertThat(count).isEqualTo(2);
    }

    @Test
    @DisplayName("Should find active {{domain}}s")
    void shouldFindActive{{domainTitleCase}}s() {
        // When
        List<{{domainTitleCase}}> active{{domainTitleCase}}s = {{domain}}Repository.findActive{{domainTitleCase}}s();

        // Then
        assertThat(active{{domainTitleCase}}s).hasSize(2);
        assertThat(active{{domainTitleCase}}s).allMatch({{domain}} ->
                {{domain}}.getDescription() != null && !{{domain}}.getDescription().isEmpty());
    }

    @Test
    @DisplayName("Should delete {{domain}} by ID")
    void shouldDelete{{domainTitleCase}}ById() {
        // Given
        String {{domain}}Id = test{{domainTitleCase}}1.getId();

        // When
        {{domain}}Repository.deleteById({{domain}}Id);

        // Then
        Optional<{{domainTitleCase}}> deleted{{domainTitleCase}} = {{domain}}Repository.findById({{domain}}Id);
        assertThat(deleted{{domainTitleCase}}).isEmpty();

        // Verify other {{domain}} still exists
        List<{{domainTitleCase}}> remaining{{domainTitleCase}}s = {{domain}}Repository.findAll();
        assertThat(remaining{{domainTitleCase}}s).hasSize(1);
        assertThat(remaining{{domainTitleCase}}s.get(0).getName()).isEqualTo("Second Test {{domainTitleCase}}");
    }
}