package {{packageName}}.repository;

import {{packageName}}.entity.{{domainTitleCase}};
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager;
import org.springframework.test.context.ActiveProfiles;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.*;

/**
 * Repository layer tests for {{domainTitleCase}}Repository
 *
 * Uses @DataJpaTest for optimized JPA testing with in-memory database.
 * Generated by Enterprise CLI - customize according to your business requirements.
 */
@DataJpaTest
@ActiveProfiles("test")
@DisplayName("{{domainTitleCase}} Repository Tests")
class {{domainTitleCase}}RepositoryTest {

    @Autowired
    private TestEntityManager entityManager;

    @Autowired
    private {{domainTitleCase}}Repository {{domain}}Repository;

    private {{domainTitleCase}} test{{domainTitleCase}}1;
    private {{domainTitleCase}} test{{domainTitleCase}}2;

    @BeforeEach
    void setUp() {
        // Setup test entities
        test{{domainTitleCase}}1 = new {{domainTitleCase}}();
        test{{domainTitleCase}}1.setName("First Test {{domainTitleCase}}");
        test{{domainTitleCase}}1.setDescription("First test description");

        test{{domainTitleCase}}2 = new {{domainTitleCase}}();
        test{{domainTitleCase}}2.setName("Second Test {{domainTitleCase}}");
        test{{domainTitleCase}}2.setDescription("Second test description with different content");

        // Persist test entities
        entityManager.persistAndFlush(test{{domainTitleCase}}1);
        entityManager.persistAndFlush(test{{domainTitleCase}}2);
    }

    @Test
    @DisplayName("Should save and retrieve {{domain}} successfully")
    void shouldSaveAndRetrieve{{domainTitleCase}}Successfully() {
        // Given
        {{domainTitleCase}} new{{domainTitleCase}} = new {{domainTitleCase}}();
        new{{domainTitleCase}}.setName("New {{domainTitleCase}}");
        new{{domainTitleCase}}.setDescription("New description");

        // When
        {{domainTitleCase}} saved{{domainTitleCase}} = {{domain}}Repository.save(new{{domainTitleCase}});

        // Then
        assertThat(saved{{domainTitleCase}}).isNotNull();
        assertThat(saved{{domainTitleCase}}.getId()).isNotNull();
        assertThat(saved{{domainTitleCase}}.getName()).isEqualTo("New {{domainTitleCase}}");
        assertThat(saved{{domainTitleCase}}.getCreatedAt()).isNotNull();
        assertThat(saved{{domainTitleCase}}.getUpdatedAt()).isNotNull();
        assertThat(saved{{domainTitleCase}}.getVersion()).isEqualTo(0L);
    }

    @Test
    @DisplayName("Should find {{domain}} by name ignore case")
    void shouldFind{{domainTitleCase}}ByNameIgnoreCase() {
        // When
        Optional<{{domainTitleCase}}> found = {{domain}}Repository.findByNameIgnoreCase("FIRST TEST {{domainTitleCase}}");

        // Then
        assertThat(found).isPresent();
        assertThat(found.get().getName()).isEqualTo("First Test {{domainTitleCase}}");
    }

    @Test
    @DisplayName("Should return empty when {{domain}} not found by name")
    void shouldReturnEmptyWhen{{domainTitleCase}}NotFoundByName() {
        // When
        Optional<{{domainTitleCase}}> found = {{domain}}Repository.findByNameIgnoreCase("Non Existent {{domainTitleCase}}");

        // Then
        assertThat(found).isEmpty();
    }

    @Test
    @DisplayName("Should find {{domain}}s by name or description containing text")
    void shouldFind{{domainTitleCase}}sByNameOrDescriptionContaining() {
        // When
        List<{{domainTitleCase}}> found = {{domain}}Repository.findByNameOrDescriptionContaining("test");

        // Then
        assertThat(found).hasSize(2);
        assertThat(found).extracting({{domainTitleCase}}::getName)
                .contains("First Test {{domainTitleCase}}", "Second Test {{domainTitleCase}}");
    }

    @Test
    @DisplayName("Should find {{domain}}s by description containing text")
    void shouldFind{{domainTitleCase}}sByDescriptionContaining() {
        // When
        List<{{domainTitleCase}}> found = {{domain}}Repository.findByNameOrDescriptionContaining("different");

        // Then
        assertThat(found).hasSize(1);
        assertThat(found.get(0).getName()).isEqualTo("Second Test {{domainTitleCase}}");
    }

    @Test
    @DisplayName("Should find {{domain}}s created after specific date")
    void shouldFind{{domainTitleCase}}sCreatedAfterSpecificDate() {
        // Given
        LocalDateTime yesterday = LocalDateTime.now().minusDays(1);

        // When
        List<{{domainTitleCase}}> found = {{domain}}Repository.findByCreatedAtAfter(yesterday);

        // Then
        assertThat(found).hasSize(2);
        assertThat(found).extracting({{domainTitleCase}}::getName)
                .contains("First Test {{domainTitleCase}}", "Second Test {{domainTitleCase}}");
    }

    @Test
    @DisplayName("Should find {{domain}}s by name pattern containing")
    void shouldFind{{domainTitleCase}}sByNamePatternContaining() {
        // When
        List<{{domainTitleCase}}> found = {{domain}}Repository.findByNameContainingIgnoreCase("FIRST");

        // Then
        assertThat(found).hasSize(1);
        assertThat(found.get(0).getName()).isEqualTo("First Test {{domainTitleCase}}");
    }

    @Test
    @DisplayName("Should check if {{domain}} exists by name ignore case")
    void shouldCheckIf{{domainTitleCase}}ExistsByNameIgnoreCase() {
        // When
        boolean exists = {{domain}}Repository.existsByNameIgnoreCase("first test {{domainTitleCase}}");

        // Then
        assertThat(exists).isTrue();
    }

    @Test
    @DisplayName("Should return false when {{domain}} does not exist by name")
    void shouldReturnFalseWhen{{domainTitleCase}}DoesNotExistByName() {
        // When
        boolean exists = {{domain}}Repository.existsByNameIgnoreCase("Non Existent {{domainTitleCase}}");

        // Then
        assertThat(exists).isFalse();
    }

    @Test
    @DisplayName("Should count {{domain}}s created after specific date")
    void shouldCount{{domainTitleCase}}sCreatedAfterSpecificDate() {
        // Given
        LocalDateTime yesterday = LocalDateTime.now().minusDays(1);

        // When
        long count = {{domain}}Repository.countByCreatedAtAfter(yesterday);

        // Then
        assertThat(count).isEqualTo(2);
    }

    @Test
    @DisplayName("Should find active {{domain}}s")
    void shouldFindActive{{domainTitleCase}}s() {
        // When
        List<{{domainTitleCase}}> active{{domainTitleCase}}s = {{domain}}Repository.findActive{{domainTitleCase}}s();

        // Then
        assertThat(active{{domainTitleCase}}s).hasSize(2);
        assertThat(active{{domainTitleCase}}s).allMatch({{domain}} ->
                {{domain}}.getDescription() != null && !{{domain}}.getDescription().isEmpty());
    }

    @Test
    @DisplayName("Should update {{domain}} optimistically")
    void shouldUpdate{{domainTitleCase}}Optimistically() {
        // Given
        {{domainTitleCase}} {{domain}}ToUpdate = entityManager.find({{domainTitleCase}}.class, test{{domainTitleCase}}1.getId());
        Long originalVersion = {{domain}}ToUpdate.getVersion();

        // When
        {{domain}}ToUpdate.setName("Updated Name");
        {{domainTitleCase}} updated{{domainTitleCase}} = {{domain}}Repository.save({{domain}}ToUpdate);

        // Then
        assertThat(updated{{domainTitleCase}}.getName()).isEqualTo("Updated Name");
        assertThat(updated{{domainTitleCase}}.getVersion()).isGreaterThan(originalVersion);
        assertThat(updated{{domainTitleCase}}.getUpdatedAt()).isAfter(updated{{domainTitleCase}}.getCreatedAt());
    }

    @Test
    @DisplayName("Should delete {{domain}} by ID")
    void shouldDelete{{domainTitleCase}}ById() {
        // Given
        String {{domain}}Id = test{{domainTitleCase}}1.getId();

        // When
        {{domain}}Repository.deleteById({{domain}}Id);

        // Then
        Optional<{{domainTitleCase}}> deleted{{domainTitleCase}} = {{domain}}Repository.findById({{domain}}Id);
        assertThat(deleted{{domainTitleCase}}).isEmpty();

        // Verify other {{domain}} still exists
        List<{{domainTitleCase}}> remaining{{domainTitleCase}}s = {{domain}}Repository.findAll();
        assertThat(remaining{{domainTitleCase}}s).hasSize(1);
        assertThat(remaining{{domainTitleCase}}s.get(0).getName()).isEqualTo("Second Test {{domainTitleCase}}");
    }

    @Test
    @DisplayName("Should enforce unique constraint on name")
    void shouldEnforceUniqueConstraintOnName() {
        // Given
        {{domainTitleCase}} duplicate{{domainTitleCase}} = new {{domainTitleCase}}();
        duplicate{{domainTitleCase}}.setName("First Test {{domainTitleCase}}"); // Same name as existing
        duplicate{{domainTitleCase}}.setDescription("Different description");

        // When & Then
        assertThatThrownBy(() -> {
            {{domain}}Repository.save(duplicate{{domainTitleCase}});
            entityManager.flush(); // Force database constraint check
        }).isInstanceOf(Exception.class); // Could be ConstraintViolationException or DataIntegrityViolationException
    }

    @Test
    @DisplayName("Should handle null description gracefully")
    void shouldHandleNullDescriptionGracefully() {
        // Given
        {{domainTitleCase}} {{domain}}WithNullDescription = new {{domainTitleCase}}();
        {{domain}}WithNullDescription.setName("{{domainTitleCase}} with Null Description");
        {{domain}}WithNullDescription.setDescription(null);

        // When
        {{domainTitleCase}} saved{{domainTitleCase}} = {{domain}}Repository.save({{domain}}WithNullDescription);

        // Then
        assertThat(saved{{domainTitleCase}}).isNotNull();
        assertThat(saved{{domainTitleCase}}.getDescription()).isNull();

        // Should not appear in active {{domain}}s
        List<{{domainTitleCase}}> active{{domainTitleCase}}s = {{domain}}Repository.findActive{{domainTitleCase}}s();
        assertThat(active{{domainTitleCase}}s).doesNotContain(saved{{domainTitleCase}});
    }

    @Test
    @DisplayName("Should maintain audit fields automatically")
    void shouldMaintainAuditFieldsAutomatically() {
        // Given
        {{domainTitleCase}} new{{domainTitleCase}} = new {{domainTitleCase}}();
        new{{domainTitleCase}}.setName("Audit Test {{domainTitleCase}}");
        new{{domainTitleCase}}.setDescription("Testing audit fields");

        // When
        {{domainTitleCase}} saved{{domainTitleCase}} = {{domain}}Repository.save(new{{domainTitleCase}});

        // Then
        assertThat(saved{{domainTitleCase}}.getCreatedAt()).isNotNull();
        assertThat(saved{{domainTitleCase}}.getUpdatedAt()).isNotNull();
        assertThat(saved{{domainTitleCase}}.getCreatedAt()).isEqualTo(saved{{domainTitleCase}}.getUpdatedAt());

        // When updating
        saved{{domainTitleCase}}.setName("Updated Audit Test {{domainTitleCase}}");
        {{domainTitleCase}} updated{{domainTitleCase}} = {{domain}}Repository.save(saved{{domainTitleCase}});

        // Then
        assertThat(updated{{domainTitleCase}}.getUpdatedAt()).isAfter(updated{{domainTitleCase}}.getCreatedAt());
    }
}