/*
 * Copyright (c) {{year}} {{packageName}}
 * All rights reserved.
 */
package {{packageName}}.dto;

import {{packageName}}.enterprise.framework.constants.FrameworkConstants.ValidationLimits;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.Data;

/**
 * {{domainTitleCase}} Request DTO
 *
 * <p>Used for CREATE and UPDATE operations.
 * Contains only business fields that can be set by clients.
 *
 * <p><strong>Does NOT include:</strong>
 * <ul>
 *   <li>id - Generated by database</li>
 *   <li>Audit fields (createdBy, createdAt, updatedBy, updatedAt) - Set by framework</li>
 *   <li>Soft delete fields (deleted, deletedAt, deletedBy) - Managed by framework</li>
 *   <li>version - Managed by JPA for optimistic locking</li>
 * </ul>
 *
 * <p><strong>Example JSON:</strong>
 * <pre>
 * {
 *   "name": "Sample {{domainTitleCase}}",
 *   "description": "This is a sample {{domain}}",
 *   "status": "ACTIVE"
 * }
 * </pre>
 *
 * @author Enterprise CLI
 * @version {{frameworkVersion}}
 */
@Data
public class {{domainTitleCase}}Request {

    /**
     * Name of the {{domain}}.
     * Required, 1-100 characters.
     */
    @NotBlank(message = "Name is required")
    @Size(min = ValidationLimits.NAME_MIN_LENGTH, max = ValidationLimits.NAME_MAX_LENGTH,
          message = "Name must be between " + ValidationLimits.NAME_MIN_LENGTH + " and " + ValidationLimits.NAME_MAX_LENGTH + " characters")
    private String name;

    /**
     * Description of the {{domain}}.
     * Optional, max 500 characters.
     */
    @Size(max = ValidationLimits.DESCRIPTION_MAX_LENGTH,
          message = "Description must not exceed " + ValidationLimits.DESCRIPTION_MAX_LENGTH + " characters")
    private String description;

    /**
     * Status of the {{domain}}.
     * Optional, defaults to ACTIVE.
     * Valid values: ACTIVE, INACTIVE, PENDING
     */
    @Size(max = ValidationLimits.STATUS_MAX_LENGTH,
          message = "Status must not exceed " + ValidationLimits.STATUS_MAX_LENGTH + " characters")
    private String status;
}
