package {{packageName}}.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

/**
 * Request DTO for {{domainTitleCase}} operations
 *
 * This is a sample DTO generated by Enterprise CLI.
 * Customize fields and validation according to your business requirements.
 */
@Schema(description = "{{domainTitleCase}} request data")
public class {{domainTitleCase}}Request {

    @Schema(description = "Name of the {{domain}}", example = "Sample {{domainTitleCase}} Name", required = true)
    @NotBlank(message = "{{domainTitleCase}} name is required")
    @Size(min = 2, max = 100, message = "{{domainTitleCase}} name must be between 2 and 100 characters")
    private String name;

    @Schema(description = "Description of the {{domain}}", example = "This is a sample {{domain}} description")
    @Size(max = 500, message = "{{domainTitleCase}} description cannot exceed 500 characters")
    private String description;

    // Default constructor
    public {{domainTitleCase}}Request() {
    }

    // Constructor with all fields
    public {{domainTitleCase}}Request(String name, String description) {
        this.name = name;
        this.description = description;
    }

    // Getters and Setters
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public String toString() {
        return "{{domainTitleCase}}Request{" +
                "name='" + name + '\'' +
                ", description='" + description + '\'' +
                '}';
    }
}