package {{packageName}};

import {{packageName}}.enterprise.annotations.EnableEnterpriseFramework;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * {{serviceNameTitleCase}} Spring Boot Application
 *
 * Generated by Enterprise CLI on {{timestamp}}
 *
 * This is the main entry point for the {{serviceName}} microservice.
 * It includes enterprise-ready configurations for JPA, transactions, and security.
 */
@SpringBootApplication
@EnableEnterpriseFramework
public class {{serviceNameTitleCase}}Application {

    public static void main(String[] args) {
        SpringApplication.run({{serviceNameTitleCase}}Application.class, args);
    }

}