package {{packageName}};

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.domain.EntityScan;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;
import org.springframework.transaction.annotation.EnableTransactionManagement;

/**
 * {{serviceNameTitleCase}} Spring Boot Application
 *
 * Generated by Enterprise CLI on {{timestamp}}
 *
 * This is the main entry point for the {{serviceName}} microservice.
 * It includes enterprise-ready configurations for JPA, transactions, and security.
 */
@SpringBootApplication
@EnableJpaRepositories(basePackages = "{{packageName}}.repository")
@EntityScan(basePackages = "{{packageName}}.entity")
@EnableTransactionManagement
public class {{serviceNameTitleCase}}Application {

    public static void main(String[] args) {
        SpringApplication.run({{serviceNameTitleCase}}Application.class, args);
    }

}