package {{packageName}}.config;

import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Primary;
import org.springframework.context.annotation.Profile;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configurers.AbstractHttpConfigurer;
import org.springframework.security.web.SecurityFilterChain;

/**
 * Security Test Configuration for {{serviceNameTitleCase}}
 *
 * Disables security for unit and integration tests to avoid authentication issues.
 * Generated by Enterprise CLI - only active in test profile.
 */
@TestConfiguration
@Profile("test")
public class SecurityTestConfig {

    /**
     * Test security filter chain that permits all requests
     */
    @Bean
    @Primary
    public SecurityFilterChain testSecurityFilterChain(HttpSecurity http) throws Exception {
        http
                .csrf(AbstractHttpConfigurer::disable)
                .authorizeHttpRequests(auth -> auth
                        .anyRequest().permitAll()
                )
                .headers(headers -> headers
                        .frameOptions().disable() // Allow H2 console in tests
                );

        return http.build();
    }
}