package {{packageName}}.controller;

import {{packageName}}.dto.{{domainTitleCase}}Request;
import {{packageName}}.dto.{{domainTitleCase}}Response;
import {{packageName}}.service.{{domainTitleCase}}Service;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.http.MediaType;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.web.servlet.MockMvc;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.Optional;

import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

/**
 * Controller layer tests for {{domainTitleCase}}Controller
 *
 * Uses @WebMvcTest for optimized web layer testing with MockMvc.
 * Generated by Enterprise CLI - customize according to your business requirements.
 */
@WebMvcTest({{domainTitleCase}}Controller.class)
@ActiveProfiles("test")
@DisplayName("{{domainTitleCase}} Controller Tests")
class {{domainTitleCase}}ControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private ObjectMapper objectMapper;

    @MockBean
    private {{domainTitleCase}}Service {{domain}}Service;

    private {{domainTitleCase}}Request test{{domainTitleCase}}Request;
    private {{domainTitleCase}}Response test{{domainTitleCase}}Response;
    private List<{{domainTitleCase}}Response> test{{domainTitleCase}}List;

    @BeforeEach
    void setUp() {
        // Setup test DTOs
        test{{domainTitleCase}}Request = new {{domainTitleCase}}Request();
        test{{domainTitleCase}}Request.setName("Test {{domainTitleCase}}");
        test{{domainTitleCase}}Request.setDescription("Test description");

        test{{domainTitleCase}}Response = new {{domainTitleCase}}Response();
        test{{domainTitleCase}}Response.setId("test-id-123");
        test{{domainTitleCase}}Response.setName("Test {{domainTitleCase}}");
        test{{domainTitleCase}}Response.setDescription("Test description");
        test{{domainTitleCase}}Response.setCreatedAt(LocalDateTime.now().minusDays(1));
        test{{domainTitleCase}}Response.setUpdatedAt(LocalDateTime.now());

        {{domainTitleCase}}Response second{{domainTitleCase}} = new {{domainTitleCase}}Response();
        second{{domainTitleCase}}.setId("test-id-456");
        second{{domainTitleCase}}.setName("Second {{domainTitleCase}}");
        second{{domainTitleCase}}.setDescription("Second description");
        second{{domainTitleCase}}.setCreatedAt(LocalDateTime.now().minusDays(2));
        second{{domainTitleCase}}.setUpdatedAt(LocalDateTime.now());

        test{{domainTitleCase}}List = Arrays.asList(test{{domainTitleCase}}Response, second{{domainTitleCase}});
    }

    @Test
    @DisplayName("Should return hello message")
    void shouldReturnHelloMessage() throws Exception {
        mockMvc.perform(get("/{{domain}}s/hello"))
                .andExpect(status().isOk())
                .andExpect(content().string("Hello from {{domainTitleCase}} Service! 🚀"));
    }

    @Test
    @DisplayName("Should get all {{domain}}s successfully")
    void shouldGetAll{{domainTitleCase}}sSuccessfully() throws Exception {
        // Given
        when({{domain}}Service.getAll{{domainTitleCase}}s()).thenReturn(test{{domainTitleCase}}List);

        // When & Then
        mockMvc.perform(get("/{{domain}}s"))
                .andExpect(status().isOk())
                .andExpect(content().contentType(MediaType.APPLICATION_JSON))
                .andExpect(jsonPath("$").isArray())
                .andExpect(jsonPath("$.length()").value(2))
                .andExpect(jsonPath("$[0].id").value("test-id-123"))
                .andExpect(jsonPath("$[0].name").value("Test {{domainTitleCase}}"))
                .andExpect(jsonPath("$[1].id").value("test-id-456"))
                .andExpect(jsonPath("$[1].name").value("Second {{domainTitleCase}}"));

        verify({{domain}}Service).getAll{{domainTitleCase}}s();
    }

    @Test
    @DisplayName("Should get all {{domain}}s with pagination successfully")
    void shouldGetAll{{domainTitleCase}}sWithPaginationSuccessfully() throws Exception {
        // Given
        Page<{{domainTitleCase}}Response> {{domain}}Page = new PageImpl<>(test{{domainTitleCase}}List, PageRequest.of(0, 10), 2);
        when({{domain}}Service.getAll{{domainTitleCase}}s(any())).thenReturn({{domain}}Page);

        // When & Then
        mockMvc.perform(get("/{{domain}}s/paged")
                        .param("page", "0")
                        .param("size", "10"))
                .andExpect(status().isOk())
                .andExpect(content().contentType(MediaType.APPLICATION_JSON))
                .andExpect(jsonPath("$.content").isArray())
                .andExpect(jsonPath("$.content.length()").value(2))
                .andExpect(jsonPath("$.totalElements").value(2))
                .andExpect(jsonPath("$.totalPages").value(1))
                .andExpect(jsonPath("$.size").value(10));

        verify({{domain}}Service).getAll{{domainTitleCase}}s(any());
    }

    @Test
    @DisplayName("Should get {{domain}} by ID successfully")
    void shouldGet{{domainTitleCase}}ByIdSuccessfully() throws Exception {
        // Given
        String {{domain}}Id = "test-id-123";
        when({{domain}}Service.get{{domainTitleCase}}ById({{domain}}Id)).thenReturn(Optional.of(test{{domainTitleCase}}Response));

        // When & Then
        mockMvc.perform(get("/{{domain}}s/{id}", {{domain}}Id))
                .andExpect(status().isOk())
                .andExpect(content().contentType(MediaType.APPLICATION_JSON))
                .andExpect(jsonPath("$.id").value({{domain}}Id))
                .andExpect(jsonPath("$.name").value("Test {{domainTitleCase}}"))
                .andExpect(jsonPath("$.description").value("Test description"));

        verify({{domain}}Service).get{{domainTitleCase}}ById({{domain}}Id);
    }

    @Test
    @DisplayName("Should return 404 when {{domain}} not found by ID")
    void shouldReturn404When{{domainTitleCase}}NotFoundById() throws Exception {
        // Given
        String {{domain}}Id = "non-existent-id";
        when({{domain}}Service.get{{domainTitleCase}}ById({{domain}}Id)).thenReturn(Optional.empty());

        // When & Then
        mockMvc.perform(get("/{{domain}}s/{id}", {{domain}}Id))
                .andExpect(status().isNotFound());

        verify({{domain}}Service).get{{domainTitleCase}}ById({{domain}}Id);
    }

    @Test
    @DisplayName("Should create {{domain}} successfully")
    void shouldCreate{{domainTitleCase}}Successfully() throws Exception {
        // Given
        when({{domain}}Service.create{{domainTitleCase}}(any({{domainTitleCase}}Request.class)))
                .thenReturn(test{{domainTitleCase}}Response);

        // When & Then
        mockMvc.perform(post("/{{domain}}s")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(test{{domainTitleCase}}Request)))
                .andExpect(status().isCreated())
                .andExpect(content().contentType(MediaType.APPLICATION_JSON))
                .andExpect(jsonPath("$.id").value("test-id-123"))
                .andExpect(jsonPath("$.name").value("Test {{domainTitleCase}}"))
                .andExpect(jsonPath("$.description").value("Test description"));

        verify({{domain}}Service).create{{domainTitleCase}}(any({{domainTitleCase}}Request.class));
    }

    @Test
    @DisplayName("Should return 400 when creating {{domain}} with invalid data")
    void shouldReturn400WhenCreating{{domainTitleCase}}WithInvalidData() throws Exception {
        // Given
        {{domainTitleCase}}Request invalidRequest = new {{domainTitleCase}}Request();
        invalidRequest.setName(""); // Invalid: empty name
        invalidRequest.setDescription("Test description");

        // When & Then
        mockMvc.perform(post("/{{domain}}s")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(invalidRequest)))
                .andExpect(status().isBadRequest());

        verify({{domain}}Service, never()).create{{domainTitleCase}}(any({{domainTitleCase}}Request.class));
    }

    @Test
    @DisplayName("Should return 409 when creating {{domain}} with existing name")
    void shouldReturn409WhenCreating{{domainTitleCase}}WithExistingName() throws Exception {
        // Given
        when({{domain}}Service.create{{domainTitleCase}}(any({{domainTitleCase}}Request.class)))
                .thenThrow(new IllegalArgumentException("{{domainTitleCase}} with name 'Test {{domainTitleCase}}' already exists"));

        // When & Then
        mockMvc.perform(post("/{{domain}}s")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(test{{domainTitleCase}}Request)))
                .andExpect(status().isConflict());

        verify({{domain}}Service).create{{domainTitleCase}}(any({{domainTitleCase}}Request.class));
    }

    @Test
    @DisplayName("Should update {{domain}} successfully")
    void shouldUpdate{{domainTitleCase}}Successfully() throws Exception {
        // Given
        String {{domain}}Id = "test-id-123";
        {{domainTitleCase}}Request updateRequest = new {{domainTitleCase}}Request();
        updateRequest.setName("Updated {{domainTitleCase}}");
        updateRequest.setDescription("Updated description");

        {{domainTitleCase}}Response updatedResponse = new {{domainTitleCase}}Response();
        updatedResponse.setId({{domain}}Id);
        updatedResponse.setName(updateRequest.getName());
        updatedResponse.setDescription(updateRequest.getDescription());
        updatedResponse.setCreatedAt(test{{domainTitleCase}}Response.getCreatedAt());
        updatedResponse.setUpdatedAt(LocalDateTime.now());

        when({{domain}}Service.update{{domainTitleCase}}(eq({{domain}}Id), any({{domainTitleCase}}Request.class)))
                .thenReturn(Optional.of(updatedResponse));

        // When & Then
        mockMvc.perform(put("/{{domain}}s/{id}", {{domain}}Id)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(updateRequest)))
                .andExpect(status().isOk())
                .andExpect(content().contentType(MediaType.APPLICATION_JSON))
                .andExpect(jsonPath("$.id").value({{domain}}Id))
                .andExpect(jsonPath("$.name").value("Updated {{domainTitleCase}}"))
                .andExpect(jsonPath("$.description").value("Updated description"));

        verify({{domain}}Service).update{{domainTitleCase}}(eq({{domain}}Id), any({{domainTitleCase}}Request.class));
    }

    @Test
    @DisplayName("Should return 404 when updating non-existent {{domain}}")
    void shouldReturn404WhenUpdatingNonExistent{{domainTitleCase}}() throws Exception {
        // Given
        String {{domain}}Id = "non-existent-id";
        when({{domain}}Service.update{{domainTitleCase}}(eq({{domain}}Id), any({{domainTitleCase}}Request.class)))
                .thenReturn(Optional.empty());

        // When & Then
        mockMvc.perform(put("/{{domain}}s/{id}", {{domain}}Id)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(test{{domainTitleCase}}Request)))
                .andExpect(status().isNotFound());

        verify({{domain}}Service).update{{domainTitleCase}}(eq({{domain}}Id), any({{domainTitleCase}}Request.class));
    }

    @Test
    @DisplayName("Should delete {{domain}} successfully")
    void shouldDelete{{domainTitleCase}}Successfully() throws Exception {
        // Given
        String {{domain}}Id = "test-id-123";
        when({{domain}}Service.delete{{domainTitleCase}}({{domain}}Id)).thenReturn(true);

        // When & Then
        mockMvc.perform(delete("/{{domain}}s/{id}", {{domain}}Id))
                .andExpect(status().isNoContent());

        verify({{domain}}Service).delete{{domainTitleCase}}({{domain}}Id);
    }

    @Test
    @DisplayName("Should return 404 when deleting non-existent {{domain}}")
    void shouldReturn404WhenDeletingNonExistent{{domainTitleCase}}() throws Exception {
        // Given
        String {{domain}}Id = "non-existent-id";
        when({{domain}}Service.delete{{domainTitleCase}}({{domain}}Id)).thenReturn(false);

        // When & Then
        mockMvc.perform(delete("/{{domain}}s/{id}", {{domain}}Id))
                .andExpect(status().isNotFound());

        verify({{domain}}Service).delete{{domainTitleCase}}({{domain}}Id);
    }

    @Test
    @DisplayName("Should search {{domain}}s successfully")
    void shouldSearch{{domainTitleCase}}sSuccessfully() throws Exception {
        // Given
        String searchText = "test";
        when({{domain}}Service.search{{domainTitleCase}}s(searchText)).thenReturn(test{{domainTitleCase}}List);

        // When & Then
        mockMvc.perform(get("/{{domain}}s/search")
                        .param("searchText", searchText))
                .andExpect(status().isOk())
                .andExpect(content().contentType(MediaType.APPLICATION_JSON))
                .andExpect(jsonPath("$").isArray())
                .andExpect(jsonPath("$.length()").value(2));

        verify({{domain}}Service).search{{domainTitleCase}}s(searchText);
    }

    @Test
    @DisplayName("Should get {{domain}}s created after date successfully")
    void shouldGet{{domainTitleCase}}sCreatedAfterDateSuccessfully() throws Exception {
        // Given
        String dateString = "2023-01-01T00:00:00";
        when({{domain}}Service.get{{domainTitleCase}}sCreatedAfter(any(LocalDateTime.class)))
                .thenReturn(test{{domainTitleCase}}List);

        // When & Then
        mockMvc.perform(get("/{{domain}}s/created-after")
                        .param("date", dateString))
                .andExpect(status().isOk())
                .andExpect(content().contentType(MediaType.APPLICATION_JSON))
                .andExpect(jsonPath("$").isArray())
                .andExpect(jsonPath("$.length()").value(2));

        verify({{domain}}Service).get{{domainTitleCase}}sCreatedAfter(any(LocalDateTime.class));
    }

    @Test
    @DisplayName("Should return 400 for invalid date format")
    void shouldReturn400ForInvalidDateFormat() throws Exception {
        // When & Then
        mockMvc.perform(get("/{{domain}}s/created-after")
                        .param("date", "invalid-date"))
                .andExpect(status().isBadRequest());

        verify({{domain}}Service, never()).get{{domainTitleCase}}sCreatedAfter(any(LocalDateTime.class));
    }

    @Test
    @DisplayName("Should check if {{domain}} exists by name")
    void shouldCheckIf{{domainTitleCase}}ExistsByName() throws Exception {
        // Given
        String {{domain}}Name = "Test {{domainTitleCase}}";
        when({{domain}}Service.exists{{domainTitleCase}}ByName({{domain}}Name)).thenReturn(true);

        // When & Then
        mockMvc.perform(get("/{{domain}}s/exists")
                        .param("name", {{domain}}Name))
                .andExpect(status().isOk())
                .andExpect(content().contentType(MediaType.APPLICATION_JSON))
                .andExpect(jsonPath("$").value(true));

        verify({{domain}}Service).exists{{domainTitleCase}}ByName({{domain}}Name);
    }

    @Test
    @DisplayName("Should handle validation errors gracefully")
    void shouldHandleValidationErrorsGracefully() throws Exception {
        // Given
        {{domainTitleCase}}Request invalidRequest = new {{domainTitleCase}}Request();
        invalidRequest.setName("A"); // Too short
        invalidRequest.setDescription("x".repeat(501)); // Too long

        // When & Then
        mockMvc.perform(post("/{{domain}}s")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(invalidRequest)))
                .andExpect(status().isBadRequest());

        verify({{domain}}Service, never()).create{{domainTitleCase}}(any({{domainTitleCase}}Request.class));
    }

    @Test
    @DisplayName("Should handle missing request body")
    void shouldHandleMissingRequestBody() throws Exception {
        // When & Then
        mockMvc.perform(post("/{{domain}}s")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(""))
                .andExpect(status().isBadRequest());

        verify({{domain}}Service, never()).create{{domainTitleCase}}(any({{domainTitleCase}}Request.class));
    }

    @Test
    @DisplayName("Should handle invalid JSON format")
    void shouldHandleInvalidJsonFormat() throws Exception {
        // When & Then
        mockMvc.perform(post("/{{domain}}s")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{invalid json}"))
                .andExpect(status().isBadRequest());

        verify({{domain}}Service, never()).create{{domainTitleCase}}(any({{domainTitleCase}}Request.class));
    }
}