package {{packageName}}.enterprise.patterns;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Component;

import java.time.Instant;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;

/**
 * 🤖 ENTERPRISE INFRASTRUCTURE - DO NOT MODIFY
 *
 * Enterprise Audit Logger providing:
 * - Comprehensive audit trail
 * - Security event logging
 * - Data change tracking
 * - User activity monitoring
 * - Compliance reporting
 * - Structured audit events
 *
 * Automatically used by AbstractEnterpriseService
 * Generated by Enterprise CLI - Infrastructure layer
 */
@Component
public class EnterpriseAuditLogger {

    private static final Logger auditLogger = LoggerFactory.getLogger("AUDIT");
    private static final Logger logger = LoggerFactory.getLogger(EnterpriseAuditLogger.class);

    private final ObjectMapper objectMapper;

    @Autowired
    public EnterpriseAuditLogger(ObjectMapper objectMapper) {
        this.objectMapper = objectMapper;
    }

    // ================================
    // 🤖 OPERATION AUDIT METHODS
    // ================================

    /**
     * 🤖 Log operation start
     */
    public void logOperationStart(String operation, String entityType, Object entityId, Object requestData) {
        AuditEvent event = AuditEvent.builder()
                .eventType("OPERATION_START")
                .operation(operation)
                .entityType(entityType)
                .entityId(safeToString(entityId))
                .status("STARTED")
                .requestData(requestData)
                .build();

        logAuditEvent(event);
    }

    /**
     * 🤖 Log successful operation
     */
    public void logOperationSuccess(String operation, String entityType, Object entityId, Object responseData) {
        AuditEvent event = AuditEvent.builder()
                .eventType("OPERATION_SUCCESS")
                .operation(operation)
                .entityType(entityType)
                .entityId(safeToString(entityId))
                .status("SUCCESS")
                .responseData(responseData)
                .build();

        logAuditEvent(event);
    }

    /**
     * 🤖 Log validation error
     */
    public void logValidationError(String operation, String entityType, Object entityId, Exception error) {
        AuditEvent event = AuditEvent.builder()
                .eventType("VALIDATION_ERROR")
                .operation(operation)
                .entityType(entityType)
                .entityId(safeToString(entityId))
                .status("VALIDATION_FAILED")
                .errorMessage(error.getMessage())
                .errorType("BUSINESS_VALIDATION")
                .build();

        logAuditEvent(event);
    }

    /**
     * 🤖 Log system error
     */
    public void logSystemError(String operation, String entityType, Object entityId, Exception error) {
        AuditEvent event = AuditEvent.builder()
                .eventType("SYSTEM_ERROR")
                .operation(operation)
                .entityType(entityType)
                .entityId(safeToString(entityId))
                .status("SYSTEM_ERROR")
                .errorMessage(error.getMessage())
                .errorType(error.getClass().getSimpleName())
                .stackTrace(getStackTrace(error))
                .build();

        logAuditEvent(event);
    }

    /**
     * 🤖 Log security event
     */
    public void logSecurityEvent(String eventType, String description, String severity) {
        AuditEvent event = AuditEvent.builder()
                .eventType("SECURITY_EVENT")
                .operation(eventType)
                .status(severity)
                .description(description)
                .securityRelevant(true)
                .build();

        logAuditEvent(event);
    }

    /**
     * 🤖 Log data access event
     */
    public void logDataAccess(String entityType, Object entityId, String accessType) {
        AuditEvent event = AuditEvent.builder()
                .eventType("DATA_ACCESS")
                .operation(accessType)
                .entityType(entityType)
                .entityId(safeToString(entityId))
                .status("ACCESSED")
                .build();

        logAuditEvent(event);
    }

    /**
     * 🤖 Log business rule violation
     */
    public void logBusinessRuleViolation(String entityType, Object entityId, String ruleType, String ruleDescription) {
        AuditEvent event = AuditEvent.builder()
                .eventType("BUSINESS_RULE_VIOLATION")
                .operation("VALIDATION")
                .entityType(entityType)
                .entityId(safeToString(entityId))
                .status("RULE_VIOLATED")
                .ruleType(ruleType)
                .description(ruleDescription)
                .build();

        logAuditEvent(event);
    }

    /**
     * 🤖 Log configuration change
     */
    public void logConfigurationChange(String configType, String configKey, Object oldValue, Object newValue) {
        AuditEvent event = AuditEvent.builder()
                .eventType("CONFIGURATION_CHANGE")
                .operation("CONFIG_UPDATE")
                .entityType("CONFIGURATION")
                .entityId(configKey)
                .status("CHANGED")
                .previousData(oldValue)
                .responseData(newValue)
                .configType(configType)
                .build();

        logAuditEvent(event);
    }

    // ================================
    // 🤖 INTERNAL AUDIT METHODS
    // ================================

    private void logAuditEvent(AuditEvent event) {
        try {
            String auditJson = objectMapper.writeValueAsString(event);

            // Log to dedicated audit logger
            auditLogger.info("AUDIT_EVENT: {}", auditJson);

            // Also log significant events to main logger
            if (event.isSecurityRelevant() || "SYSTEM_ERROR".equals(event.getEventType())) {
                logger.warn("🔒 Security/Critical Audit Event: {} - {} - {}",
                           event.getEventType(), event.getOperation(), event.getStatus());
            }

        } catch (JsonProcessingException e) {
            logger.error("💥 Failed to serialize audit event: {}", event.getEventType(), e);
            // Fallback to simple logging
            auditLogger.error("AUDIT_SERIALIZATION_ERROR: event={}, error={}",
                             event.getEventType(), e.getMessage());
        }
    }

    private String safeToString(Object obj) {
        return obj != null ? obj.toString() : null;
    }

    private String getStackTrace(Exception error) {
        if (error == null) return null;

        java.io.StringWriter sw = new java.io.StringWriter();
        java.io.PrintWriter pw = new java.io.PrintWriter(sw);
        error.printStackTrace(pw);
        return sw.toString();
    }

    private String getCurrentUserId() {
        try {
            Authentication auth = SecurityContextHolder.getContext().getAuthentication();
            if (auth != null && auth.isAuthenticated()) {
                return auth.getName();
            }
        } catch (Exception e) {
            logger.debug("Could not retrieve current user: {}", e.getMessage());
        }
        return "SYSTEM";
    }

    private String getCurrentUserRole() {
        try {
            Authentication auth = SecurityContextHolder.getContext().getAuthentication();
            if (auth != null && auth.getAuthorities() != null) {
                return auth.getAuthorities().stream()
                          .map(Object::toString)
                          .reduce((a, b) -> a + "," + b)
                          .orElse("UNKNOWN");
            }
        } catch (Exception e) {
            logger.debug("Could not retrieve current user roles: {}", e.getMessage());
        }
        return "UNKNOWN";
    }

    private String getClientIpAddress() {
        // In a real implementation, this would extract IP from HTTP request
        // For now, return placeholder
        return "UNKNOWN";
    }

    private String getSessionId() {
        // In a real implementation, this would extract session ID
        // For now, return placeholder
        return "UNKNOWN";
    }

    // ================================
    // 🤖 AUDIT EVENT CLASS
    // ================================

    public static class AuditEvent {
        private String auditId;
        private Instant timestamp;
        private String eventType;
        private String operation;
        private String entityType;
        private String entityId;
        private String status;
        private String userId;
        private String userRole;
        private String sessionId;
        private String clientIpAddress;
        private String description;
        private Object requestData;
        private Object responseData;
        private Object previousData;
        private String errorMessage;
        private String errorType;
        private String stackTrace;
        private String ruleType;
        private String configType;
        private boolean securityRelevant;
        private Map<String, Object> additionalData;

        private AuditEvent(Builder builder) {
            this.auditId = builder.auditId;
            this.timestamp = builder.timestamp;
            this.eventType = builder.eventType;
            this.operation = builder.operation;
            this.entityType = builder.entityType;
            this.entityId = builder.entityId;
            this.status = builder.status;
            this.userId = builder.userId;
            this.userRole = builder.userRole;
            this.sessionId = builder.sessionId;
            this.clientIpAddress = builder.clientIpAddress;
            this.description = builder.description;
            this.requestData = builder.requestData;
            this.responseData = builder.responseData;
            this.previousData = builder.previousData;
            this.errorMessage = builder.errorMessage;
            this.errorType = builder.errorType;
            this.stackTrace = builder.stackTrace;
            this.ruleType = builder.ruleType;
            this.configType = builder.configType;
            this.securityRelevant = builder.securityRelevant;
            this.additionalData = builder.additionalData;
        }

        public static Builder builder() {
            return new Builder();
        }

        // Getters
        public String getAuditId() { return auditId; }
        public Instant getTimestamp() { return timestamp; }
        public String getEventType() { return eventType; }
        public String getOperation() { return operation; }
        public String getEntityType() { return entityType; }
        public String getEntityId() { return entityId; }
        public String getStatus() { return status; }
        public String getUserId() { return userId; }
        public String getUserRole() { return userRole; }
        public String getSessionId() { return sessionId; }
        public String getClientIpAddress() { return clientIpAddress; }
        public String getDescription() { return description; }
        public Object getRequestData() { return requestData; }
        public Object getResponseData() { return responseData; }
        public Object getPreviousData() { return previousData; }
        public String getErrorMessage() { return errorMessage; }
        public String getErrorType() { return errorType; }
        public String getStackTrace() { return stackTrace; }
        public String getRuleType() { return ruleType; }
        public String getConfigType() { return configType; }
        public boolean isSecurityRelevant() { return securityRelevant; }
        public Map<String, Object> getAdditionalData() { return additionalData; }

        public static class Builder {
            private String auditId = java.util.UUID.randomUUID().toString();
            private Instant timestamp = Instant.now();
            private String eventType;
            private String operation;
            private String entityType;
            private String entityId;
            private String status;
            private String userId;
            private String userRole;
            private String sessionId;
            private String clientIpAddress;
            private String description;
            private Object requestData;
            private Object responseData;
            private Object previousData;
            private String errorMessage;
            private String errorType;
            private String stackTrace;
            private String ruleType;
            private String configType;
            private boolean securityRelevant = false;
            private Map<String, Object> additionalData = new HashMap<>();

            public Builder eventType(String eventType) {
                this.eventType = eventType;
                return this;
            }

            public Builder operation(String operation) {
                this.operation = operation;
                return this;
            }

            public Builder entityType(String entityType) {
                this.entityType = entityType;
                return this;
            }

            public Builder entityId(String entityId) {
                this.entityId = entityId;
                return this;
            }

            public Builder status(String status) {
                this.status = status;
                return this;
            }

            public Builder description(String description) {
                this.description = description;
                return this;
            }

            public Builder requestData(Object requestData) {
                this.requestData = requestData;
                return this;
            }

            public Builder responseData(Object responseData) {
                this.responseData = responseData;
                return this;
            }

            public Builder previousData(Object previousData) {
                this.previousData = previousData;
                return this;
            }

            public Builder errorMessage(String errorMessage) {
                this.errorMessage = errorMessage;
                return this;
            }

            public Builder errorType(String errorType) {
                this.errorType = errorType;
                return this;
            }

            public Builder stackTrace(String stackTrace) {
                this.stackTrace = stackTrace;
                return this;
            }

            public Builder ruleType(String ruleType) {
                this.ruleType = ruleType;
                return this;
            }

            public Builder configType(String configType) {
                this.configType = configType;
                return this;
            }

            public Builder securityRelevant(boolean securityRelevant) {
                this.securityRelevant = securityRelevant;
                return this;
            }

            public Builder additionalData(Map<String, Object> additionalData) {
                this.additionalData = additionalData;
                return this;
            }

            public AuditEvent build() {
                // Auto-populate user context if not set
                if (this.userId == null) {
                    this.userId = getCurrentUserId();
                }
                if (this.userRole == null) {
                    this.userRole = getCurrentUserRole();
                }
                if (this.sessionId == null) {
                    this.sessionId = getSessionId();
                }
                if (this.clientIpAddress == null) {
                    this.clientIpAddress = getClientIpAddress();
                }

                return new AuditEvent(this);
            }

            private String getCurrentUserId() {
                try {
                    Authentication auth = SecurityContextHolder.getContext().getAuthentication();
                    if (auth != null && auth.isAuthenticated()) {
                        return auth.getName();
                    }
                } catch (Exception e) {
                    // Ignore
                }
                return "SYSTEM";
            }

            private String getCurrentUserRole() {
                try {
                    Authentication auth = SecurityContextHolder.getContext().getAuthentication();
                    if (auth != null && auth.getAuthorities() != null) {
                        return auth.getAuthorities().stream()
                                  .map(Object::toString)
                                  .reduce((a, b) -> a + "," + b)
                                  .orElse("UNKNOWN");
                    }
                } catch (Exception e) {
                    // Ignore
                }
                return "UNKNOWN";
            }

            private String getSessionId() {
                return "SESSION_" + System.currentTimeMillis();
            }

            private String getClientIpAddress() {
                return "UNKNOWN";
            }
        }
    }
}