package {{packageName}}.enterprise.patterns;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.stereotype.Component;

import java.time.Instant;
import java.util.Map;
import java.util.concurrent.CompletableFuture;

/**
 * 🤖 ENTERPRISE INFRASTRUCTURE - DO NOT MODIFY
 *
 * Enterprise Event Publisher providing:
 * - Standardized domain event publishing
 * - Asynchronous event processing
 * - Event correlation and tracing
 * - Error handling and retry logic
 * - Event audit and metrics
 *
 * Automatically used by AbstractEnterpriseService
 * Generated by Enterprise CLI - Infrastructure layer
 */
@Component
public class EnterpriseEventPublisher {

    private static final Logger logger = LoggerFactory.getLogger(EnterpriseEventPublisher.class);

    private final ApplicationEventPublisher applicationEventPublisher;

    @Autowired
    public EnterpriseEventPublisher(ApplicationEventPublisher applicationEventPublisher) {
        this.applicationEventPublisher = applicationEventPublisher;
    }

    /**
     * 🤖 Publish entity created event
     */
    public <T> void publishCreated(T entity) {
        publishEvent(EnterpriseEvent.created(entity));
    }

    /**
     * 🤖 Publish entity updated event
     */
    public <T> void publishUpdated(T previousState, T currentState) {
        publishEvent(EnterpriseEvent.updated(previousState, currentState));
    }

    /**
     * 🤖 Publish entity deleted event
     */
    public <T> void publishDeleted(T entity) {
        publishEvent(EnterpriseEvent.deleted(entity));
    }

    /**
     * 🤖 Publish custom business event
     */
    public void publishBusinessEvent(String eventType, Object payload, Map<String, Object> metadata) {
        publishEvent(EnterpriseEvent.business(eventType, payload, metadata));
    }

    /**
     * 🤖 Publish event synchronously
     */
    public void publishEvent(EnterpriseEvent event) {
        try {
            logger.debug("📤 Publishing enterprise event: {} for entity: {}",
                        event.getEventType(), event.getEntityType());

            applicationEventPublisher.publishEvent(event);

            logger.info("✅ Successfully published event: {} with ID: {}",
                       event.getEventType(), event.getEventId());

        } catch (Exception e) {
            logger.error("💥 Failed to publish enterprise event: {} for entity: {}",
                        event.getEventType(), event.getEntityType(), e);
            throw new EventPublishingException(
                "Failed to publish event: " + event.getEventType(), e);
        }
    }

    /**
     * 🤖 Publish event asynchronously
     */
    public CompletableFuture<Void> publishEventAsync(EnterpriseEvent event) {
        return CompletableFuture.runAsync(() -> publishEvent(event))
                .exceptionally(throwable -> {
                    logger.error("💥 Async event publishing failed: {} for entity: {}",
                                event.getEventType(), event.getEntityType(), throwable);
                    return null;
                });
    }

    /**
     * 🤖 Enterprise Event wrapper
     */
    public static class EnterpriseEvent {
        private final String eventId;
        private final String eventType;
        private final String entityType;
        private final Object entityId;
        private final Object payload;
        private final Object previousState;
        private final Instant timestamp;
        private final String correlationId;
        private final Map<String, Object> metadata;

        private EnterpriseEvent(Builder builder) {
            this.eventId = builder.eventId;
            this.eventType = builder.eventType;
            this.entityType = builder.entityType;
            this.entityId = builder.entityId;
            this.payload = builder.payload;
            this.previousState = builder.previousState;
            this.timestamp = builder.timestamp;
            this.correlationId = builder.correlationId;
            this.metadata = builder.metadata;
        }

        public static <T> EnterpriseEvent created(T entity) {
            return new Builder()
                    .eventType("ENTITY_CREATED")
                    .entityType(entity.getClass().getSimpleName())
                    .payload(entity)
                    .build();
        }

        public static <T> EnterpriseEvent updated(T previousState, T currentState) {
            return new Builder()
                    .eventType("ENTITY_UPDATED")
                    .entityType(currentState.getClass().getSimpleName())
                    .payload(currentState)
                    .previousState(previousState)
                    .build();
        }

        public static <T> EnterpriseEvent deleted(T entity) {
            return new Builder()
                    .eventType("ENTITY_DELETED")
                    .entityType(entity.getClass().getSimpleName())
                    .payload(entity)
                    .build();
        }

        public static EnterpriseEvent business(String eventType, Object payload, Map<String, Object> metadata) {
            return new Builder()
                    .eventType(eventType)
                    .entityType("BUSINESS_EVENT")
                    .payload(payload)
                    .metadata(metadata)
                    .build();
        }

        // Getters
        public String getEventId() { return eventId; }
        public String getEventType() { return eventType; }
        public String getEntityType() { return entityType; }
        public Object getEntityId() { return entityId; }
        public Object getPayload() { return payload; }
        public Object getPreviousState() { return previousState; }
        public Instant getTimestamp() { return timestamp; }
        public String getCorrelationId() { return correlationId; }
        public Map<String, Object> getMetadata() { return metadata; }

        @Override
        public String toString() {
            return "EnterpriseEvent{" +
                    "eventId='" + eventId + '\'' +
                    ", eventType='" + eventType + '\'' +
                    ", entityType='" + entityType + '\'' +
                    ", timestamp=" + timestamp +
                    '}';
        }

        /**
         * Builder for Enterprise Event
         */
        public static class Builder {
            private String eventId = java.util.UUID.randomUUID().toString();
            private String eventType;
            private String entityType;
            private Object entityId;
            private Object payload;
            private Object previousState;
            private Instant timestamp = Instant.now();
            private String correlationId = generateCorrelationId();
            private Map<String, Object> metadata = new java.util.HashMap<>();

            public Builder eventType(String eventType) {
                this.eventType = eventType;
                return this;
            }

            public Builder entityType(String entityType) {
                this.entityType = entityType;
                return this;
            }

            public Builder entityId(Object entityId) {
                this.entityId = entityId;
                return this;
            }

            public Builder payload(Object payload) {
                this.payload = payload;
                return this;
            }

            public Builder previousState(Object previousState) {
                this.previousState = previousState;
                return this;
            }

            public Builder correlationId(String correlationId) {
                this.correlationId = correlationId;
                return this;
            }

            public Builder metadata(Map<String, Object> metadata) {
                this.metadata = metadata;
                return this;
            }

            public EnterpriseEvent build() {
                return new EnterpriseEvent(this);
            }

            private static String generateCorrelationId() {
                return "corr-" + System.currentTimeMillis() + "-" +
                       java.util.UUID.randomUUID().toString().substring(0, 8);
            }
        }
    }

    /**
     * 🤖 Exception for event publishing failures
     */
    public static class EventPublishingException extends RuntimeException {
        public EventPublishingException(String message, Throwable cause) {
            super(message, cause);
        }
    }
}