package {{packageName}}.scheduled;

import {{packageName}}.dto.{{domainTitleCase}}Response;
import {{packageName}}.monitoring.{{domainTitleCase}}MetricsService;
import {{packageName}}.service.{{domainTitleCase}}Service;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import java.time.LocalDateTime;
import java.util.concurrent.TimeUnit;

/**
 * Scheduled Tasks for {{domainTitleCase}} Operations
 *
 * Handles periodic business operations and maintenance tasks.
 * Tasks can be enabled/disabled via configuration properties.
 * Generated by Enterprise CLI - customize according to your business requirements.
 */
@Component
@ConditionalOnProperty(value = "app.scheduling.enabled", havingValue = "true", matchIfMissing = true)
public class {{domainTitleCase}}ScheduledTasks {

    private static final Logger logger = LoggerFactory.getLogger({{domainTitleCase}}ScheduledTasks.class);

    private final {{domainTitleCase}}Service {{domain}}Service;
    private final {{domainTitleCase}}MetricsService metricsService;

    @Autowired
    public {{domainTitleCase}}ScheduledTasks({{domainTitleCase}}Service {{domain}}Service,
                                           {{domainTitleCase}}MetricsService metricsService) {
        this.{{domain}}Service = {{domain}}Service;
        this.metricsService = metricsService;
    }

    /**
     * Daily statistics collection
     * Runs every day at 2:00 AM
     */
    @Scheduled(cron = "0 0 2 * * ?")
    @ConditionalOnProperty(value = "app.scheduling.daily-stats.enabled", havingValue = "true", matchIfMissing = true)
    public void collectDailyStatistics() {
        logger.info("Starting daily statistics collection");

        try {
            LocalDateTime yesterday = LocalDateTime.now().minusDays(1);
            long count = {{domain}}Service.count{{domainTitleCase}}sCreatedAfter(yesterday);

            metricsService.recordBusinessMetric("daily_{{domain}}_count", count);

            logger.info("Daily statistics collected successfully. {{domainTitleCase}}s created yesterday: {}", count);

        } catch (Exception e) {
            logger.error("Error collecting daily statistics", e);
            metricsService.recordError();
        }
    }

    /**
     * Hourly metrics collection
     * Runs every hour at minute 5
     */
    @Scheduled(cron = "0 5 * * * ?")
    @ConditionalOnProperty(value = "app.scheduling.hourly-metrics.enabled", havingValue = "true", matchIfMissing = true)
    public void collectHourlyMetrics() {
        logger.debug("Starting hourly metrics collection");

        try {
            // Collect current counts
            Page<{{domainTitleCase}}Response> totalPage = {{domain}}Service.findAll(Pageable.unpaged());
            long totalCount = totalPage.getTotalElements();
            long activeCount = {{domain}}Service.getActive{{domainTitleCase}}s().size();

            metricsService.recordBusinessMetric("total_{{domain}}_count", totalCount);
            metricsService.recordBusinessMetric("active_{{domain}}_count", activeCount);

            logger.debug("Hourly metrics collected. Total: {}, Active: {}", totalCount, activeCount);

        } catch (Exception e) {
            logger.error("Error collecting hourly metrics", e);
            metricsService.recordError();
        }
    }

    /**
     * Weekly maintenance task
     * Runs every Sunday at 3:00 AM
     */
    @Scheduled(cron = "0 0 3 ? * SUN")
    @ConditionalOnProperty(value = "app.scheduling.weekly-maintenance.enabled", havingValue = "true", matchIfMissing = true)
    public void performWeeklyMaintenance() {
        logger.info("Starting weekly maintenance task");

        try {
            // Add your weekly maintenance logic here
            // Examples:
            // - Clean up old data
            // - Generate weekly reports
            // - Optimize database indexes
            // - Validate data integrity

            performDataValidation();
            generateWeeklyReport();

            logger.info("Weekly maintenance completed successfully");

        } catch (Exception e) {
            logger.error("Error during weekly maintenance", e);
            metricsService.recordError();
        }
    }

    /**
     * Monthly archival task
     * Runs on the 1st day of every month at 4:00 AM
     */
    @Scheduled(cron = "0 0 4 1 * ?")
    @ConditionalOnProperty(value = "app.scheduling.monthly-archival.enabled", havingValue = "true", matchIfMissing = true)
    public void performMonthlyArchival() {
        logger.info("Starting monthly archival task");

        try {
            LocalDateTime cutoffDate = LocalDateTime.now().minusMonths(6);

            // Add your archival logic here
            // Examples:
            // - Archive old {{domain}}s
            // - Compress old logs
            // - Clean up temporary files
            // - Generate monthly reports

            logger.info("Monthly archival completed successfully for data older than {}", cutoffDate);

        } catch (Exception e) {
            logger.error("Error during monthly archival", e);
            metricsService.recordError();
        }
    }

    /**
     * Fixed rate task - runs every 30 minutes
     * Good for health checks and monitoring
     */
    @Scheduled(fixedRate = 30, timeUnit = TimeUnit.MINUTES)
    @ConditionalOnProperty(value = "app.scheduling.health-check.enabled", havingValue = "true", matchIfMissing = true)
    public void performHealthCheck() {
        logger.debug("Performing {{domain}} service health check");

        try {
            // Add your health check logic here
            // Examples:
            // - Check database connectivity
            // - Validate external service connections
            // - Monitor resource usage
            // - Check application state

            boolean isHealthy = checkServiceHealth();

            if (isHealthy) {
                metricsService.recordBusinessMetric("health_check_success", 1);
            } else {
                metricsService.recordBusinessMetric("health_check_failure", 1);
                logger.warn("Health check detected issues in {{domain}} service");
            }

        } catch (Exception e) {
            logger.error("Error during health check", e);
            metricsService.recordBusinessMetric("health_check_error", 1);
        }
    }

    /**
     * Initial delay task - runs 2 minutes after startup, then every hour
     * Good for initialization tasks
     */
    @Scheduled(initialDelay = 2, fixedRate = 60, timeUnit = TimeUnit.MINUTES)
    @ConditionalOnProperty(value = "app.scheduling.initialization.enabled", havingValue = "true", matchIfMissing = true)
    public void performInitializationTasks() {
        logger.debug("Performing initialization and periodic tasks");

        try {
            // Add your initialization logic here
            // Examples:
            // - Warm up caches
            // - Preload reference data
            // - Initialize connections
            // - Verify system state

            warmupCaches();
            validateSystemState();

            metricsService.recordBusinessMetric("initialization_task_success", 1);

        } catch (Exception e) {
            logger.error("Error during initialization tasks", e);
            metricsService.recordBusinessMetric("initialization_task_error", 1);
        }
    }

    // Helper methods for business logic

    private void performDataValidation() {
        logger.debug("Performing data validation");
        // Add your data validation logic here
    }

    private void generateWeeklyReport() {
        logger.debug("Generating weekly report");
        // Add your weekly report generation logic here
    }

    private boolean checkServiceHealth() {
        // Add your health check logic here
        // Return true if service is healthy, false otherwise
        return true;
    }

    private void warmupCaches() {
        logger.debug("Warming up caches");
        // Add cache warmup logic here
        // Example: preload frequently accessed {{domain}}s
    }

    private void validateSystemState() {
        logger.debug("Validating system state");
        // Add system state validation logic here
    }

    /**
     * Custom scheduled task with configurable cron expression
     * Cron expression can be configured via property: app.scheduling.custom.cron
     */
    @Scheduled(cron = "${app.scheduling.custom.cron:0 0 1 * * ?}") // Default: daily at 1 AM
    @ConditionalOnProperty(value = "app.scheduling.custom.enabled", havingValue = "true", matchIfMissing = false)
    public void performCustomTask() {
        logger.info("Performing custom scheduled task");

        try {
            // Add your custom business logic here
            // This task can be configured via properties

            logger.info("Custom scheduled task completed successfully");

        } catch (Exception e) {
            logger.error("Error during custom scheduled task", e);
            metricsService.recordError();
        }
    }
}