package {{packageName}}.validation;

import {{packageName}}.dto.{{domainTitleCase}}Request;
import {{packageName}}.entity.{{domainTitleCase}};
import {{packageName}}.repository.{{domainTitleCase}}Repository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import jakarta.validation.ConstraintValidator;
import jakarta.validation.ConstraintValidatorContext;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Pattern;

/**
 * Custom Validator for {{domainTitleCase}} Operations
 *
 * Provides complex business validation beyond standard Bean Validation.
 * Implements custom validation rules and cross-field validation.
 * Generated by Enterprise CLI - customize according to your business rules.
 */
@Component
public class {{domainTitleCase}}Validator {

    private static final Logger logger = LoggerFactory.getLogger({{domainTitleCase}}Validator.class);

    private final {{domainTitleCase}}Repository {{domain}}Repository;

    // Common validation patterns
    private static final Pattern ALPHANUMERIC_PATTERN = Pattern.compile("^[a-zA-Z0-9]+$");
    private static final Pattern EMAIL_PATTERN = Pattern.compile("^[A-Za-z0-9+_.-]+@(.+)$");
    private static final Pattern PHONE_PATTERN = Pattern.compile("^\\+?[1-9]\\d{1,14}$");
    private static final Pattern URL_PATTERN = Pattern.compile("^(https?|ftp)://[^\\s/$.?#].[^\\s]*$");

    @Autowired
    public {{domainTitleCase}}Validator({{domainTitleCase}}Repository {{domain}}Repository) {
        this.{{domain}}Repository = {{domain}}Repository;
    }

    /**
     * Validate {{domainTitleCase}} creation request
     */
    public ValidationResult validateCreateRequest({{domainTitleCase}}Request request) {
        List<String> errors = new ArrayList<>();

        // Validate name
        validateName(request.getName(), errors);

        // Validate description
        validateDescription(request.getDescription(), errors);

        // Check for uniqueness
        if (request.getName() != null && {{domain}}Repository.existsByNameIgnoreCase(request.getName())) {
            errors.add("{{domainTitleCase}} with name '" + request.getName() + "' already exists");
        }

        // Custom business rules
        validateBusinessRules(request, errors);

        return new ValidationResult(errors.isEmpty(), errors);
    }

    /**
     * Validate {{domainTitleCase}} update request
     */
    public ValidationResult validateUpdateRequest(String id, {{domainTitleCase}}Request request) {
        List<String> errors = new ArrayList<>();

        // Basic validation
        validateName(request.getName(), errors);
        validateDescription(request.getDescription(), errors);

        // Check if entity exists
        {{domainTitleCase}} existing = {{domain}}Repository.findById(id).orElse(null);
        if (existing == null) {
            errors.add("{{domainTitleCase}} with ID '" + id + "' not found");
            return new ValidationResult(false, errors);
        }

        // Check name uniqueness if changed
        if (request.getName() != null &&
            !existing.getName().equalsIgnoreCase(request.getName()) &&
            {{domain}}Repository.existsByNameIgnoreCase(request.getName())) {
            errors.add("{{domainTitleCase}} with name '" + request.getName() + "' already exists");
        }

        // Validate state transitions
        validateStateTransition(existing, request, errors);

        // Custom business rules
        validateBusinessRules(request, errors);

        return new ValidationResult(errors.isEmpty(), errors);
    }

    /**
     * Validate {{domainTitleCase}} deletion
     */
    public ValidationResult validateDeleteRequest(String id) {
        List<String> errors = new ArrayList<>();

        {{domainTitleCase}} entity = {{domain}}Repository.findById(id).orElse(null);
        if (entity == null) {
            errors.add("{{domainTitleCase}} with ID '" + id + "' not found");
            return new ValidationResult(false, errors);
        }

        // Check if deletion is allowed
        if (!canDelete(entity)) {
            errors.add("Cannot delete {{domain}} '" + entity.getName() + "' - it has dependencies or is protected");
        }

        return new ValidationResult(errors.isEmpty(), errors);
    }

    // Specific validation methods

    private void validateName(String name, List<String> errors) {
        if (name == null || name.trim().isEmpty()) {
            errors.add("Name is required");
            return;
        }

        if (name.length() < 2) {
            errors.add("Name must be at least 2 characters long");
        }

        if (name.length() > 100) {
            errors.add("Name cannot exceed 100 characters");
        }

        // Custom name validation
        if (name.startsWith("_") || name.startsWith("-")) {
            errors.add("Name cannot start with underscore or dash");
        }

        // Reserved keywords check
        if (isReservedKeyword(name)) {
            errors.add("Name '" + name + "' is a reserved keyword");
        }
    }

    private void validateDescription(String description, List<String> errors) {
        if (description != null && description.length() > 500) {
            errors.add("Description cannot exceed 500 characters");
        }

        // Check for prohibited content
        if (description != null && containsProhibitedContent(description)) {
            errors.add("Description contains prohibited content");
        }
    }

    private void validateBusinessRules({{domainTitleCase}}Request request, List<String> errors) {
        // Add your custom business validation rules here
        // Examples:

        // Rule 1: Name and description correlation
        if (request.getName() != null && request.getDescription() != null) {
            if (request.getName().length() > request.getDescription().length()) {
                // Example business rule - customize as needed
                // errors.add("Description must be longer than name");
            }
        }

        // Rule 2: Specific naming conventions
        if (request.getName() != null && !request.getName().matches("^[A-Z][a-zA-Z0-9]*$")) {
            // Example: Enforce PascalCase
            // errors.add("Name must start with capital letter and be in PascalCase");
        }

        // Rule 3: Cross-field validation
        // Add more complex business rules as needed
    }

    private void validateStateTransition({{domainTitleCase}} existing, {{domainTitleCase}}Request request, List<String> errors) {
        // Implement state transition validation
        // Example: Check if status changes are valid

        // if (existing.getStatus() == Status.FINALIZED) {
        //     errors.add("Cannot modify finalized {{domain}}");
        // }

        // if (existing.getStatus() == Status.DRAFT && request.getStatus() == Status.PUBLISHED) {
        //     if (!hasRequiredFieldsForPublishing(request)) {
        //         errors.add("Cannot publish - missing required fields");
        //     }
        // }
    }

    private boolean canDelete({{domainTitleCase}} entity) {
        // Implement deletion rules
        // Examples:
        // - Check for dependent entities
        // - Check if entity is in deletable state
        // - Check for system-protected entities

        // System entities cannot be deleted
        if (entity.getName() != null && entity.getName().startsWith("SYSTEM_")) {
            return false;
        }

        // Add more deletion rules as needed
        return true;
    }

    private boolean isReservedKeyword(String name) {
        // Define reserved keywords for your domain
        String[] reservedKeywords = {
            "admin", "system", "root", "default", "null", "undefined"
        };

        String lowerName = name.toLowerCase();
        for (String keyword : reservedKeywords) {
            if (lowerName.equals(keyword)) {
                return true;
            }
        }
        return false;
    }

    private boolean containsProhibitedContent(String text) {
        // Implement content filtering
        // Check for SQL injection attempts, XSS, etc.

        String lowerText = text.toLowerCase();

        // Check for SQL injection patterns
        if (lowerText.contains("drop table") ||
            lowerText.contains("delete from") ||
            lowerText.contains("insert into")) {
            return true;
        }

        // Check for script injection
        if (lowerText.contains("<script") ||
            lowerText.contains("javascript:") ||
            lowerText.contains("onerror=")) {
            return true;
        }

        return false;
    }

    /**
     * Validation result class
     */
    public static class ValidationResult {
        private final boolean valid;
        private final List<String> errors;

        public ValidationResult(boolean valid, List<String> errors) {
            this.valid = valid;
            this.errors = errors != null ? errors : new ArrayList<>();
        }

        public boolean isValid() {
            return valid;
        }

        public List<String> getErrors() {
            return errors;
        }

        public String getErrorMessage() {
            return String.join("; ", errors);
        }

        @Override
        public String toString() {
            return "ValidationResult{" +
                    "valid=" + valid +
                    ", errors=" + errors +
                    '}';
        }
    }

    /**
     * Custom constraint validator for unique {{domainTitleCase}} name
     */
    public static class Unique{{domainTitleCase}}NameValidator
            implements ConstraintValidator<Unique{{domainTitleCase}}Name, String> {

        @Autowired
        private {{domainTitleCase}}Repository {{domain}}Repository;

        @Override
        public void initialize(Unique{{domainTitleCase}}Name constraintAnnotation) {
            // Initialization if needed
        }

        @Override
        public boolean isValid(String name, ConstraintValidatorContext context) {
            if (name == null) {
                return true; // Let @NotNull handle null validation
            }

            boolean exists = {{domain}}Repository.existsByNameIgnoreCase(name);

            if (exists) {
                context.disableDefaultConstraintViolation();
                context.buildConstraintViolationWithTemplate(
                    "{{domainTitleCase}} with name '" + name + "' already exists")
                    .addConstraintViolation();
            }

            return !exists;
        }
    }
}