package {{packageName}}.enterprise.validation;

import java.util.List;

/**
 * 👨‍💻 BUSINESS INTERFACE - IMPLEMENT THIS
 *
 * Business Validator interface for implementing domain-specific validation rules.
 * This is the ONLY validation interface developers need to implement.
 *
 * The Enterprise infrastructure handles:
 * - Framework validation (annotations, constraints)
 * - Error handling and formatting
 * - Audit logging of validation failures
 * - Metrics collection
 *
 * Developers implement:
 * - Business-specific validation logic
 * - Cross-field validation rules
 * - Domain integrity constraints
 *
 * Generated by Enterprise CLI - Business layer interface
 */
public interface BusinessValidator<T, CreateDTO, UpdateDTO> {

    /**
     * 👨‍💻 IMPLEMENT: Validate entity creation
     *
     * @param createDTO The data for creating the entity
     * @return ValidationResult with success/failure and error messages
     */
    ValidationResult validateCreate(CreateDTO createDTO);

    /**
     * 👨‍💻 IMPLEMENT: Validate entity update
     *
     * @param entityId The ID of the entity being updated
     * @param updateDTO The update data
     * @param existingEntity The current state of the entity
     * @return ValidationResult with success/failure and error messages
     */
    ValidationResult validateUpdate(Object entityId, UpdateDTO updateDTO, T existingEntity);

    /**
     * 👨‍💻 IMPLEMENT: Validate entity deletion
     *
     * @param entityId The ID of the entity being deleted
     * @param entity The entity being deleted
     * @return ValidationResult with success/failure and error messages
     */
    ValidationResult validateDelete(Object entityId, T entity);

    /**
     * 🔧 OPTIONAL: Validate business state transitions
     * Override this method if your entity has state transitions
     *
     * @param entity The entity
     * @param fromState Previous state
     * @param toState New state
     * @return ValidationResult with success/failure and error messages
     */
    default ValidationResult validateStateTransition(T entity, String fromState, String toState) {
        return ValidationResult.success();
    }

    /**
     * 🔧 OPTIONAL: Validate business rules for bulk operations
     * Override this method if you support bulk operations
     *
     * @param entities List of entities
     * @param operation The bulk operation type
     * @return ValidationResult with success/failure and error messages
     */
    default ValidationResult validateBulkOperation(List<T> entities, String operation) {
        return ValidationResult.success();
    }

    /**
     * ValidationResult class for returning validation outcomes
     */
    class ValidationResult {
        private final boolean valid;
        private final List<String> errors;
        private final List<String> warnings;
        private final String errorCode;

        public ValidationResult(boolean valid, List<String> errors, List<String> warnings, String errorCode) {
            this.valid = valid;
            this.errors = errors != null ? errors : List.of();
            this.warnings = warnings != null ? warnings : List.of();
            this.errorCode = errorCode;
        }

        public static ValidationResult success() {
            return new ValidationResult(true, List.of(), List.of(), null);
        }

        public static ValidationResult success(List<String> warnings) {
            return new ValidationResult(true, List.of(), warnings, null);
        }

        public static ValidationResult failure(String error) {
            return new ValidationResult(false, List.of(error), List.of(), null);
        }

        public static ValidationResult failure(List<String> errors) {
            return new ValidationResult(false, errors, List.of(), null);
        }

        public static ValidationResult failure(String error, String errorCode) {
            return new ValidationResult(false, List.of(error), List.of(), errorCode);
        }

        public static ValidationResult failure(List<String> errors, String errorCode) {
            return new ValidationResult(false, errors, List.of(), errorCode);
        }

        public static ValidationResult failureWithWarnings(List<String> errors, List<String> warnings) {
            return new ValidationResult(false, errors, warnings, null);
        }

        // Getters
        public boolean isValid() {
            return valid;
        }

        public List<String> getErrors() {
            return errors;
        }

        public List<String> getWarnings() {
            return warnings;
        }

        public String getErrorCode() {
            return errorCode;
        }

        public boolean hasWarnings() {
            return !warnings.isEmpty();
        }

        public String getErrorMessage() {
            return String.join("; ", errors);
        }

        public String getWarningMessage() {
            return String.join("; ", warnings);
        }

        @Override
        public String toString() {
            return "ValidationResult{" +
                    "valid=" + valid +
                    ", errors=" + errors +
                    ", warnings=" + warnings +
                    ", errorCode='" + errorCode + '\'' +
                    '}';
        }
    }

    /**
     * Abstract base class for common validation utilities
     * Extend this for convenience methods
     */
    abstract class AbstractBusinessValidator<T, CreateDTO, UpdateDTO> implements BusinessValidator<T, CreateDTO, UpdateDTO> {

        /**
         * 🔧 Utility: Check if string is null or empty
         */
        protected boolean isNullOrEmpty(String value) {
            return value == null || value.trim().isEmpty();
        }

        /**
         * 🔧 Utility: Check if value is within range
         */
        protected boolean isInRange(Number value, Number min, Number max) {
            if (value == null) return false;
            double val = value.doubleValue();
            double minVal = min != null ? min.doubleValue() : Double.MIN_VALUE;
            double maxVal = max != null ? max.doubleValue() : Double.MAX_VALUE;
            return val >= minVal && val <= maxVal;
        }

        /**
         * 🔧 Utility: Check if string matches pattern
         */
        protected boolean matchesPattern(String value, String pattern) {
            if (value == null || pattern == null) return false;
            return value.matches(pattern);
        }

        /**
         * 🔧 Utility: Check if email format is valid
         */
        protected boolean isValidEmail(String email) {
            if (isNullOrEmpty(email)) return false;
            return matchesPattern(email, "^[A-Za-z0-9+_.-]+@([A-Za-z0-9.-]+\\.[A-Za-z]{2,})$");
        }

        /**
         * 🔧 Utility: Check if phone format is valid
         */
        protected boolean isValidPhone(String phone) {
            if (isNullOrEmpty(phone)) return false;
            return matchesPattern(phone, "^\\+?[1-9]\\d{1,14}$");
        }

        /**
         * 🔧 Utility: Check if URL format is valid
         */
        protected boolean isValidUrl(String url) {
            if (isNullOrEmpty(url)) return false;
            return matchesPattern(url, "^(https?|ftp)://[^\\s/$.?#].[^\\s]*$");
        }

        /**
         * 🔧 Utility: Create validation builder for complex validations
         */
        protected ValidationBuilder validationBuilder() {
            return new ValidationBuilder();
        }

        /**
         * Validation Builder for fluent validation
         */
        protected static class ValidationBuilder {
            private boolean valid = true;
            private final List<String> errors = new java.util.ArrayList<>();
            private final List<String> warnings = new java.util.ArrayList<>();
            private String errorCode;

            public ValidationBuilder check(boolean condition, String errorMessage) {
                if (!condition) {
                    valid = false;
                    errors.add(errorMessage);
                }
                return this;
            }

            public ValidationBuilder warn(boolean condition, String warningMessage) {
                if (!condition) {
                    warnings.add(warningMessage);
                }
                return this;
            }

            public ValidationBuilder checkNotNull(Object value, String fieldName) {
                return check(value != null, fieldName + " is required");
            }

            public ValidationBuilder checkNotEmpty(String value, String fieldName) {
                return check(value != null && !value.trim().isEmpty(), fieldName + " cannot be empty");
            }

            public ValidationBuilder checkMinLength(String value, int minLength, String fieldName) {
                return check(value != null && value.length() >= minLength,
                           fieldName + " must be at least " + minLength + " characters");
            }

            public ValidationBuilder checkMaxLength(String value, int maxLength, String fieldName) {
                return check(value == null || value.length() <= maxLength,
                           fieldName + " cannot exceed " + maxLength + " characters");
            }

            public ValidationBuilder checkRange(Number value, Number min, Number max, String fieldName) {
                if (value != null) {
                    double val = value.doubleValue();
                    if (min != null) {
                        check(val >= min.doubleValue(), fieldName + " must be at least " + min);
                    }
                    if (max != null) {
                        check(val <= max.doubleValue(), fieldName + " cannot exceed " + max);
                    }
                }
                return this;
            }

            public ValidationBuilder errorCode(String code) {
                this.errorCode = code;
                return this;
            }

            public ValidationResult build() {
                return new ValidationResult(valid, errors, warnings, errorCode);
            }
        }
    }
}