-- Flyway migration script for {{domainTitleCase}} entity
-- This is a sample migration generated by Enterprise CLI.
-- Customize the schema according to your business requirements.

-- Create {{domain}}s table
CREATE TABLE IF NOT EXISTS {{domain}}s (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_{{domain}}s_name ON {{domain}}s(name);
CREATE INDEX IF NOT EXISTS idx_{{domain}}s_created_at ON {{domain}}s(created_at);
CREATE INDEX IF NOT EXISTS idx_{{domain}}s_name_lower ON {{domain}}s(LOWER(name));

-- Add unique constraint for name (case-insensitive)
{{#postgresql}}
CREATE UNIQUE INDEX IF NOT EXISTS idx_{{domain}}s_name_unique ON {{domain}}s(LOWER(name));
{{/postgresql}}
{{#mysql}}
-- MySQL: Add unique constraint on name
ALTER TABLE {{domain}}s ADD CONSTRAINT uk_{{domain}}s_name UNIQUE (name);
{{/mysql}}
{{#h2}}
-- H2: Add unique constraint on name (case-insensitive)
ALTER TABLE {{domain}}s ADD CONSTRAINT uk_{{domain}}s_name UNIQUE (name);
{{/h2}}

-- Insert sample data (optional - remove if not needed)
INSERT INTO {{domain}}s (id, name, description, created_at, updated_at, version) VALUES
    ('550e8400-e29b-41d4-a716-446655440001', 'Sample {{domainTitleCase}} 1', 'This is a sample {{domain}} created by migration', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
    ('550e8400-e29b-41d4-a716-446655440002', 'Sample {{domainTitleCase}} 2', 'Another sample {{domain}} for testing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
    ('550e8400-e29b-41d4-a716-446655440003', 'Sample {{domainTitleCase}} 3', 'Third sample {{domain}} with longer description to test various field lengths', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0)
ON CONFLICT (id) DO NOTHING;

-- Add comments to table and columns for documentation
{{#postgresql}}
COMMENT ON TABLE {{domain}}s IS '{{domainTitleCase}} entities managed by the enterprise microservice';
COMMENT ON COLUMN {{domain}}s.id IS 'Unique identifier (UUID)';
COMMENT ON COLUMN {{domain}}s.name IS '{{domainTitleCase}} name (2-100 characters)';
COMMENT ON COLUMN {{domain}}s.description IS 'Optional description (max 500 characters)';
COMMENT ON COLUMN {{domain}}s.created_at IS 'Record creation timestamp';
COMMENT ON COLUMN {{domain}}s.updated_at IS 'Last update timestamp';
COMMENT ON COLUMN {{domain}}s.version IS 'Optimistic locking version';
{{/postgresql}}