package {{packageName}}.enterprise.base;

import {{packageName}}.enterprise.patterns.EnterpriseMetricsCollector;
import {{packageName}}.enterprise.patterns.EnterpriseAuditLogger;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import jakarta.validation.Valid;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.net.URI;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * 🤖 ENTERPRISE INFRASTRUCTURE - DO NOT MODIFY
 *
 * Abstract Enterprise Controller providing standardized REST endpoints:
 * - Complete CRUD operations
 * - Standardized error handling
 * - OpenAPI documentation
 * - Request/Response validation
 * - Audit logging
 * - Metrics collection
 * - Security headers
 * - Rate limiting integration
 *
 * Template Method Pattern:
 * Developers implement ONLY business customization methods marked with 👨‍💻
 * All REST infrastructure is handled automatically.
 *
 * Generated by Enterprise CLI - Infrastructure layer
 */
public abstract class AbstractEnterpriseController<T, ID, CreateDTO, UpdateDTO, ResponseDTO> {

    protected final Logger logger = LoggerFactory.getLogger(this.getClass());

    // 🤖 Infrastructure Dependencies - Injected automatically
    @Autowired
    private EnterpriseMetricsCollector metricsCollector;

    @Autowired
    private EnterpriseAuditLogger auditLogger;

    // ================================
    // 🤖 STANDARD REST ENDPOINTS - DO NOT OVERRIDE
    // ================================

    /**
     * 🤖 GET /entities - List all entities with pagination
     */
    @GetMapping
    @Operation(summary = "Get all entities", description = "Retrieve a paginated list of entities")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Successfully retrieved entities"),
            @ApiResponse(responseCode = "400", description = "Invalid pagination parameters"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
    })
    public final ResponseEntity<Page<ResponseDTO>> getAll(
            @Parameter(description = "Pagination parameters") Pageable pageable) {

        try {
            logger.debug("🔍 GET {} - pageable: {}", getEntityPathName(), pageable);

            // 🤖 Infrastructure: Audit request
            auditLogger.logDataAccess(getEntityName(), null, "LIST");

            // 👨‍💻 Business: Delegate to service (developer implements)
            Page<ResponseDTO> result = getEnterpriseService().findAll(pageable);

            // 👨‍💻 Business: Allow custom response processing (developer can override)
            ResponseEntity<Page<ResponseDTO>> response = customizeListResponse(result, pageable);

            logger.debug("✅ GET {} - found {} entities", getEntityPathName(), result.getNumberOfElements());
            return response;

        } catch (Exception e) {
            logger.error("💥 GET {} failed", getEntityPathName(), e);
            return handleError(e, "Failed to retrieve " + getEntityName() + " list");
        }
    }

    /**
     * 🤖 GET /entities/{id} - Get entity by ID
     */
    @GetMapping("/{id}")
    @Operation(summary = "Get entity by ID", description = "Retrieve a specific entity by its unique identifier")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Entity found"),
            @ApiResponse(responseCode = "404", description = "Entity not found"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
    })
    public final ResponseEntity<ResponseDTO> getById(
            @Parameter(description = "Entity unique identifier") @PathVariable ID id) {

        try {
            logger.debug("🔍 GET {}/{}", getEntityPathName(), id);

            // 🤖 Infrastructure: Audit request
            auditLogger.logDataAccess(getEntityName(), id, "READ");

            // 👨‍💻 Business: Delegate to service (developer implements)
            Optional<ResponseDTO> result = getEnterpriseService().findById(id);

            if (result.isPresent()) {
                // 👨‍💻 Business: Allow custom response processing (developer can override)
                ResponseEntity<ResponseDTO> response = customizeGetResponse(result.get(), id);

                logger.debug("✅ GET {}/{} - found", getEntityPathName(), id);
                return response;
            } else {
                logger.debug("❌ GET {}/{} - not found", getEntityPathName(), id);
                return ResponseEntity.notFound().build();
            }

        } catch (Exception e) {
            logger.error("💥 GET {}/{} failed", getEntityPathName(), id, e);
            return handleError(e, "Failed to retrieve " + getEntityName() + " with ID: " + id);
        }
    }

    /**
     * 🤖 POST /entities - Create new entity
     */
    @PostMapping
    @Operation(summary = "Create new entity", description = "Create a new entity with the provided information")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "201", description = "Entity created successfully"),
            @ApiResponse(responseCode = "400", description = "Invalid input data"),
            @ApiResponse(responseCode = "409", description = "Entity already exists"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
    })
    public final ResponseEntity<ResponseDTO> create(@Valid @RequestBody CreateDTO createDTO) {

        try {
            logger.info("📝 POST {} - creating new {}", getEntityPathName(), getEntityName());

            // 👨‍💻 Business: Allow custom request validation (developer can override)
            validateCreateRequest(createDTO);

            // 👨‍💻 Business: Delegate to service (developer implements)
            ResponseDTO result = getEnterpriseService().create(createDTO);

            // 👨‍💻 Business: Allow custom response processing (developer can override)
            ResponseEntity<ResponseDTO> response = customizeCreateResponse(result, createDTO);

            logger.info("✅ POST {} - created with ID: {}", getEntityPathName(), extractEntityId(result));
            return response;

        } catch (AbstractEnterpriseService.BusinessValidationException e) {
            logger.warn("❌ POST {} - validation failed: {}", getEntityPathName(), e.getMessage());
            return ResponseEntity.badRequest().build();
        } catch (Exception e) {
            logger.error("💥 POST {} failed", getEntityPathName(), e);
            return handleError(e, "Failed to create " + getEntityName());
        }
    }

    /**
     * 🤖 PUT /entities/{id} - Update entity
     */
    @PutMapping("/{id}")
    @Operation(summary = "Update entity", description = "Update an existing entity with new information")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Entity updated successfully"),
            @ApiResponse(responseCode = "400", description = "Invalid input data"),
            @ApiResponse(responseCode = "404", description = "Entity not found"),
            @ApiResponse(responseCode = "409", description = "Conflict with existing data"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
    })
    public final ResponseEntity<ResponseDTO> update(
            @Parameter(description = "Entity unique identifier") @PathVariable ID id,
            @Valid @RequestBody UpdateDTO updateDTO) {

        try {
            logger.info("📝 PUT {}/{} - updating {}", getEntityPathName(), id, getEntityName());

            // 👨‍💻 Business: Allow custom request validation (developer can override)
            validateUpdateRequest(id, updateDTO);

            // 👨‍💻 Business: Delegate to service (developer implements)
            Optional<ResponseDTO> result = getEnterpriseService().update(id, updateDTO);

            if (result.isPresent()) {
                // 👨‍💻 Business: Allow custom response processing (developer can override)
                ResponseEntity<ResponseDTO> response = customizeUpdateResponse(result.get(), id, updateDTO);

                logger.info("✅ PUT {}/{} - updated successfully", getEntityPathName(), id);
                return response;
            } else {
                logger.warn("❌ PUT {}/{} - not found", getEntityPathName(), id);
                return ResponseEntity.notFound().build();
            }

        } catch (AbstractEnterpriseService.BusinessValidationException e) {
            logger.warn("❌ PUT {}/{} - validation failed: {}", getEntityPathName(), id, e.getMessage());
            return ResponseEntity.badRequest().build();
        } catch (Exception e) {
            logger.error("💥 PUT {}/{} failed", getEntityPathName(), id, e);
            return handleError(e, "Failed to update " + getEntityName() + " with ID: " + id);
        }
    }

    /**
     * 🤖 DELETE /entities/{id} - Delete entity
     */
    @DeleteMapping("/{id}")
    @Operation(summary = "Delete entity", description = "Delete an entity by its unique identifier")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "204", description = "Entity deleted successfully"),
            @ApiResponse(responseCode = "404", description = "Entity not found"),
            @ApiResponse(responseCode = "409", description = "Cannot delete entity due to dependencies"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
    })
    public final ResponseEntity<Void> delete(
            @Parameter(description = "Entity unique identifier") @PathVariable ID id) {

        try {
            logger.info("🗑️ DELETE {}/{} - deleting {}", getEntityPathName(), id, getEntityName());

            // 👨‍💻 Business: Allow custom deletion validation (developer can override)
            validateDeleteRequest(id);

            // 👨‍💻 Business: Delegate to service (developer implements)
            boolean deleted = getEnterpriseService().delete(id);

            if (deleted) {
                // 👨‍💻 Business: Allow custom post-delete processing (developer can override)
                handlePostDelete(id);

                logger.info("✅ DELETE {}/{} - deleted successfully", getEntityPathName(), id);
                return ResponseEntity.noContent().build();
            } else {
                logger.warn("❌ DELETE {}/{} - not found", getEntityPathName(), id);
                return ResponseEntity.notFound().build();
            }

        } catch (AbstractEnterpriseService.BusinessValidationException e) {
            logger.warn("❌ DELETE {}/{} - validation failed: {}", getEntityPathName(), id, e.getMessage());
            return ResponseEntity.status(HttpStatus.CONFLICT).build();
        } catch (Exception e) {
            logger.error("💥 DELETE {}/{} failed", getEntityPathName(), id, e);
            return handleError(e, "Failed to delete " + getEntityName() + " with ID: " + id);
        }
    }

    /**
     * 🤖 GET /entities/search - Search entities
     */
    @GetMapping("/search")
    @Operation(summary = "Search entities", description = "Search entities using various criteria")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Search completed successfully"),
            @ApiResponse(responseCode = "400", description = "Invalid search parameters"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
    })
    public final ResponseEntity<List<ResponseDTO>> search(
            @Parameter(description = "Search parameters") @RequestParam Map<String, String> searchParams) {

        try {
            logger.debug("🔍 GET {}/search - params: {}", getEntityPathName(), searchParams);

            // 🤖 Infrastructure: Audit search request
            auditLogger.logDataAccess(getEntityName(), null, "SEARCH");

            // 👨‍💻 Business: Delegate to custom search (developer implements)
            List<ResponseDTO> result = performSearch(searchParams);

            // 👨‍💻 Business: Allow custom response processing (developer can override)
            ResponseEntity<List<ResponseDTO>> response = customizeSearchResponse(result, searchParams);

            logger.debug("✅ GET {}/search - found {} results", getEntityPathName(), result.size());
            return response;

        } catch (Exception e) {
            logger.error("💥 GET {}/search failed", getEntityPathName(), e);
            return handleError(e, "Failed to search " + getEntityName());
        }
    }

    /**
     * 🤖 GET /entities/health - Health check endpoint
     */
    @GetMapping("/health")
    @Operation(summary = "Health check", description = "Check the health of the entity service")
    @ApiResponse(responseCode = "200", description = "Service is healthy")
    public final ResponseEntity<String> health() {
        try {
            // 👨‍💻 Business: Allow custom health checks (developer can override)
            String healthStatus = performHealthCheck();

            return ResponseEntity.ok("✅ " + getEntityName() + " Service: " + healthStatus);
        } catch (Exception e) {
            logger.error("💥 Health check failed for {}", getEntityName(), e);
            return ResponseEntity.status(HttpStatus.SERVICE_UNAVAILABLE)
                                 .body("❌ " + getEntityName() + " Service: UNHEALTHY");
        }
    }

    // ================================
    // 👨‍💻 BUSINESS METHODS - IMPLEMENT THESE
    // ================================

    /**
     * 👨‍💻 IMPLEMENT: Get the enterprise service instance
     * Return your service that extends AbstractEnterpriseService
     */
    protected abstract AbstractEnterpriseService<T, ID, CreateDTO, UpdateDTO, ResponseDTO> getEnterpriseService();

    /**
     * 👨‍💻 IMPLEMENT: Get entity name for logging and responses
     */
    protected abstract String getEntityName();

    /**
     * 👨‍💻 IMPLEMENT: Get entity path name for REST endpoints
     */
    protected abstract String getEntityPathName();

    /**
     * 👨‍💻 IMPLEMENT: Extract entity ID from response DTO for logging
     */
    protected abstract ID extractEntityId(ResponseDTO responseDTO);

    /**
     * 👨‍💻 IMPLEMENT: Perform custom search logic
     * Implement your search criteria handling
     */
    protected abstract List<ResponseDTO> performSearch(Map<String, String> searchParams);

    // ================================
    // 🔧 EXTENSION POINTS - OVERRIDE IF NEEDED
    // ================================

    /**
     * 🔧 OPTIONAL: Additional validation for create requests
     */
    protected void validateCreateRequest(CreateDTO createDTO) {
        // Default: no additional validation
    }

    /**
     * 🔧 OPTIONAL: Additional validation for update requests
     */
    protected void validateUpdateRequest(ID id, UpdateDTO updateDTO) {
        // Default: no additional validation
    }

    /**
     * 🔧 OPTIONAL: Additional validation for delete requests
     */
    protected void validateDeleteRequest(ID id) {
        // Default: no additional validation
    }

    /**
     * 🔧 OPTIONAL: Customize list response
     */
    protected ResponseEntity<Page<ResponseDTO>> customizeListResponse(Page<ResponseDTO> result, Pageable pageable) {
        return ResponseEntity.ok(result);
    }

    /**
     * 🔧 OPTIONAL: Customize get response
     */
    protected ResponseEntity<ResponseDTO> customizeGetResponse(ResponseDTO result, ID id) {
        return ResponseEntity.ok(result);
    }

    /**
     * 🔧 OPTIONAL: Customize create response
     */
    protected ResponseEntity<ResponseDTO> customizeCreateResponse(ResponseDTO result, CreateDTO createDTO) {
        try {
            ID entityId = extractEntityId(result);
            URI location = URI.create("/" + getEntityPathName() + "/" + entityId);
            return ResponseEntity.created(location).body(result);
        } catch (Exception e) {
            return ResponseEntity.status(HttpStatus.CREATED).body(result);
        }
    }

    /**
     * 🔧 OPTIONAL: Customize update response
     */
    protected ResponseEntity<ResponseDTO> customizeUpdateResponse(ResponseDTO result, ID id, UpdateDTO updateDTO) {
        return ResponseEntity.ok(result);
    }

    /**
     * 🔧 OPTIONAL: Customize search response
     */
    protected ResponseEntity<List<ResponseDTO>> customizeSearchResponse(List<ResponseDTO> result, Map<String, String> searchParams) {
        return ResponseEntity.ok(result);
    }

    /**
     * 🔧 OPTIONAL: Handle post-delete operations
     */
    protected void handlePostDelete(ID id) {
        // Default: no post-delete handling
    }

    /**
     * 🔧 OPTIONAL: Perform custom health check
     */
    protected String performHealthCheck() {
        return "HEALTHY";
    }

    // ================================
    // 🤖 PRIVATE INFRASTRUCTURE METHODS - DO NOT OVERRIDE
    // ================================

    private <R> ResponseEntity<R> handleError(Exception e, String message) {
        logger.error("🔴 {}: {}", message, e.getMessage());

        if (e instanceof AbstractEnterpriseService.BusinessValidationException) {
            return ResponseEntity.badRequest().build();
        } else if (e instanceof IllegalArgumentException) {
            return ResponseEntity.badRequest().build();
        } else {
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
        }
    }
}