package {{packageName}}.enterprise.base;

import {{packageName}}.enterprise.patterns.EnterpriseEventPublisher;
import {{packageName}}.enterprise.patterns.MetricsCollector;
import {{packageName}}.enterprise.patterns.EnterpriseAuditLogger;
import {{packageName}}.enterprise.validation.BusinessValidator;
import {{packageName}}.enterprise.rules.BusinessRules;
import io.micrometer.core.instrument.Timer;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.cache.annotation.CacheEvict;
import org.springframework.cache.annotation.CachePut;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;

/**
 * 🤖 ENTERPRISE INFRASTRUCTURE - DO NOT MODIFY
 *
 * Abstract Enterprise Service providing complete infrastructure patterns:
 * - Transaction management
 * - Caching strategy
 * - Metrics collection
 * - Event publishing
 * - Audit logging
 * - Error handling
 * - Performance monitoring
 *
 * Template Method Pattern:
 * Developers implement ONLY business logic methods marked with 👨‍💻
 * All infrastructure concerns are handled automatically.
 *
 * Generated by Enterprise CLI - Infrastructure layer
 */
@Transactional
public abstract class AbstractEnterpriseService<T, ID, CreateDTO, UpdateDTO, ResponseDTO> {

    protected final Logger logger = LoggerFactory.getLogger(this.getClass());

    // 🤖 Infrastructure Dependencies - Injected automatically
    @Autowired
    private EnterpriseEventPublisher eventPublisher;

    @Autowired
    private MetricsCollector metricsCollector;

    @Autowired
    private EnterpriseAuditLogger auditLogger;

    // Business components - set by concrete implementations
    private BusinessValidator<T, CreateDTO, UpdateDTO> businessValidator;
    private BusinessRules<T, CreateDTO, UpdateDTO> businessRules;

    // ================================
    // 🤖 INFRASTRUCTURE METHODS - DO NOT OVERRIDE
    // ================================

    /**
     * 🤖 Create operation with full enterprise infrastructure
     * Handles: validation, persistence, events, metrics, audit, caching
     */
    @CacheEvict(value = "#{this.getCacheName()}", allEntries = true)
    public final ResponseDTO create(CreateDTO createDTO) {
        Timer.Sample timer = metricsCollector.startCreationTimer(getEntityClass());

        try {
            // 🤖 Infrastructure: Pre-creation audit
            auditLogger.logOperationStart("CREATE", getEntityClass().getSimpleName(), null, createDTO);

            // 🤖 Infrastructure: Framework validation
            validateFrameworkConstraints(createDTO);

            // 👨‍💻 Business: Custom validation (developer implements)
            if (businessValidator != null) {
                var validationResult = businessValidator.validateCreate(createDTO);
                if (!validationResult.isValid()) {
                    throw new BusinessValidationException(validationResult.getErrorMessage());
                }
            }

            // 👨‍💻 Business: Entity creation (developer implements)
            T entity = createEntityFromRequest(createDTO);

            // 🤖 Infrastructure: Apply enterprise rules
            applyEnterpriseRules(entity, "CREATE");

            // 👨‍💻 Business: Apply business rules (developer implements)
            if (businessRules != null) {
                businessRules.applyCreateRules(entity, createDTO);
            }

            // 🤖 Infrastructure: Persistence
            T savedEntity = getRepository().save(entity);

            // 🤖 Infrastructure: Event publishing
            eventPublisher.publishCreated(savedEntity);

            // 👨‍💻 Business: Post-creation business logic (developer can override)
            handlePostCreation(savedEntity);

            // 🤖 Infrastructure: Convert to response DTO
            ResponseDTO response = convertToResponse(savedEntity);

            // 🤖 Infrastructure: Metrics and audit
            metricsCollector.recordCreation(getEntityClass());
            auditLogger.logOperationSuccess("CREATE", getEntityClass().getSimpleName(),
                                          extractEntityId(savedEntity), response);

            logger.info("✅ Successfully created {} with ID: {}",
                       getEntityClass().getSimpleName(), extractEntityId(savedEntity));

            return response;

        } catch (BusinessValidationException e) {
            // 🤖 Infrastructure: Business validation errors
            metricsCollector.recordValidationError(getEntityClass());
            auditLogger.logValidationError("CREATE", getEntityClass().getSimpleName(), null, e);
            logger.warn("❌ Business validation failed for {}: {}", getEntityClass().getSimpleName(), e.getMessage());
            throw e;
        } catch (Exception e) {
            // 🤖 Infrastructure: System errors
            metricsCollector.recordSystemError(getEntityClass());
            auditLogger.logSystemError("CREATE", getEntityClass().getSimpleName(), null, e);
            logger.error("💥 System error creating {}: {}", getEntityClass().getSimpleName(), e.getMessage(), e);
            throw new EnterpriseServiceException("Failed to create " + getEntityClass().getSimpleName(), e);
        } finally {
            metricsCollector.stopCreationTimer(timer, getEntityClass());
        }
    }

    /**
     * 🤖 Read operation with enterprise caching and metrics
     */
    @Transactional(readOnly = true)
    @Cacheable(value = "#{this.getCacheName()}", key = "#id")
    public final Optional<ResponseDTO> findById(ID id) {
        Timer.Sample timer = metricsCollector.startReadTimer(getEntityClass());

        try {
            logger.debug("🔍 Fetching {} with ID: {}", getEntityClass().getSimpleName(), id);

            // 👨‍💻 Business: Entity retrieval (developer implements)
            Optional<T> entity = getRepository().findById(id);

            if (entity.isPresent()) {
                // 🤖 Infrastructure: Metrics and response conversion
                metricsCollector.recordRead(getEntityClass());
                ResponseDTO response = convertToResponse(entity.get());

                logger.debug("✅ Found {} with ID: {}", getEntityClass().getSimpleName(), id);
                return Optional.of(response);
            } else {
                logger.debug("❌ {} not found with ID: {}", getEntityClass().getSimpleName(), id);
                return Optional.empty();
            }

        } finally {
            metricsCollector.stopReadTimer(timer, getEntityClass());
        }
    }

    /**
     * 🤖 Update operation with full enterprise infrastructure
     */
    @CachePut(value = "#{this.getCacheName()}", key = "#id")
    @CacheEvict(value = "#{this.getCacheName()}-list", allEntries = true)
    public final Optional<ResponseDTO> update(ID id, UpdateDTO updateDTO) {
        Timer.Sample timer = metricsCollector.startUpdateTimer(getEntityClass());

        try {
            // 🤖 Infrastructure: Pre-update audit
            auditLogger.logOperationStart("UPDATE", getEntityClass().getSimpleName(), id, updateDTO);

            // 👨‍💻 Business: Find existing entity (developer implements)
            Optional<T> existingEntityOpt = getRepository().findById(id);

            if (existingEntityOpt.isEmpty()) {
                logger.warn("❌ {} not found for update with ID: {}", getEntityClass().getSimpleName(), id);
                return Optional.empty();
            }

            T existingEntity = existingEntityOpt.get();
            T previousState = existingEntity; // Simplified for now

            // 🤖 Infrastructure: Framework validation
            validateFrameworkConstraints(updateDTO);

            // 👨‍💻 Business: Update validation (developer implements)
            if (businessValidator != null) {
                var validationResult = businessValidator.validateUpdate(id, updateDTO, existingEntity);
                if (!validationResult.isValid()) {
                    throw new BusinessValidationException(validationResult.getErrorMessage());
                }
            }

            // 👨‍💻 Business: Entity update (developer implements)
            updateEntityFromRequest(updateDTO, existingEntity);

            // 🤖 Infrastructure: Apply enterprise rules
            applyEnterpriseRules(existingEntity, "UPDATE");

            // 👨‍💻 Business: Apply business rules (developer implements)
            if (businessRules != null) {
                businessRules.applyUpdateRules(existingEntity, updateDTO, previousState);
            }

            // 🤖 Infrastructure: Persistence
            T updatedEntity = getRepository().save(existingEntity);

            // 🤖 Infrastructure: Event publishing
            eventPublisher.publishUpdated(previousState, updatedEntity);

            // 👨‍💻 Business: Post-update business logic (developer can override)
            handlePostUpdate(previousState, updatedEntity);

            // 🤖 Infrastructure: Convert to response DTO
            ResponseDTO response = convertToResponse(updatedEntity);

            // 🤖 Infrastructure: Metrics and audit
            metricsCollector.recordUpdate(getEntityClass());
            auditLogger.logOperationSuccess("UPDATE", getEntityClass().getSimpleName(), id, response);

            logger.info("✅ Successfully updated {} with ID: {}", getEntityClass().getSimpleName(), id);

            return Optional.of(response);

        } catch (BusinessValidationException e) {
            metricsCollector.recordValidationError(getEntityClass());
            auditLogger.logValidationError("UPDATE", getEntityClass().getSimpleName(), id, e);
            logger.warn("❌ Business validation failed for {} update: {}", getEntityClass().getSimpleName(), e.getMessage());
            throw e;
        } catch (Exception e) {
            metricsCollector.recordSystemError(getEntityClass());
            auditLogger.logSystemError("UPDATE", getEntityClass().getSimpleName(), id, e);
            logger.error("💥 System error updating {}: {}", getEntityClass().getSimpleName(), e.getMessage(), e);
            throw new EnterpriseServiceException("Failed to update " + getEntityClass().getSimpleName(), e);
        } finally {
            metricsCollector.stopUpdateTimer(timer, getEntityClass());
        }
    }

    /**
     * 🤖 Delete operation with full enterprise infrastructure
     */
    @CacheEvict(value = {"#{this.getCacheName()}", "#{this.getCacheName()}-list"}, allEntries = true)
    public final boolean delete(ID id) {
        Timer.Sample timer = metricsCollector.startDeleteTimer(getEntityClass());

        try {
            // 🤖 Infrastructure: Pre-deletion audit
            auditLogger.logOperationStart("DELETE", getEntityClass().getSimpleName(), id, null);

            // 👨‍💻 Business: Find entity to delete (developer implements)
            Optional<T> entityOpt = getRepository().findById(id);

            if (entityOpt.isEmpty()) {
                logger.warn("❌ {} not found for deletion with ID: {}", getEntityClass().getSimpleName(), id);
                return false;
            }

            T entity = entityOpt.get();

            // 👨‍💻 Business: Validate deletion rules (developer implements)
            if (businessValidator != null) {
                var validationResult = businessValidator.validateDelete(id, entity);
                if (!validationResult.isValid()) {
                    throw new BusinessValidationException(validationResult.getErrorMessage());
                }
            }

            // 👨‍💻 Business: Check if entity can be deleted (developer implements)
            if (businessRules != null && !businessRules.canDelete(entity)) {
                throw new BusinessValidationException("Entity cannot be deleted due to business rules");
            }

            // 👨‍💻 Business: Pre-deletion business logic (developer can override)
            handlePreDeletion(entity);

            // 👨‍💻 Business: Apply delete rules (developer implements)
            if (businessRules != null) {
                businessRules.applyDeleteRules(entity);
            }

            // 🤖 Infrastructure: Physical deletion
            getRepository().deleteById(id);

            // 🤖 Infrastructure: Event publishing
            eventPublisher.publishDeleted(entity);

            // 👨‍💻 Business: Post-deletion business logic (developer can override)
            handlePostDeletion(entity);

            // 🤖 Infrastructure: Metrics and audit
            metricsCollector.recordDeletion(getEntityClass());
            auditLogger.logOperationSuccess("DELETE", getEntityClass().getSimpleName(), id, null);

            logger.info("✅ Successfully deleted {} with ID: {}", getEntityClass().getSimpleName(), id);

            return true;

        } catch (BusinessValidationException e) {
            metricsCollector.recordValidationError(getEntityClass());
            auditLogger.logValidationError("DELETE", getEntityClass().getSimpleName(), id, e);
            logger.warn("❌ Business validation failed for {} deletion: {}", getEntityClass().getSimpleName(), e.getMessage());
            throw e;
        } catch (Exception e) {
            metricsCollector.recordSystemError(getEntityClass());
            auditLogger.logSystemError("DELETE", getEntityClass().getSimpleName(), id, e);
            logger.error("💥 System error deleting {}: {}", getEntityClass().getSimpleName(), e.getMessage(), e);
            throw new EnterpriseServiceException("Failed to delete " + getEntityClass().getSimpleName(), e);
        } finally {
            metricsCollector.stopDeleteTimer(timer, getEntityClass());
        }
    }

    /**
     * 🤖 List operation with enterprise caching and pagination
     */
    @Transactional(readOnly = true)
    @Cacheable(value = "#{this.getCacheName()}-list", key = "#pageable.pageNumber + '_' + #pageable.pageSize")
    public final Page<ResponseDTO> findAll(Pageable pageable) {
        Timer.Sample timer = metricsCollector.startListTimer(getEntityClass());

        try {
            logger.debug("📋 Fetching {} list with pagination: {}", getEntityClass().getSimpleName(), pageable);

            // 👨‍💻 Business: Entity list retrieval (developer implements)
            Page<T> entities = getRepository().findAll(pageable);

            // 🤖 Infrastructure: Convert to response DTOs
            Page<ResponseDTO> response = entities.map(this::convertToResponse);

            // 🤖 Infrastructure: Metrics
            metricsCollector.recordList(getEntityClass(), entities.getNumberOfElements());

            logger.debug("✅ Found {} {} entities", entities.getNumberOfElements(), getEntityClass().getSimpleName());

            return response;

        } finally {
            metricsCollector.stopListTimer(timer, getEntityClass());
        }
    }

    // ================================
    // 👨‍💻 BUSINESS LOGIC METHODS - IMPLEMENT THESE
    // ================================

    /**
     * 👨‍💻 IMPLEMENT: Create business entity from DTO
     * Focus on business logic only - infrastructure is handled automatically
     */
    protected abstract org.springframework.data.jpa.repository.JpaRepository<T, ID> getRepository();

    /**
     * 👨‍💻 IMPLEMENT: Validate business rules for creation
     * Throw BusinessValidationException for validation failures
     */
    protected abstract T createEntityFromRequest(CreateDTO createDTO);

    /**
     * 👨‍💻 IMPLEMENT: Find entity by ID
     * Use repository or any data access pattern you prefer
     */
    protected abstract void updateEntityFromRequest(UpdateDTO updateDTO, T entity);

    /**
     * 👨‍💻 IMPLEMENT: Validate business rules for update
     * Throw BusinessValidationException for validation failures
     */
    protected abstract ResponseDTO convertToResponse(T entity);

    /**
     * 👨‍💻 IMPLEMENT: Update business entity with DTO data
     * Focus on business logic only
     */
    protected abstract ID extractEntityId(T entity);

    /**
     * 👨‍💻 IMPLEMENT: Validate business rules for deletion
     * Throw BusinessValidationException for validation failures
     */
    // Setter methods for business components

    // Setter methods for business components
    protected void setBusinessValidator(BusinessValidator<T, CreateDTO, UpdateDTO> businessValidator) {
        this.businessValidator = businessValidator;
    }

    protected void setBusinessRules(BusinessRules<T, CreateDTO, UpdateDTO> businessRules) {
        this.businessRules = businessRules;
    }

    /**
     * 👨‍💻 IMPLEMENT: Get entity class for metrics and logging
     */
    protected abstract Class<T> getEntityClass();

    /**
     * 👨‍💻 IMPLEMENT: Get entity ID for auditing
     */

    // ================================
    // 🔧 EXTENSION POINTS - OVERRIDE IF NEEDED
    // ================================

    /**
     * 🔧 OPTIONAL: Override for custom post-creation logic
     */
    protected void handlePostCreation(T entity) {
        // Default: no additional logic
    }

    /**
     * 🔧 OPTIONAL: Override for custom post-update logic
     */
    protected void handlePostUpdate(T previousState, T updatedEntity) {
        // Default: no additional logic
    }

    /**
     * 🔧 OPTIONAL: Override for custom pre-deletion logic
     */
    protected void handlePreDeletion(T entity) {
        // Default: no additional logic
    }

    /**
     * 🔧 OPTIONAL: Override for custom post-deletion logic
     */
    protected void handlePostDeletion(T entity) {
        // Default: no additional logic
    }

    /**
     * 🔧 OPTIONAL: Override for custom cache name
     */
    protected String getCacheName() {
        return getEntityClass().getSimpleName().toLowerCase();
    }

    // ================================
    // 🤖 PRIVATE INFRASTRUCTURE METHODS - DO NOT OVERRIDE
    // ================================

    private void validateFrameworkConstraints(Object dto) {
        // Framework-level validation (annotations, etc.)
        // Implementation depends on validation framework
    }

    private void applyEnterpriseRules(T entity, String operation) {
        // Apply common enterprise rules (auditing fields, etc.)
        // Implementation depends on enterprise requirements
    }

    private T persistEntity(T entity) {
        // Delegate to repository - implementation depends on specific service
        return entity; // Placeholder - implement in concrete classes
    }

    private void deleteEntity(ID id) {
        // Delegate to repository - implementation depends on specific service
    }

    private T cloneEntity(T entity) {
        // Create deep copy for audit purposes
        // Implementation depends on entity structure
        return entity; // Placeholder - implement in concrete classes
    }

    // ================================
    // 🤖 ENTERPRISE EXCEPTIONS
    // ================================

    public static class EnterpriseServiceException extends RuntimeException {
        public EnterpriseServiceException(String message, Throwable cause) {
            super(message, cause);
        }
    }

    public static class BusinessValidationException extends RuntimeException {
        public BusinessValidationException(String message) {
            super(message);
        }
    }
}