package {{packageName}}.enterprise.annotations;

import java.lang.annotation.*;

/**
 * 🤖 ENTERPRISE ANNOTATION - BUSINESS VALIDATION CONFIGURATION
 *
 * Marks a method or class as having business validation with specific configurations.
 * This annotation provides metadata for enterprise infrastructure to automatically
 * handle validation execution, error handling, audit logging, and metrics collection.
 *
 * Usage:
 * @BusinessValidation(
 *     name = "CustomerEmailValidation",
 *     description = "Validates customer email format and uniqueness",
 *     severity = Severity.ERROR
 * )
 *
 * Generated by Enterprise CLI - Infrastructure annotation
 */
@Target({ElementType.METHOD, ElementType.TYPE, ElementType.FIELD})
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Repeatable(BusinessValidations.class)
public @interface BusinessValidation {

    /**
     * Validation rule name
     */
    String name();

    /**
     * Validation description
     */
    String description() default "";

    /**
     * Validation severity level
     */
    Severity severity() default Severity.ERROR;

    /**
     * Validation category for grouping
     */
    String category() default "BUSINESS";

    /**
     * Whether this validation is mandatory
     */
    boolean mandatory() default true;

    /**
     * Whether validation should be audited
     */
    boolean auditEnabled() default true;

    /**
     * Whether validation metrics should be collected
     */
    boolean metricsEnabled() default true;

    /**
     * Operations where this validation applies
     */
    Operation[] operations() default {Operation.CREATE, Operation.UPDATE};

    /**
     * Validation groups
     */
    String[] groups() default {"Default"};

    /**
     * Conditions for validation execution
     */
    String[] conditions() default {};

    /**
     * Custom error message
     */
    String errorMessage() default "";

    /**
     * Error code for validation failure
     */
    String errorCode() default "";

    /**
     * Whether validation failure should stop processing
     */
    boolean failFast() default true;

    /**
     * Validation timeout in milliseconds
     */
    long timeoutMs() default 3000;

    /**
     * Dependencies on other validations
     */
    String[] dependsOn() default {};

    /**
     * Custom validation parameters
     */
    Parameter[] parameters() default {};

    /**
     * Tags for validation classification
     */
    String[] tags() default {};

    enum Severity {
        INFO, WARNING, ERROR, CRITICAL
    }

    enum Operation {
        CREATE, UPDATE, DELETE, READ, ALL
    }

    @interface Parameter {
        String name();
        String value();
        String type() default "String";
    }
}

/**
 * Container annotation for multiple business validations
 */
@Target({ElementType.METHOD, ElementType.TYPE, ElementType.FIELD})
@Retention(RetentionPolicy.RUNTIME)
@Documented
@interface BusinessValidations {
    BusinessValidation[] value();
}