package {{packageName}}.enterprise.annotations;

import org.springframework.context.annotation.Import;

import java.lang.annotation.*;

/**
 * 🤖 ENTERPRISE ANNOTATION - FRAMEWORK ENABLER
 *
 * Enables the Enterprise Framework with all its features.
 * This annotation should be placed on the main application class or configuration class
 * to activate all enterprise infrastructure components.
 *
 * Features enabled:
 * - Enterprise Service infrastructure
 * - Enterprise Controller infrastructure
 * - Enterprise Repository patterns
 * - Business validation framework
 * - Business rules engine
 * - Audit logging
 * - Metrics collection
 * - Event publishing
 * - Caching infrastructure
 * - Transaction management
 *
 * Usage:
 * @SpringBootApplication
 * @EnableEnterpriseFramework
 * public class MyApplication {
 *     public static void main(String[] args) {
 *         SpringApplication.run(MyApplication.class, args);
 *     }
 * }
 *
 * Generated by Enterprise CLI - Infrastructure annotation
 */
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Import(EnterpriseFrameworkConfiguration.class)
public @interface EnableEnterpriseFramework {

    /**
     * Enable enterprise services infrastructure
     */
    boolean enableServices() default true;

    /**
     * Enable enterprise controllers infrastructure
     */
    boolean enableControllers() default true;

    /**
     * Enable enterprise repositories infrastructure
     */
    boolean enableRepositories() default true;

    /**
     * Enable business validation framework
     */
    boolean enableBusinessValidation() default true;

    /**
     * Enable business rules engine
     */
    boolean enableBusinessRules() default true;

    /**
     * Enable audit logging
     */
    boolean enableAuditLogging() default true;

    /**
     * Enable metrics collection
     */
    boolean enableMetrics() default true;

    /**
     * Enable event publishing
     */
    boolean enableEvents() default true;

    /**
     * Enable caching infrastructure
     */
    boolean enableCaching() default true;

    /**
     * Enable transaction management
     */
    boolean enableTransactions() default true;

    /**
     * Package names to scan for enterprise components
     */
    String[] basePackages() default {};

    /**
     * Configuration profiles to activate
     */
    String[] profiles() default {"default"};

    /**
     * Additional enterprise features to enable
     */
    Feature[] features() default {};

    enum Feature {
        CIRCUIT_BREAKER,
        RATE_LIMITING,
        DISTRIBUTED_TRACING,
        HEALTH_CHECKS,
        SECURITY_HEADERS,
        REQUEST_CORRELATION,
        PERFORMANCE_MONITORING,
        BUSINESS_INTELLIGENCE
    }
}