package {{packageName}}.enterprise.annotations;

import java.lang.annotation.*;

/**
 * 🤖 ENTERPRISE ANNOTATION - CONTROLLER CONFIGURATION
 *
 * Marks a controller as an Enterprise controller with specific configurations.
 * This annotation provides metadata for enterprise infrastructure to automatically
 * configure security, validation, error handling, rate limiting, and API documentation.
 *
 * Usage:
 * @EnterpriseController(
 *     domain = "Customer",
 *     apiVersion = "v1",
 *     secured = true
 * )
 *
 * Generated by Enterprise CLI - Infrastructure annotation
 */
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
@Documented
public @interface EnterpriseController {

    /**
     * Domain name that this controller manages
     */
    String domain();

    /**
     * API version for this controller
     */
    String apiVersion() default "v1";

    /**
     * Whether security is enabled for this controller
     */
    boolean secured() default true;

    /**
     * Required security roles
     */
    String[] requiredRoles() default {};

    /**
     * Whether input validation is enabled
     */
    boolean validationEnabled() default true;

    /**
     * Whether request/response logging is enabled
     */
    boolean loggingEnabled() default true;

    /**
     * Logging level for requests
     */
    LoggingLevel loggingLevel() default LoggingLevel.INFO;

    /**
     * Whether rate limiting is enabled
     */
    boolean rateLimitingEnabled() default false;

    /**
     * Rate limiting configuration
     */
    RateLimit rateLimit() default @RateLimit;

    /**
     * Whether CORS is enabled
     */
    boolean corsEnabled() default true;

    /**
     * Allowed CORS origins
     */
    String[] corsOrigins() default {"*"};

    /**
     * API documentation configuration
     */
    ApiDoc apiDoc() default @ApiDoc;

    /**
     * Error handling strategy
     */
    ErrorHandling errorHandling() default ErrorHandling.STANDARD;

    /**
     * Response compression enabled
     */
    boolean compressionEnabled() default true;

    /**
     * Content type restrictions
     */
    String[] allowedContentTypes() default {"application/json", "application/xml"};

    enum LoggingLevel {
        TRACE, DEBUG, INFO, WARN, ERROR
    }

    enum ErrorHandling {
        MINIMAL, STANDARD, DETAILED, COMPREHENSIVE
    }

    @interface RateLimit {
        int requestsPerSecond() default 50;
        int requestsPerMinute() default 3000;
        int requestsPerHour() default 180000;
        String[] exemptIPs() default {};
    }

    @interface ApiDoc {
        String title() default "";
        String description() default "";
        String version() default "1.0";
        boolean enabled() default true;
        String[] tags() default {};
    }
}