package {{packageName}}.enterprise.annotations;

import {{packageName}}.enterprise.patterns.EnterpriseAuditLogger;
import {{packageName}}.enterprise.patterns.EnterpriseEventPublisher;
import {{packageName}}.enterprise.patterns.EnterpriseMetricsCollector;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.micrometer.core.instrument.MeterRegistry;
import io.micrometer.core.instrument.simple.SimpleMeterRegistry;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.cache.CacheManager;
import org.springframework.cache.concurrent.ConcurrentMapCacheManager;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * 🤖 ENTERPRISE CONFIGURATION - FRAMEWORK INFRASTRUCTURE
 *
 * Auto-configuration for Enterprise Framework components.
 * This configuration is automatically imported when @EnableEnterpriseFramework is used.
 *
 * Provides default beans for:
 * - Enterprise audit logging
 * - Enterprise metrics collection
 * - Enterprise event publishing
 * - Enterprise infrastructure components
 *
 * Generated by Enterprise CLI - Infrastructure configuration
 */
@Configuration
public class EnterpriseFrameworkConfiguration {

    /**
     * 🤖 Meter registry for metrics collection
     */
    @Bean
    @ConditionalOnMissingBean
    public MeterRegistry meterRegistry() {
        return new SimpleMeterRegistry();
    }

    /**
     * 🤖 Cache manager for caching support
     */
    @Bean
    @ConditionalOnMissingBean
    public CacheManager cacheManager() {
        return new ConcurrentMapCacheManager("default", "enterprise", "rateLimit");
    }

    /**
     * 🤖 Enterprise audit logger bean
     */
    @Bean
    @ConditionalOnMissingBean
    public EnterpriseAuditLogger enterpriseAuditLogger(ObjectMapper objectMapper) {
        return new EnterpriseAuditLogger(objectMapper);
    }

    /**
     * 🤖 Enterprise metrics collector bean
     */
    @Bean
    @ConditionalOnMissingBean
    public EnterpriseMetricsCollector enterpriseMetricsCollector(MeterRegistry meterRegistry) {
        return new EnterpriseMetricsCollector(meterRegistry);
    }

    /**
     * 🤖 Enterprise event publisher bean
     */
    @Bean
    @ConditionalOnMissingBean
    public EnterpriseEventPublisher enterpriseEventPublisher(ApplicationEventPublisher applicationEventPublisher) {
        return new EnterpriseEventPublisher(applicationEventPublisher);
    }

    /**
     * 🤖 Object mapper for JSON serialization
     */
    @Bean
    @ConditionalOnMissingBean
    public ObjectMapper objectMapper() {
        ObjectMapper mapper = new ObjectMapper();
        mapper.findAndRegisterModules();
        return mapper;
    }

    // ================================
    // 👨‍💻 CUSTOM ENTERPRISE CONFIGURATION
    // ================================

    /**
     * 👨‍💻 Add your custom enterprise configuration beans here
     *
     * Examples:
     * - Custom audit providers
     * - Custom metrics collectors
     * - Custom event handlers
     * - Business intelligence components
     */

    // Example custom configuration:
    /*
    @Bean
    @ConditionalOnMissingBean
    public CustomBusinessIntelligenceService businessIntelligenceService() {
        return new CustomBusinessIntelligenceService();
    }

    @Bean
    @ConditionalOnProperty(name = "enterprise.features.circuit-breaker.enabled", havingValue = "true")
    public CircuitBreakerConfiguration circuitBreakerConfiguration() {
        return new CircuitBreakerConfiguration();
    }
    */
}