package {{packageName}}.enterprise.annotations;

import java.lang.annotation.*;

/**
 * 🤖 ENTERPRISE ANNOTATION - ENTITY CONFIGURATION
 *
 * Marks an entity as an Enterprise entity with specific configurations.
 * This annotation provides metadata for enterprise infrastructure to automatically
 * configure caching, auditing, validation, and other enterprise features.
 *
 * Usage:
 * @EnterpriseEntity(
 *     cacheable = true,
 *     auditEnabled = true,
 *     businessName = "Customer"
 * )
 *
 * Generated by Enterprise CLI - Infrastructure annotation
 */
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
@Documented
public @interface EnterpriseEntity {

    /**
     * Business name for the entity (used in logging, metrics, etc.)
     */
    String businessName() default "";

    /**
     * Whether this entity should be cached
     */
    boolean cacheable() default true;

    /**
     * Cache region name for this entity
     */
    String cacheRegion() default "";

    /**
     * Whether audit logging is enabled for this entity
     */
    boolean auditEnabled() default true;

    /**
     * Whether metrics collection is enabled for this entity
     */
    boolean metricsEnabled() default true;

    /**
     * Whether domain events should be published for this entity
     */
    boolean eventsEnabled() default true;

    /**
     * Business category for classification
     */
    String businessCategory() default "STANDARD";

    /**
     * Security level for this entity
     */
    SecurityLevel securityLevel() default SecurityLevel.NORMAL;

    /**
     * Whether soft delete is enabled for this entity
     */
    boolean softDeleteEnabled() default true;

    /**
     * Whether versioning/optimistic locking is enabled
     */
    boolean versioningEnabled() default true;

    /**
     * Tags for additional metadata
     */
    String[] tags() default {};

    enum SecurityLevel {
        LOW, NORMAL, HIGH, CRITICAL
    }
}