package {{packageName}}.specification;

import {{packageName}}.entity.{{domainTitleCase}};
import org.springframework.data.jpa.domain.Specification;

import jakarta.persistence.criteria.*;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * JPA Specification for {{domainTitleCase}} entity
 *
 * Provides type-safe query building for complex search operations.
 * Generated by Enterprise CLI - customize criteria as needed.
 */
public class {{domainTitleCase}}Specification {

    /**
     * Private constructor to prevent instantiation
     */
    private {{domainTitleCase}}Specification() {
    }

    /**
     * Specification for {{domain}}s with name containing the given text (case-insensitive)
     */
    public static Specification<{{domainTitleCase}}> nameContains(String name) {
        return (root, query, criteriaBuilder) -> {
            if (name == null || name.trim().isEmpty()) {
                return criteriaBuilder.conjunction();
            }
            return criteriaBuilder.like(
                criteriaBuilder.lower(root.get("name")),
                "%" + name.toLowerCase() + "%"
            );
        };
    }

    /**
     * Specification for {{domain}}s with description containing the given text (case-insensitive)
     */
    public static Specification<{{domainTitleCase}}> descriptionContains(String description) {
        return (root, query, criteriaBuilder) -> {
            if (description == null || description.trim().isEmpty()) {
                return criteriaBuilder.conjunction();
            }
            return criteriaBuilder.like(
                criteriaBuilder.lower(root.get("description")),
                "%" + description.toLowerCase() + "%"
            );
        };
    }

    /**
     * Specification for {{domain}}s created after the given date
     */
    public static Specification<{{domainTitleCase}}> createdAfter(LocalDateTime date) {
        return (root, query, criteriaBuilder) -> {
            if (date == null) {
                return criteriaBuilder.conjunction();
            }
            return criteriaBuilder.greaterThan(root.get("createdAt"), date);
        };
    }

    /**
     * Specification for {{domain}}s created before the given date
     */
    public static Specification<{{domainTitleCase}}> createdBefore(LocalDateTime date) {
        return (root, query, criteriaBuilder) -> {
            if (date == null) {
                return criteriaBuilder.conjunction();
            }
            return criteriaBuilder.lessThan(root.get("createdAt"), date);
        };
    }

    /**
     * Specification for {{domain}}s created between two dates
     */
    public static Specification<{{domainTitleCase}}> createdBetween(LocalDateTime startDate, LocalDateTime endDate) {
        return (root, query, criteriaBuilder) -> {
            List<Predicate> predicates = new ArrayList<>();

            if (startDate != null) {
                predicates.add(criteriaBuilder.greaterThanOrEqualTo(root.get("createdAt"), startDate));
            }

            if (endDate != null) {
                predicates.add(criteriaBuilder.lessThanOrEqualTo(root.get("createdAt"), endDate));
            }

            return criteriaBuilder.and(predicates.toArray(new Predicate[0]));
        };
    }

    /**
     * Specification for {{domain}}s updated after the given date
     */
    public static Specification<{{domainTitleCase}}> updatedAfter(LocalDateTime date) {
        return (root, query, criteriaBuilder) -> {
            if (date == null) {
                return criteriaBuilder.conjunction();
            }
            return criteriaBuilder.greaterThan(root.get("updatedAt"), date);
        };
    }

    /**
     * Specification for {{domain}}s that have a description (not null and not empty)
     */
    public static Specification<{{domainTitleCase}}> hasDescription() {
        return (root, query, criteriaBuilder) -> criteriaBuilder.and(
            criteriaBuilder.isNotNull(root.get("description")),
            criteriaBuilder.notEqual(root.get("description"), "")
        );
    }

    /**
     * Specification for {{domain}}s that do not have a description (null or empty)
     */
    public static Specification<{{domainTitleCase}}> hasNoDescription() {
        return (root, query, criteriaBuilder) -> criteriaBuilder.or(
            criteriaBuilder.isNull(root.get("description")),
            criteriaBuilder.equal(root.get("description"), "")
        );
    }

    /**
     * Specification for {{domain}}s with name exactly matching (case-insensitive)
     */
    public static Specification<{{domainTitleCase}}> nameEquals(String name) {
        return (root, query, criteriaBuilder) -> {
            if (name == null) {
                return criteriaBuilder.conjunction();
            }
            return criteriaBuilder.equal(
                criteriaBuilder.lower(root.get("name")),
                name.toLowerCase()
            );
        };
    }

    /**
     * Specification for {{domain}}s with name starting with the given prefix (case-insensitive)
     */
    public static Specification<{{domainTitleCase}}> nameStartsWith(String prefix) {
        return (root, query, criteriaBuilder) -> {
            if (prefix == null || prefix.trim().isEmpty()) {
                return criteriaBuilder.conjunction();
            }
            return criteriaBuilder.like(
                criteriaBuilder.lower(root.get("name")),
                prefix.toLowerCase() + "%"
            );
        };
    }

    /**
     * Specification for {{domain}}s with name ending with the given suffix (case-insensitive)
     */
    public static Specification<{{domainTitleCase}}> nameEndsWith(String suffix) {
        return (root, query, criteriaBuilder) -> {
            if (suffix == null || suffix.trim().isEmpty()) {
                return criteriaBuilder.conjunction();
            }
            return criteriaBuilder.like(
                criteriaBuilder.lower(root.get("name")),
                "%" + suffix.toLowerCase()
            );
        };
    }

    /**
     * Specification for global text search across name and description
     */
    public static Specification<{{domainTitleCase}}> globalSearch(String searchText) {
        return (root, query, criteriaBuilder) -> {
            if (searchText == null || searchText.trim().isEmpty()) {
                return criteriaBuilder.conjunction();
            }

            String searchPattern = "%" + searchText.toLowerCase() + "%";
            return criteriaBuilder.or(
                criteriaBuilder.like(criteriaBuilder.lower(root.get("name")), searchPattern),
                criteriaBuilder.like(criteriaBuilder.lower(root.get("description")), searchPattern)
            );
        };
    }

    /**
     * Specification builder for complex queries
     */
    public static class Builder {
        private Specification<{{domainTitleCase}}> specification = Specification.where(null);

        public Builder withName(String name) {
            if (name != null && !name.trim().isEmpty()) {
                specification = specification.and(nameContains(name));
            }
            return this;
        }

        public Builder withDescription(String description) {
            if (description != null && !description.trim().isEmpty()) {
                specification = specification.and(descriptionContains(description));
            }
            return this;
        }

        public Builder withNameExact(String name) {
            if (name != null && !name.trim().isEmpty()) {
                specification = specification.and(nameEquals(name));
            }
            return this;
        }

        public Builder createdAfter(LocalDateTime date) {
            if (date != null) {
                specification = specification.and({{domainTitleCase}}Specification.createdAfter(date));
            }
            return this;
        }

        public Builder createdBefore(LocalDateTime date) {
            if (date != null) {
                specification = specification.and({{domainTitleCase}}Specification.createdBefore(date));
            }
            return this;
        }

        public Builder createdBetween(LocalDateTime startDate, LocalDateTime endDate) {
            if (startDate != null || endDate != null) {
                specification = specification.and({{domainTitleCase}}Specification.createdBetween(startDate, endDate));
            }
            return this;
        }

        public Builder updatedAfter(LocalDateTime date) {
            if (date != null) {
                specification = specification.and({{domainTitleCase}}Specification.updatedAfter(date));
            }
            return this;
        }

        public Builder withDescription(boolean hasDescription) {
            if (hasDescription) {
                specification = specification.and(hasDescription());
            } else {
                specification = specification.and(hasNoDescription());
            }
            return this;
        }

        public Builder withGlobalSearch(String searchText) {
            if (searchText != null && !searchText.trim().isEmpty()) {
                specification = specification.and(globalSearch(searchText));
            }
            return this;
        }

        public Specification<{{domainTitleCase}}> build() {
            return specification;
        }
    }

    /**
     * Create a new specification builder
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Example of a complex business-specific specification
     * (Customize based on your business requirements)
     */
    public static Specification<{{domainTitleCase}}> active{{domainTitleCase}}sLastWeek() {
        LocalDateTime oneWeekAgo = LocalDateTime.now().minusWeeks(1);
        return builder()
            .withDescription(true)  // Must have description
            .createdAfter(oneWeekAgo)  // Created in last week
            .build();
    }

    /**
     * Search specification with flexible criteria
     */
    public static Specification<{{domainTitleCase}}> search(String name, String description,
                                                          LocalDateTime createdAfter,
                                                          LocalDateTime createdBefore,
                                                          Boolean hasDescription) {
        return builder()
            .withName(name)
            .withDescription(description)
            .createdAfter(createdAfter)
            .createdBefore(createdBefore)
            .withDescription(hasDescription != null ? hasDescription : true)
            .build();
    }
}