package {{packageName}}.entity;

import {{packageName}}.enterprise.annotations.EnterpriseEntity;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;
import java.util.Objects;

/**
 * 👨‍💻 BUSINESS ENTITY - {{domainTitleCase}}
 *
 * JPA Entity for {{domainTitleCase}} with Enterprise infrastructure integration.
 * The @EnterpriseEntity annotation automatically configures:
 * - Caching with default cache region
 * - Audit logging for all operations
 * - Metrics collection
 * - Domain event publishing
 * - Soft delete capability
 * - Optimistic locking
 *
 * Customize fields and relationships according to your business requirements.
 * Generated by Enterprise CLI - Business layer entity
 */
@Entity
@Table(name = "{{domain}}s")
@EnterpriseEntity(
    businessName = "{{domainTitleCase}}",
    cacheable = true,
    cacheRegion = "{{domain}}-cache",
    auditEnabled = true,
    metricsEnabled = true,
    eventsEnabled = true,
    businessCategory = "CORE",
    securityLevel = EnterpriseEntity.SecurityLevel.NORMAL,
    softDeleteEnabled = true,
    versioningEnabled = true,
    tags = {"domain", "{{domain}}", "core-entity"}
)
public class {{domainTitleCase}} {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", nullable = false)
    private String id;

    @NotBlank(message = "{{domainTitleCase}} name is required")
    @Size(min = 2, max = 100, message = "{{domainTitleCase}} name must be between 2 and 100 characters")
    @Column(name = "name", nullable = false, length = 100)
    private String name;

    @Size(max = 500, message = "{{domainTitleCase}} description cannot exceed 500 characters")
    @Column(name = "description", length = 500)
    private String description;

    @NotBlank(message = "Business ID is required")
    @Size(min = 3, max = 50, message = "Business ID must be between 3 and 50 characters")
    @Column(name = "business_id", nullable = false, unique = true, length = 50)
    private String businessId;

    @NotBlank(message = "Status is required")
    @Size(max = 20, message = "Status cannot exceed 20 characters")
    @Column(name = "status", nullable = false, length = 20)
    private String status;

    @Size(max = 100, message = "Display name cannot exceed 100 characters")
    @Column(name = "display_name", length = 100)
    private String displayName;

    @Column(name = "priority")
    private Integer priority;

    @Size(max = 50, message = "Category cannot exceed 50 characters")
    @Column(name = "category", length = 50)
    private String category;

    @Column(name = "business_score")
    private Double businessScore;

    @Column(name = "modification_count")
    private Integer modificationCount = 0;

    @Column(name = "status_changed_at")
    private LocalDateTime statusChangedAt;

    @Column(name = "last_calculated_at")
    private LocalDateTime lastCalculatedAt;

    @Column(name = "last_significant_change")
    private LocalDateTime lastSignificantChange;

    @Column(name = "activated_at")
    private LocalDateTime activatedAt;

    @Column(name = "deactivated_at")
    private LocalDateTime deactivatedAt;

    @Column(name = "archived_at")
    private LocalDateTime archivedAt;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    @Version
    @Column(name = "version")
    private Long version;

    // Default constructor
    public {{domainTitleCase}}() {
    }

    // Constructor with required fields
    public {{domainTitleCase}}(String name, String businessId, String status) {
        this.name = name;
        this.businessId = businessId;
        this.status = status;
    }

    // Constructor with all fields except auto-generated
    public {{domainTitleCase}}(String name, String description, String businessId, String status, String displayName, Integer priority) {
        this.name = name;
        this.description = description;
        this.businessId = businessId;
        this.status = status;
        this.displayName = displayName;
        this.priority = priority;
    }

    // Getters and Setters
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getBusinessId() {
        return businessId;
    }

    public void setBusinessId(String businessId) {
        this.businessId = businessId;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getDisplayName() {
        return displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public Integer getPriority() {
        return priority;
    }

    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public Long getVersion() {
        return version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public Double getBusinessScore() {
        return businessScore;
    }

    public void setBusinessScore(Double businessScore) {
        this.businessScore = businessScore;
    }

    public Integer getModificationCount() {
        return modificationCount;
    }

    public void setModificationCount(Integer modificationCount) {
        this.modificationCount = modificationCount;
    }

    public LocalDateTime getStatusChangedAt() {
        return statusChangedAt;
    }

    public void setStatusChangedAt(LocalDateTime statusChangedAt) {
        this.statusChangedAt = statusChangedAt;
    }

    public LocalDateTime getLastCalculatedAt() {
        return lastCalculatedAt;
    }

    public void setLastCalculatedAt(LocalDateTime lastCalculatedAt) {
        this.lastCalculatedAt = lastCalculatedAt;
    }

    public LocalDateTime getLastSignificantChange() {
        return lastSignificantChange;
    }

    public void setLastSignificantChange(LocalDateTime lastSignificantChange) {
        this.lastSignificantChange = lastSignificantChange;
    }

    public LocalDateTime getActivatedAt() {
        return activatedAt;
    }

    public void setActivatedAt(LocalDateTime activatedAt) {
        this.activatedAt = activatedAt;
    }

    public LocalDateTime getDeactivatedAt() {
        return deactivatedAt;
    }

    public void setDeactivatedAt(LocalDateTime deactivatedAt) {
        this.deactivatedAt = deactivatedAt;
    }

    public LocalDateTime getArchivedAt() {
        return archivedAt;
    }

    public void setArchivedAt(LocalDateTime archivedAt) {
        this.archivedAt = archivedAt;
    }

    // equals and hashCode
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        {{domainTitleCase}} {{domain}} = ({{domainTitleCase}}) o;
        return Objects.equals(id, {{domain}}.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }

    @Override
    public String toString() {
        return "{{domainTitleCase}}{" +
                "id='" + id + '\'' +
                ", name='" + name + '\'' +
                ", description='" + description + '\'' +
                ", businessId='" + businessId + '\'' +
                ", status='" + status + '\'' +
                ", displayName='" + displayName + '\'' +
                ", priority=" + priority +
                ", category='" + category + '\'' +
                ", businessScore=" + businessScore +
                ", modificationCount=" + modificationCount +
                ", statusChangedAt=" + statusChangedAt +
                ", lastCalculatedAt=" + lastCalculatedAt +
                ", lastSignificantChange=" + lastSignificantChange +
                ", activatedAt=" + activatedAt +
                ", deactivatedAt=" + deactivatedAt +
                ", archivedAt=" + archivedAt +
                ", createdAt=" + createdAt +
                ", updatedAt=" + updatedAt +
                ", version=" + version +
                '}';
    }
}