package {{packageName}}.controller;

import {{packageName}}.service.BatchProcessingService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * REST Controller for Batch Processing operations
 *
 * This controller provides endpoints for managing batch jobs including:
 * - Starting batch processing jobs
 * - Monitoring job progress
 * - Getting job status and results
 * - Cancelling running jobs
 *
 * Generated by Enterprise CLI - customize batch operations as needed.
 */
@RestController
@RequestMapping("/batch")
@Tag(name = "Batch Processing", description = "Batch job management and execution")
public class BatchController {

    private static final Logger logger = LoggerFactory.getLogger(BatchController.class);

    private final BatchProcessingService batchProcessingService;

    @Autowired
    public BatchController(BatchProcessingService batchProcessingService) {
        this.batchProcessingService = batchProcessingService;
    }

    /**
     * Start batch processing of all {{domain}}s
     */
    @PostMapping("/process-all")
    @Operation(summary = "Process all {{domain}}s", description = "Start batch processing of all {{domain}}s with custom logic")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "202", description = "Batch job started successfully"),
            @ApiResponse(responseCode = "400", description = "Invalid parameters"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
    })
    public ResponseEntity<Map<String, Object>> processAll{{domainTitleCase}}s(
            @Parameter(description = "Chunk size for batch processing")
            @RequestParam(defaultValue = "100") int chunkSize) {

        try {
            logger.info("Starting batch processing of all {{domain}}s with chunk size: {}", chunkSize);

            // Example processor - customize this logic
            java.util.function.Function<{{packageName}}.entity.{{domainTitleCase}}, {{packageName}}.entity.{{domainTitleCase}}> processor = (entity) -> {
                // Add your custom processing logic here
                // Example: entity.setLastProcessed(LocalDateTime.now());
                return entity;
            };

            var futureResult = batchProcessingService.processAll{{domainTitleCase}}s(processor, chunkSize);

            Map<String, Object> response = Map.of(
                "message", "Batch processing started",
                "chunkSize", chunkSize,
                "status", "ACCEPTED"
            );

            return ResponseEntity.status(HttpStatus.ACCEPTED).body(response);

        } catch (Exception e) {
            logger.error("Failed to start batch processing: {}", e.getMessage(), e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body(Map.of("error", "Failed to start batch processing: " + e.getMessage()));
        }
    }

    /**
     * Start batch processing by date range
     */
    @PostMapping("/process-by-date")
    @Operation(summary = "Process {{domain}}s by date range", description = "Start batch processing of {{domain}}s within a specific date range")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "202", description = "Batch job started successfully"),
            @ApiResponse(responseCode = "400", description = "Invalid parameters"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
    })
    public ResponseEntity<Map<String, Object>> process{{domainTitleCase}}sByDateRange(
            @Parameter(description = "Start date (yyyy-MM-dd'T'HH:mm:ss)")
            @RequestParam @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) LocalDateTime startDate,
            @Parameter(description = "End date (yyyy-MM-dd'T'HH:mm:ss)")
            @RequestParam @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) LocalDateTime endDate,
            @Parameter(description = "Chunk size for batch processing")
            @RequestParam(defaultValue = "100") int chunkSize) {

        try {
            logger.info("Starting batch processing by date range: {} to {}", startDate, endDate);

            // Example processor - customize this logic
            java.util.function.Function<{{packageName}}.entity.{{domainTitleCase}}, {{packageName}}.entity.{{domainTitleCase}}> processor = (entity) -> {
                // Add your custom processing logic here
                return entity;
            };

            var futureResult = batchProcessingService.process{{domainTitleCase}}sByDateRange(
                startDate, endDate, processor, chunkSize);

            Map<String, Object> response = Map.of(
                "message", "Batch processing by date range started",
                "startDate", startDate.toString(),
                "endDate", endDate.toString(),
                "chunkSize", chunkSize,
                "status", "ACCEPTED"
            );

            return ResponseEntity.status(HttpStatus.ACCEPTED).body(response);

        } catch (Exception e) {
            logger.error("Failed to start batch processing by date range: {}", e.getMessage(), e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body(Map.of("error", "Failed to start batch processing: " + e.getMessage()));
        }
    }

    /**
     * Start bulk update of {{domain}}s
     */
    @PostMapping("/bulk-update")
    @Operation(summary = "Bulk update {{domain}}s", description = "Start bulk update of specific {{domain}}s")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "202", description = "Batch job started successfully"),
            @ApiResponse(responseCode = "400", description = "Invalid parameters"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
    })
    public ResponseEntity<Map<String, Object>> bulkUpdate{{domainTitleCase}}s(
            @Parameter(description = "List of entity IDs to update")
            @RequestBody List<String> entityIds,
            @Parameter(description = "Chunk size for batch processing")
            @RequestParam(defaultValue = "50") int chunkSize) {

        try {
            if (entityIds == null || entityIds.isEmpty()) {
                return ResponseEntity.badRequest()
                        .body(Map.of("error", "Entity IDs list cannot be empty"));
            }

            logger.info("Starting bulk update of {} {{domain}}s", entityIds.size());

            // Example updater - customize this logic
            java.util.function.Function<{{packageName}}.entity.{{domainTitleCase}}, {{packageName}}.entity.{{domainTitleCase}}> updater = (entity) -> {
                // Add your custom update logic here
                // Example: entity.setLastUpdated(LocalDateTime.now());
                return entity;
            };

            var futureResult = batchProcessingService.bulkUpdate{{domainTitleCase}}s(entityIds, updater, chunkSize);

            Map<String, Object> response = Map.of(
                "message", "Bulk update started",
                "entityCount", entityIds.size(),
                "chunkSize", chunkSize,
                "status", "ACCEPTED"
            );

            return ResponseEntity.status(HttpStatus.ACCEPTED).body(response);

        } catch (Exception e) {
            logger.error("Failed to start bulk update: {}", e.getMessage(), e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body(Map.of("error", "Failed to start bulk update: " + e.getMessage()));
        }
    }

    /**
     * Start data migration
     */
    @PostMapping("/migrate-data")
    @Operation(summary = "Start data migration", description = "Start data migration batch job")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "202", description = "Migration job started successfully"),
            @ApiResponse(responseCode = "400", description = "Invalid parameters"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
    })
    public ResponseEntity<Map<String, Object>> migrateData(
            @Parameter(description = "Chunk size for batch processing")
            @RequestParam(defaultValue = "100") int chunkSize) {

        try {
            logger.info("Starting data migration with chunk size: {}", chunkSize);

            // Example migrator - customize this logic
            java.util.function.Function<{{packageName}}.entity.{{domainTitleCase}}, {{packageName}}.entity.{{domainTitleCase}}> migrator = (entity) -> {
                // Add your custom migration logic here
                // Example: Convert old data format to new format
                return entity;
            };

            var futureResult = batchProcessingService.migrateData(migrator, chunkSize);

            Map<String, Object> response = Map.of(
                "message", "Data migration started",
                "chunkSize", chunkSize,
                "status", "ACCEPTED"
            );

            return ResponseEntity.status(HttpStatus.ACCEPTED).body(response);

        } catch (Exception e) {
            logger.error("Failed to start data migration: {}", e.getMessage(), e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body(Map.of("error", "Failed to start data migration: " + e.getMessage()));
        }
    }

    /**
     * Get job status
     */
    @GetMapping("/jobs/{jobId}")
    @Operation(summary = "Get job status", description = "Get the status and progress of a specific batch job")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Job status retrieved successfully"),
            @ApiResponse(responseCode = "404", description = "Job not found"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
    })
    public ResponseEntity<BatchProcessingService.BatchJobStatus> getJobStatus(
            @Parameter(description = "Job ID")
            @PathVariable String jobId) {

        try {
            BatchProcessingService.BatchJobStatus status = batchProcessingService.getJobStatus(jobId);

            if (status == null) {
                return ResponseEntity.notFound().build();
            }

            return ResponseEntity.ok(status);

        } catch (Exception e) {
            logger.error("Failed to get job status for {}: {}", jobId, e.getMessage(), e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
        }
    }

    /**
     * Get all jobs
     */
    @GetMapping("/jobs")
    @Operation(summary = "Get all jobs", description = "Get status of all batch jobs")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Jobs retrieved successfully"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
    })
    public ResponseEntity<ConcurrentHashMap<String, BatchProcessingService.BatchJobStatus>> getAllJobs() {

        try {
            ConcurrentHashMap<String, BatchProcessingService.BatchJobStatus> jobs =
                batchProcessingService.getAllJobs();
            return ResponseEntity.ok(jobs);

        } catch (Exception e) {
            logger.error("Failed to get all jobs: {}", e.getMessage(), e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
        }
    }

    /**
     * Cancel a job
     */
    @PostMapping("/jobs/{jobId}/cancel")
    @Operation(summary = "Cancel job", description = "Cancel a running batch job")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Job cancelled successfully"),
            @ApiResponse(responseCode = "400", description = "Job cannot be cancelled"),
            @ApiResponse(responseCode = "404", description = "Job not found"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
    })
    public ResponseEntity<Map<String, Object>> cancelJob(
            @Parameter(description = "Job ID")
            @PathVariable String jobId) {

        try {
            boolean cancelled = batchProcessingService.cancelJob(jobId);

            if (cancelled) {
                logger.info("Job cancelled: {}", jobId);
                return ResponseEntity.ok(Map.of(
                    "message", "Job cancelled successfully",
                    "jobId", jobId
                ));
            } else {
                return ResponseEntity.badRequest().body(Map.of(
                    "error", "Job cannot be cancelled or does not exist",
                    "jobId", jobId
                ));
            }

        } catch (Exception e) {
            logger.error("Failed to cancel job {}: {}", jobId, e.getMessage(), e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body(Map.of("error", "Failed to cancel job: " + e.getMessage()));
        }
    }

    /**
     * Get batch processing statistics
     */
    @GetMapping("/stats")
    @Operation(summary = "Get batch statistics", description = "Get overall batch processing statistics")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Statistics retrieved successfully"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
    })
    public ResponseEntity<Map<String, Object>> getBatchStatistics() {

        try {
            ConcurrentHashMap<String, BatchProcessingService.BatchJobStatus> allJobs =
                batchProcessingService.getAllJobs();

            long totalJobs = allJobs.size();
            long runningJobs = allJobs.values().stream()
                .mapToLong(job -> job.getStatus() == BatchProcessingService.BatchJobStatus.Status.RUNNING ? 1 : 0)
                .sum();
            long completedJobs = allJobs.values().stream()
                .mapToLong(job -> job.getStatus() == BatchProcessingService.BatchJobStatus.Status.COMPLETED ? 1 : 0)
                .sum();
            long failedJobs = allJobs.values().stream()
                .mapToLong(job -> job.getStatus() == BatchProcessingService.BatchJobStatus.Status.FAILED ? 1 : 0)
                .sum();

            Map<String, Object> stats = Map.of(
                "totalJobs", totalJobs,
                "runningJobs", runningJobs,
                "completedJobs", completedJobs,
                "failedJobs", failedJobs,
                "successRate", totalJobs > 0 ? (double) completedJobs / totalJobs * 100 : 0
            );

            return ResponseEntity.ok(stats);

        } catch (Exception e) {
            logger.error("Failed to get batch statistics: {}", e.getMessage(), e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body(Map.of("error", "Failed to get statistics: " + e.getMessage()));
        }
    }
}