package {{packageName}}.controller;

import {{packageName}}.service.DataExportService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.io.ByteArrayResource;
import org.springframework.core.io.Resource;
import org.springframework.data.domain.Pageable;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDateTime;
import java.util.Map;

/**
 * REST Controller for Data Export operations
 *
 * This controller provides endpoints for exporting {{domainTitleCase}} data in various formats:
 * - CSV export for spreadsheet applications
 * - JSON export for API integrations
 * - XML export for legacy systems
 * - Filtered and paginated exports for large datasets
 *
 * Generated by Enterprise CLI - customize export endpoints as needed.
 */
@RestController
@RequestMapping("/export")
@Tag(name = "Data Export", description = "Data export operations in various formats")
public class ExportController {

    private static final Logger logger = LoggerFactory.getLogger(ExportController.class);

    private final DataExportService dataExportService;

    @Autowired
    public ExportController(DataExportService dataExportService) {
        this.dataExportService = dataExportService;
    }

    /**
     * Export all {{domain}}s to CSV
     */
    @GetMapping("/{{domain}}s/csv")
    @Operation(summary = "Export all {{domain}}s to CSV", description = "Export all {{domain}}s in CSV format")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "CSV file generated successfully"),
            @ApiResponse(responseCode = "500", description = "Export failed")
    })
    public ResponseEntity<Resource> exportAll{{domainTitleCase}}sToCSV() {
        try {
            logger.info("Exporting all {{domain}}s to CSV");
            DataExportService.ExportResult result = dataExportService.exportAll{{domainTitleCase}}sToCSV();

            ByteArrayResource resource = new ByteArrayResource(result.getData());

            logger.info("CSV export completed: {} records, {} bytes", result.getRecordCount(), result.getDataSize());

            return ResponseEntity.ok()
                    .header(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=\"" + result.getFilename() + "\"")
                    .contentType(MediaType.parseMediaType(result.getContentType()))
                    .contentLength(result.getDataSize())
                    .body(resource);

        } catch (Exception e) {
            logger.error("Failed to export {{domain}}s to CSV", e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
        }
    }

    /**
     * Export {{domain}}s to CSV with pagination
     */
    @GetMapping("/{{domain}}s/csv/paged")
    @Operation(summary = "Export {{domain}}s to CSV (paged)", description = "Export {{domain}}s in CSV format with pagination")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "CSV file generated successfully"),
            @ApiResponse(responseCode = "500", description = "Export failed")
    })
    public ResponseEntity<Resource> export{{domainTitleCase}}sToCSVPaged(Pageable pageable) {
        try {
            logger.info("Exporting {{domain}}s to CSV (paged): {}", pageable);
            DataExportService.ExportResult result = dataExportService.export{{domainTitleCase}}sToCSVPaged(pageable);

            ByteArrayResource resource = new ByteArrayResource(result.getData());

            return ResponseEntity.ok()
                    .header(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=\"" + result.getFilename() + "\"")
                    .contentType(MediaType.parseMediaType(result.getContentType()))
                    .contentLength(result.getDataSize())
                    .body(resource);

        } catch (Exception e) {
            logger.error("Failed to export {{domain}}s to CSV (paged)", e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
        }
    }

    /**
     * Export {{domain}}s by date range to CSV
     */
    @GetMapping("/{{domain}}s/csv/date-range")
    @Operation(summary = "Export {{domain}}s by date range to CSV", description = "Export {{domain}}s created within a specific date range to CSV")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "CSV file generated successfully"),
            @ApiResponse(responseCode = "400", description = "Invalid date parameters"),
            @ApiResponse(responseCode = "500", description = "Export failed")
    })
    public ResponseEntity<Resource> export{{domainTitleCase}}sByDateRangeToCSV(
            @Parameter(description = "Start date (yyyy-MM-dd'T'HH:mm:ss)")
            @RequestParam @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) LocalDateTime startDate,
            @Parameter(description = "End date (yyyy-MM-dd'T'HH:mm:ss)")
            @RequestParam @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) LocalDateTime endDate) {

        try {
            if (startDate.isAfter(endDate)) {
                return ResponseEntity.badRequest().build();
            }

            logger.info("Exporting {{domain}}s by date range to CSV: {} to {}", startDate, endDate);
            DataExportService.ExportResult result = dataExportService.export{{domainTitleCase}}sByDateRangeToCSV(startDate, endDate);

            ByteArrayResource resource = new ByteArrayResource(result.getData());

            return ResponseEntity.ok()
                    .header(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=\"" + result.getFilename() + "\"")
                    .contentType(MediaType.parseMediaType(result.getContentType()))
                    .contentLength(result.getDataSize())
                    .body(resource);

        } catch (Exception e) {
            logger.error("Failed to export {{domain}}s by date range to CSV", e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
        }
    }

    /**
     * Export all {{domain}}s to JSON
     */
    @GetMapping("/{{domain}}s/json")
    @Operation(summary = "Export all {{domain}}s to JSON", description = "Export all {{domain}}s in JSON format")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "JSON file generated successfully"),
            @ApiResponse(responseCode = "500", description = "Export failed")
    })
    public ResponseEntity<Resource> exportAll{{domainTitleCase}}sToJSON() {
        try {
            logger.info("Exporting all {{domain}}s to JSON");
            DataExportService.ExportResult result = dataExportService.exportAll{{domainTitleCase}}sToJSON();

            ByteArrayResource resource = new ByteArrayResource(result.getData());

            return ResponseEntity.ok()
                    .header(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=\"" + result.getFilename() + "\"")
                    .contentType(MediaType.parseMediaType(result.getContentType()))
                    .contentLength(result.getDataSize())
                    .body(resource);

        } catch (Exception e) {
            logger.error("Failed to export {{domain}}s to JSON", e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
        }
    }

    /**
     * Export {{domain}}s to JSON with pagination
     */
    @GetMapping("/{{domain}}s/json/paged")
    @Operation(summary = "Export {{domain}}s to JSON (paged)", description = "Export {{domain}}s in JSON format with pagination")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "JSON file generated successfully"),
            @ApiResponse(responseCode = "500", description = "Export failed")
    })
    public ResponseEntity<Resource> export{{domainTitleCase}}sToJSONPaged(Pageable pageable) {
        try {
            logger.info("Exporting {{domain}}s to JSON (paged): {}", pageable);
            DataExportService.ExportResult result = dataExportService.export{{domainTitleCase}}sToJSONPaged(pageable);

            ByteArrayResource resource = new ByteArrayResource(result.getData());

            return ResponseEntity.ok()
                    .header(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=\"" + result.getFilename() + "\"")
                    .contentType(MediaType.parseMediaType(result.getContentType()))
                    .contentLength(result.getDataSize())
                    .body(resource);

        } catch (Exception e) {
            logger.error("Failed to export {{domain}}s to JSON (paged)", e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
        }
    }

    /**
     * Export all {{domain}}s to XML
     */
    @GetMapping("/{{domain}}s/xml")
    @Operation(summary = "Export all {{domain}}s to XML", description = "Export all {{domain}}s in XML format")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "XML file generated successfully"),
            @ApiResponse(responseCode = "500", description = "Export failed")
    })
    public ResponseEntity<Resource> exportAll{{domainTitleCase}}sToXML() {
        try {
            logger.info("Exporting all {{domain}}s to XML");
            DataExportService.ExportResult result = dataExportService.exportAll{{domainTitleCase}}sToXML();

            ByteArrayResource resource = new ByteArrayResource(result.getData());

            return ResponseEntity.ok()
                    .header(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=\"" + result.getFilename() + "\"")
                    .contentType(MediaType.parseMediaType(result.getContentType()))
                    .contentLength(result.getDataSize())
                    .body(resource);

        } catch (Exception e) {
            logger.error("Failed to export {{domain}}s to XML", e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
        }
    }

    /**
     * Export search results to CSV
     */
    @GetMapping("/{{domain}}s/search/csv")
    @Operation(summary = "Export search results to CSV", description = "Export {{domain}}s matching search criteria to CSV")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "CSV file generated successfully"),
            @ApiResponse(responseCode = "400", description = "Invalid search parameters"),
            @ApiResponse(responseCode = "500", description = "Export failed")
    })
    public ResponseEntity<Resource> exportSearchResultsToCSV(
            @Parameter(description = "Search text")
            @RequestParam String searchText) {

        try {
            if (searchText == null || searchText.trim().isEmpty()) {
                return ResponseEntity.badRequest().build();
            }

            logger.info("Exporting search results to CSV for: {}", searchText);
            DataExportService.ExportResult result = dataExportService.exportSearchResultsToCSV(searchText);

            ByteArrayResource resource = new ByteArrayResource(result.getData());

            return ResponseEntity.ok()
                    .header(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=\"" + result.getFilename() + "\"")
                    .contentType(MediaType.parseMediaType(result.getContentType()))
                    .contentLength(result.getDataSize())
                    .body(resource);

        } catch (Exception e) {
            logger.error("Failed to export search results to CSV", e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
        }
    }

    /**
     * Export filtered data
     */
    @PostMapping("/{{domain}}s/filtered")
    @Operation(summary = "Export filtered data", description = "Export {{domain}}s with custom filtering and format selection")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "File generated successfully"),
            @ApiResponse(responseCode = "400", description = "Invalid filter parameters"),
            @ApiResponse(responseCode = "500", description = "Export failed")
    })
    public ResponseEntity<Resource> exportFilteredData(
            @RequestBody DataExportService.ExportFilter filter) {

        try {
            logger.info("Exporting filtered data with format: {}", filter.getFormat());
            DataExportService.ExportResult result = dataExportService.exportFilteredData(filter);

            ByteArrayResource resource = new ByteArrayResource(result.getData());

            return ResponseEntity.ok()
                    .header(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=\"" + result.getFilename() + "\"")
                    .contentType(MediaType.parseMediaType(result.getContentType()))
                    .contentLength(result.getDataSize())
                    .body(resource);

        } catch (IllegalArgumentException e) {
            logger.warn("Invalid export filter: {}", e.getMessage());
            return ResponseEntity.badRequest().build();
        } catch (Exception e) {
            logger.error("Failed to export filtered data", e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
        }
    }

    /**
     * Get export formats and statistics
     */
    @GetMapping("/info")
    @Operation(summary = "Get export information", description = "Get available export formats and statistics")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Export information retrieved successfully"),
            @ApiResponse(responseCode = "500", description = "Failed to get export information")
    })
    public ResponseEntity<Map<String, Object>> getExportInfo() {
        try {
            Map<String, Object> info = Map.of(
                "supportedFormats", new String[]{"CSV", "JSON", "XML"},
                "features", Map.of(
                    "pagination", true,
                    "dateRangeFiltering", true,
                    "searchFiltering", true,
                    "customFiltering", true,
                    "streamingSupport", true
                ),
                "limits", Map.of(
                    "maxRecordsPerExport", 100000,
                    "maxFileSizeMB", 100,
                    "supportedEncodings", new String[]{"UTF-8"}
                )
            );

            return ResponseEntity.ok(info);

        } catch (Exception e) {
            logger.error("Failed to get export information", e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
        }
    }

    /**
     * Preview export data (first 10 records)
     */
    @PostMapping("/{{domain}}s/preview")
    @Operation(summary = "Preview export data", description = "Preview first 10 records of filtered export data in JSON format")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Preview generated successfully"),
            @ApiResponse(responseCode = "400", description = "Invalid filter parameters"),
            @ApiResponse(responseCode = "500", description = "Preview failed")
    })
    public ResponseEntity<Resource> previewExportData(
            @RequestBody DataExportService.ExportFilter filter) {

        try {
            logger.info("Generating export preview");

            // Limit preview to 10 records
            DataExportService.ExportFilter previewFilter = new DataExportService.ExportFilter("JSON");
            previewFilter.setStartDate(filter.getStartDate());
            previewFilter.setEndDate(filter.getEndDate());
            previewFilter.setSearchText(filter.getSearchText());
            previewFilter.setMaxRecords(10);

            DataExportService.ExportResult result = dataExportService.exportFilteredData(previewFilter);

            ByteArrayResource resource = new ByteArrayResource(result.getData());

            return ResponseEntity.ok()
                    .contentType(MediaType.APPLICATION_JSON)
                    .contentLength(result.getDataSize())
                    .body(resource);

        } catch (Exception e) {
            logger.error("Failed to generate export preview", e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
        }
    }
}