package {{packageName}}.controller;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.core.io.ByteArrayResource;
import org.springframework.core.io.Resource;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;

/**
 * REST Controller for File Upload/Download operations
 *
 * This controller provides secure file upload and download functionality.
 * Includes validation, size limits, and metadata management.
 * Generated by Enterprise CLI - customize storage location and validation rules.
 */
@RestController
@RequestMapping("/files")
@Tag(name = "File Management", description = "File upload and download operations")
public class FileController {

    private static final Logger logger = LoggerFactory.getLogger(FileController.class);

    // Configuration - customize these values
    private static final long MAX_FILE_SIZE = 10 * 1024 * 1024; // 10MB
    private static final Set<String> ALLOWED_EXTENSIONS = Set.of(
        "pdf", "doc", "docx", "xls", "xlsx", "png", "jpg", "jpeg", "gif", "txt", "csv"
    );
    private static final String UPLOAD_DIR = System.getProperty("java.io.tmpdir") + "/{{serviceName}}-uploads/";

    /**
     * Upload a file
     */
    @PostMapping(value = "/upload", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
    @Operation(summary = "Upload file", description = "Upload a file with validation and metadata")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "201", description = "File uploaded successfully"),
            @ApiResponse(responseCode = "400", description = "Invalid file or validation failed"),
            @ApiResponse(responseCode = "413", description = "File too large"),
            @ApiResponse(responseCode = "415", description = "Unsupported file type"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
    })
    public ResponseEntity<Map<String, Object>> uploadFile(
            @Parameter(description = "File to upload")
            @RequestParam("file") MultipartFile file,
            @Parameter(description = "Optional description")
            @RequestParam(value = "description", required = false) String description) {

        try {
            // Validate file
            Map<String, String> validationResult = validateFile(file);
            if (!validationResult.isEmpty()) {
                logger.warn("File validation failed: {}", validationResult);
                return ResponseEntity.badRequest().body(Map.of("errors", validationResult));
            }

            // Create upload directory if it doesn't exist
            Path uploadPath = Paths.get(UPLOAD_DIR);
            if (!Files.exists(uploadPath)) {
                Files.createDirectories(uploadPath);
            }

            // Generate unique filename
            String originalFilename = file.getOriginalFilename();
            String fileExtension = getFileExtension(originalFilename);
            String uniqueFilename = generateUniqueFilename(originalFilename, fileExtension);
            Path filePath = uploadPath.resolve(uniqueFilename);

            // Save file
            Files.copy(file.getInputStream(), filePath, StandardCopyOption.REPLACE_EXISTING);

            // Create response with file metadata
            Map<String, Object> response = new HashMap<>();
            response.put("id", UUID.randomUUID().toString());
            response.put("filename", uniqueFilename);
            response.put("originalFilename", originalFilename);
            response.put("size", file.getSize());
            response.put("contentType", file.getContentType());
            response.put("description", description);
            response.put("uploadedAt", LocalDateTime.now().format(DateTimeFormatter.ISO_LOCAL_DATE_TIME));
            response.put("path", filePath.toString());

            logger.info("File uploaded successfully: {} ({})", uniqueFilename, file.getSize());
            return ResponseEntity.status(HttpStatus.CREATED).body(response);

        } catch (IOException e) {
            logger.error("Failed to upload file: {}", e.getMessage(), e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body(Map.of("error", "Failed to upload file"));
        }
    }

    /**
     * Upload multiple files
     */
    @PostMapping(value = "/upload/batch", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
    @Operation(summary = "Upload multiple files", description = "Upload multiple files in a single request")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "201", description = "Files uploaded successfully"),
            @ApiResponse(responseCode = "400", description = "Invalid files or validation failed"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
    })
    public ResponseEntity<Map<String, Object>> uploadFiles(
            @Parameter(description = "Files to upload")
            @RequestParam("files") MultipartFile[] files,
            @Parameter(description = "Optional description")
            @RequestParam(value = "description", required = false) String description) {

        List<Map<String, Object>> uploadedFiles = new ArrayList<>();
        List<Map<String, String>> errors = new ArrayList<>();

        for (MultipartFile file : files) {
            try {
                ResponseEntity<Map<String, Object>> result = uploadFile(file, description);
                if (result.getStatusCode() == HttpStatus.CREATED) {
                    uploadedFiles.add(result.getBody());
                } else {
                    errors.add(Map.of(
                        "filename", file.getOriginalFilename(),
                        "error", result.getBody().toString()
                    ));
                }
            } catch (Exception e) {
                errors.add(Map.of(
                    "filename", file.getOriginalFilename(),
                    "error", e.getMessage()
                ));
            }
        }

        Map<String, Object> response = new HashMap<>();
        response.put("uploadedFiles", uploadedFiles);
        response.put("errors", errors);
        response.put("totalUploaded", uploadedFiles.size());
        response.put("totalErrors", errors.size());

        HttpStatus status = errors.isEmpty() ? HttpStatus.CREATED : HttpStatus.PARTIAL_CONTENT;
        return ResponseEntity.status(status).body(response);
    }

    /**
     * Download a file
     */
    @GetMapping("/download/{filename}")
    @Operation(summary = "Download file", description = "Download a file by filename")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "File downloaded successfully"),
            @ApiResponse(responseCode = "404", description = "File not found"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
    })
    public ResponseEntity<Resource> downloadFile(
            @Parameter(description = "Name of file to download")
            @PathVariable String filename) {

        try {
            Path filePath = Paths.get(UPLOAD_DIR).resolve(filename);

            if (!Files.exists(filePath)) {
                logger.warn("File not found: {}", filename);
                return ResponseEntity.notFound().build();
            }

            // Security check - ensure file is within upload directory
            if (!filePath.startsWith(Paths.get(UPLOAD_DIR))) {
                logger.warn("Security violation: Attempted to access file outside upload directory: {}", filename);
                return ResponseEntity.status(HttpStatus.FORBIDDEN).build();
            }

            byte[] fileContent = Files.readAllBytes(filePath);
            ByteArrayResource resource = new ByteArrayResource(fileContent);

            String contentType = Files.probeContentType(filePath);
            if (contentType == null) {
                contentType = "application/octet-stream";
            }

            logger.info("File downloaded: {} ({})", filename, fileContent.length);

            return ResponseEntity.ok()
                    .contentType(MediaType.parseMediaType(contentType))
                    .header(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=\"" + filename + "\"")
                    .contentLength(fileContent.length)
                    .body(resource);

        } catch (IOException e) {
            logger.error("Failed to download file {}: {}", filename, e.getMessage(), e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
        }
    }

    /**
     * Get file information
     */
    @GetMapping("/info/{filename}")
    @Operation(summary = "Get file information", description = "Get metadata for a specific file")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "File information retrieved"),
            @ApiResponse(responseCode = "404", description = "File not found"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
    })
    public ResponseEntity<Map<String, Object>> getFileInfo(
            @Parameter(description = "Name of file")
            @PathVariable String filename) {

        try {
            Path filePath = Paths.get(UPLOAD_DIR).resolve(filename);

            if (!Files.exists(filePath)) {
                return ResponseEntity.notFound().build();
            }

            Map<String, Object> fileInfo = new HashMap<>();
            fileInfo.put("filename", filename);
            fileInfo.put("size", Files.size(filePath));
            fileInfo.put("contentType", Files.probeContentType(filePath));
            fileInfo.put("lastModified", Files.getLastModifiedTime(filePath).toString());
            fileInfo.put("isReadable", Files.isReadable(filePath));

            return ResponseEntity.ok(fileInfo);

        } catch (IOException e) {
            logger.error("Failed to get file info for {}: {}", filename, e.getMessage(), e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
        }
    }

    /**
     * List all uploaded files
     */
    @GetMapping("/list")
    @Operation(summary = "List files", description = "Get list of all uploaded files")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "File list retrieved"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
    })
    public ResponseEntity<List<Map<String, Object>>> listFiles() {
        try {
            Path uploadPath = Paths.get(UPLOAD_DIR);
            if (!Files.exists(uploadPath)) {
                return ResponseEntity.ok(new ArrayList<>());
            }

            List<Map<String, Object>> files = new ArrayList<>();
            Files.list(uploadPath)
                    .filter(Files::isRegularFile)
                    .forEach(filePath -> {
                        try {
                            Map<String, Object> fileInfo = new HashMap<>();
                            fileInfo.put("filename", filePath.getFileName().toString());
                            fileInfo.put("size", Files.size(filePath));
                            fileInfo.put("contentType", Files.probeContentType(filePath));
                            fileInfo.put("lastModified", Files.getLastModifiedTime(filePath).toString());
                            files.add(fileInfo);
                        } catch (IOException e) {
                            logger.warn("Failed to get info for file: {}", filePath, e);
                        }
                    });

            return ResponseEntity.ok(files);

        } catch (IOException e) {
            logger.error("Failed to list files: {}", e.getMessage(), e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
        }
    }

    /**
     * Delete a file
     */
    @DeleteMapping("/{filename}")
    @Operation(summary = "Delete file", description = "Delete a file by filename")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "204", description = "File deleted successfully"),
            @ApiResponse(responseCode = "404", description = "File not found"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
    })
    public ResponseEntity<Void> deleteFile(
            @Parameter(description = "Name of file to delete")
            @PathVariable String filename) {

        try {
            Path filePath = Paths.get(UPLOAD_DIR).resolve(filename);

            if (!Files.exists(filePath)) {
                return ResponseEntity.notFound().build();
            }

            // Security check
            if (!filePath.startsWith(Paths.get(UPLOAD_DIR))) {
                logger.warn("Security violation: Attempted to delete file outside upload directory: {}", filename);
                return ResponseEntity.status(HttpStatus.FORBIDDEN).build();
            }

            Files.delete(filePath);
            logger.info("File deleted: {}", filename);
            return ResponseEntity.noContent().build();

        } catch (IOException e) {
            logger.error("Failed to delete file {}: {}", filename, e.getMessage(), e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
        }
    }

    // Helper methods

    private Map<String, String> validateFile(MultipartFile file) {
        Map<String, String> errors = new HashMap<>();

        if (file.isEmpty()) {
            errors.put("file", "File is empty");
            return errors;
        }

        if (file.getSize() > MAX_FILE_SIZE) {
            errors.put("size", "File size exceeds maximum allowed size of " + (MAX_FILE_SIZE / 1024 / 1024) + "MB");
        }

        String originalFilename = file.getOriginalFilename();
        if (originalFilename == null || originalFilename.trim().isEmpty()) {
            errors.put("filename", "Invalid filename");
            return errors;
        }

        String extension = getFileExtension(originalFilename).toLowerCase();
        if (!ALLOWED_EXTENSIONS.contains(extension)) {
            errors.put("extension", "File type not allowed. Allowed types: " + ALLOWED_EXTENSIONS);
        }

        // Check for potentially dangerous filenames
        if (originalFilename.contains("..") || originalFilename.contains("/") || originalFilename.contains("\\")) {
            errors.put("filename", "Invalid characters in filename");
        }

        return errors;
    }

    private String getFileExtension(String filename) {
        if (filename == null || !filename.contains(".")) {
            return "";
        }
        return filename.substring(filename.lastIndexOf(".") + 1);
    }

    private String generateUniqueFilename(String originalFilename, String extension) {
        String timestamp = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss"));
        String uuid = UUID.randomUUID().toString().substring(0, 8);
        String baseName = originalFilename.substring(0, originalFilename.lastIndexOf("."));

        // Clean base name
        baseName = baseName.replaceAll("[^a-zA-Z0-9]", "_");

        return String.format("%s_%s_%s.%s", baseName, timestamp, uuid, extension);
    }
}