package {{packageName}}.controller;

import {{packageName}}.dto.{{domainTitleCase}}Request;
import {{packageName}}.dto.{{domainTitleCase}}Response;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * REST Controller for {{domainTitleCase}} operations
 *
 * This is a sample controller generated by Enterprise CLI.
 * Replace with your actual business logic.
 */
@RestController
@RequestMapping("/{{domain}}s")
@Tag(name = "{{domainTitleCase}}", description = "{{domainTitleCase}} management operations")
public class {{domainTitleCase}}Controller {

    /**
     * Hello World endpoint for service verification
     */
    @GetMapping("/hello")
    @Operation(summary = "Service health check", description = "Returns a greeting message to verify the service is running")
    public ResponseEntity<String> hello() {
        return ResponseEntity.ok("Hello from {{domainTitleCase}} Service! 🚀");
    }

    /**
     * Get all {{domain}}s
     */
    @GetMapping
    @Operation(summary = "Get all {{domain}}s", description = "Retrieve a list of all {{domain}}s")
    public ResponseEntity<List<{{domainTitleCase}}Response>> getAll{{domainTitleCase}}s() {
        List<{{domainTitleCase}}Response> {{domain}}s = new ArrayList<>();

        // Sample data - replace with actual service logic
        for (int i = 1; i <= 3; i++) {
            {{domainTitleCase}}Response {{domain}} = new {{domainTitleCase}}Response();
            {{domain}}.setId(UUID.randomUUID().toString());
            {{domain}}.setName("Sample {{domainTitleCase}} " + i);
            {{domain}}.setDescription("This is a sample {{domain}} created by Enterprise CLI");
            {{domain}}.setCreatedAt(LocalDateTime.now().minusDays(i));
            {{domain}}.setUpdatedAt(LocalDateTime.now());
            {{domain}}s.add({{domain}});
        }

        return ResponseEntity.ok({{domain}}s);
    }

    /**
     * Get {{domain}} by ID
     */
    @GetMapping("/{id}")
    @Operation(summary = "Get {{domain}} by ID", description = "Retrieve a specific {{domain}} by its unique identifier")
    public ResponseEntity<{{domainTitleCase}}Response> get{{domainTitleCase}}ById(
            @Parameter(description = "{{domainTitleCase}} unique identifier")
            @PathVariable String id) {

        // Sample data - replace with actual service logic
        {{domainTitleCase}}Response {{domain}} = new {{domainTitleCase}}Response();
        {{domain}}.setId(id);
        {{domain}}.setName("Sample {{domainTitleCase}}");
        {{domain}}.setDescription("{{domainTitleCase}} with ID: " + id);
        {{domain}}.setCreatedAt(LocalDateTime.now().minusDays(1));
        {{domain}}.setUpdatedAt(LocalDateTime.now());

        return ResponseEntity.ok({{domain}});
    }

    /**
     * Create new {{domain}}
     */
    @PostMapping
    @Operation(summary = "Create new {{domain}}", description = "Create a new {{domain}} with the provided information")
    public ResponseEntity<{{domainTitleCase}}Response> create{{domainTitleCase}}(
            @RequestBody {{domainTitleCase}}Request request) {

        // Sample data - replace with actual service logic
        {{domainTitleCase}}Response {{domain}} = new {{domainTitleCase}}Response();
        {{domain}}.setId(UUID.randomUUID().toString());
        {{domain}}.setName(request.getName());
        {{domain}}.setDescription(request.getDescription());
        {{domain}}.setCreatedAt(LocalDateTime.now());
        {{domain}}.setUpdatedAt(LocalDateTime.now());

        return ResponseEntity.status(HttpStatus.CREATED).body({{domain}});
    }

    /**
     * Update {{domain}}
     */
    @PutMapping("/{id}")
    @Operation(summary = "Update {{domain}}", description = "Update an existing {{domain}} with new information")
    public ResponseEntity<{{domainTitleCase}}Response> update{{domainTitleCase}}(
            @Parameter(description = "{{domainTitleCase}} unique identifier")
            @PathVariable String id,
            @RequestBody {{domainTitleCase}}Request request) {

        // Sample data - replace with actual service logic
        {{domainTitleCase}}Response {{domain}} = new {{domainTitleCase}}Response();
        {{domain}}.setId(id);
        {{domain}}.setName(request.getName());
        {{domain}}.setDescription(request.getDescription());
        {{domain}}.setCreatedAt(LocalDateTime.now().minusDays(1)); // Simulated creation date
        {{domain}}.setUpdatedAt(LocalDateTime.now());

        return ResponseEntity.ok({{domain}});
    }

    /**
     * Delete {{domain}}
     */
    @DeleteMapping("/{id}")
    @Operation(summary = "Delete {{domain}}", description = "Delete a {{domain}} by its unique identifier")
    public ResponseEntity<Void> delete{{domainTitleCase}}(
            @Parameter(description = "{{domainTitleCase}} unique identifier")
            @PathVariable String id) {

        // Sample logic - replace with actual service logic
        // In a real implementation, you would delete from database

        return ResponseEntity.noContent().build();
    }
}