package {{packageName}}.controller;

import {{packageName}}.dto.{{domainTitleCase}}Request;
import {{packageName}}.dto.{{domainTitleCase}}Response;
import {{packageName}}.entity.{{domainTitleCase}};
import {{packageName}}.enterprise.base.AbstractEnterpriseController;
import {{packageName}}.enterprise.base.AbstractEnterpriseService;
import {{packageName}}.service.{{domainTitleCase}}Service;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

/**
 * 👨‍💻 BUSINESS CONTROLLER - IMPLEMENT BUSINESS ENDPOINTS ONLY
 *
 * REST Controller for {{domainTitleCase}} operations.
 * Extends AbstractEnterpriseController for automatic infrastructure handling:
 * - Standard CRUD endpoints handled automatically
 * - Error handling, validation, audit, metrics handled automatically
 * - Focus ONLY on business-specific endpoints
 * - Infrastructure code is "blinded" and cannot be modified
 *
 * Generated by Enterprise CLI - Business layer implementation
 */
@RestController
@RequestMapping("/api/{{domain}}s")
@Tag(name = "{{domainTitleCase}}", description = "{{domainTitleCase}} management operations")
public class {{domainTitleCase}}Controller
    extends AbstractEnterpriseController<{{domainTitleCase}}, String, {{domainTitleCase}}Request, {{domainTitleCase}}Request, {{domainTitleCase}}Response> {

    private final {{domainTitleCase}}Service {{domain}}Service;

    @Autowired
    public {{domainTitleCase}}Controller({{domainTitleCase}}Service {{domain}}Service) {
        this.{{domain}}Service = {{domain}}Service;
    }

    // ================================
    // 👨‍💻 REQUIRED: AbstractEnterpriseController Implementation
    // ================================

    @Override
    protected AbstractEnterpriseService<{{domainTitleCase}}, String, {{domainTitleCase}}Request, {{domainTitleCase}}Request, {{domainTitleCase}}Response> getEnterpriseService() {
        return (AbstractEnterpriseService<{{domainTitleCase}}, String, {{domainTitleCase}}Request, {{domainTitleCase}}Request, {{domainTitleCase}}Response>) {{domain}}Service;
    }

    @Override
    protected String getEntityName() {
        return "{{domainTitleCase}}";
    }

    @Override
    protected String getEntityPathName() {
        return "{{domain}}s";
    }

    @Override
    protected String extractEntityId({{domainTitleCase}}Response responseDTO) {
        return responseDTO.getId();
    }

    @Override
    protected List<{{domainTitleCase}}Response> performSearch(Map<String, String> searchParams) {
        String searchText = searchParams.get("search");
        if (searchText != null && !searchText.trim().isEmpty()) {
            return {{domain}}Service.search{{domainTitleCase}}s(searchText);
        }
        return List.of();
    }

    // ================================
    // 👨‍💻 BUSINESS-SPECIFIC ENDPOINTS
    // ================================

    /**
     * 👨‍💻 Service verification endpoint
     */
    @GetMapping("/hello")
    @Operation(summary = "Service health check", description = "Returns a greeting message to verify the service is running")
    public ResponseEntity<String> hello() {
        return ResponseEntity.ok("Hello from {{domainTitleCase}} Service! 🚀");
    }

    /**
     * 👨‍💻 Get {{domain}}s created after specific date
     */
    @GetMapping("/created-after")
    @Operation(summary = "Get {{domain}}s created after date", description = "Retrieve {{domain}}s created after the specified date")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "{{domainTitleCase}}s retrieved successfully"),
            @ApiResponse(responseCode = "400", description = "Invalid date format")
    })
    public ResponseEntity<List<{{domainTitleCase}}Response>> get{{domainTitleCase}}sCreatedAfter(
            @Parameter(description = "Date in ISO format (yyyy-MM-ddTHH:mm:ss)")
            @RequestParam String date) {

        try {
            LocalDateTime dateTime = LocalDateTime.parse(date);
            return ResponseEntity.ok({{domain}}Service.get{{domainTitleCase}}sCreatedAfter(dateTime));
        } catch (Exception e) {
            return ResponseEntity.badRequest().build();
        }
    }

    /**
     * 👨‍💻 Check if {{domain}} exists by name
     */
    @GetMapping("/exists")
    @Operation(summary = "Check if {{domain}} exists", description = "Check if a {{domain}} exists by name")
    @ApiResponse(responseCode = "200", description = "Check completed successfully")
    public ResponseEntity<Boolean> exists{{domainTitleCase}}ByName(
            @Parameter(description = "{{domainTitleCase}} name")
            @RequestParam String name) {

        return ResponseEntity.ok({{domain}}Service.exists{{domainTitleCase}}ByName(name));
    }

    /**
     * 👨‍💻 Get active {{domain}}s
     */
    @GetMapping("/active")
    @Operation(summary = "Get active {{domain}}s", description = "Retrieve all active {{domain}}s")
    @ApiResponse(responseCode = "200", description = "Active {{domain}}s retrieved successfully")
    public ResponseEntity<List<{{domainTitleCase}}Response>> getActive{{domainTitleCase}}s() {
        return ResponseEntity.ok({{domain}}Service.getActive{{domainTitleCase}}s());
    }

    // ================================
    // 👨‍💻 ADD YOUR BUSINESS ENDPOINTS HERE
    // ================================

    /**
     * 👨‍💻 Add your domain-specific endpoints here
     *
     * Standard CRUD operations are handled automatically by AbstractEnterpriseController:
     * - GET    /api/{{domain}}s          -> Get all with pagination
     * - GET    /api/{{domain}}s/{id}     -> Get by ID
     * - POST   /api/{{domain}}s          -> Create new
     * - PUT    /api/{{domain}}s/{id}     -> Update existing
     * - DELETE /api/{{domain}}s/{id}     -> Delete by ID
     * - GET    /api/{{domain}}s/search   -> Search with parameters
     * - GET    /api/{{domain}}s/health   -> Health check
     *
     * Focus only on business-specific endpoints that add value beyond CRUD operations.
     */

    // Example business endpoint:
    /*
    @GetMapping("/popular")
    @Operation(summary = "Get popular {{domain}}s", description = "Retrieve {{domain}}s with high popularity scores")
    public ResponseEntity<List<{{domainTitleCase}}Response>> getPopular{{domainTitleCase}}s() {
        return ResponseEntity.ok({{domain}}Service.getPopular{{domainTitleCase}}s());
    }
    */
}