package {{packageName}}.audit;

/**
 * Enumeration of audit event severity levels for {{serviceNameTitleCase}}
 *
 * Defines severity levels for audit events to enable proper alerting and monitoring.
 * Generated by Enterprise CLI - customize according to your monitoring requirements.
 */
public enum AuditSeverity {

    /**
     * Informational events - routine operations, successful actions
     * No immediate action required
     */
    LOW("Low", "Informational events requiring no immediate action", 1),

    /**
     * Warning events - potentially concerning but not critical
     * Monitor but no immediate action required
     */
    MEDIUM("Medium", "Warning events that should be monitored", 2),

    /**
     * High severity events - security violations, system errors
     * Immediate attention and investigation required
     */
    HIGH("High", "Critical events requiring immediate attention", 3),

    /**
     * Critical severity events - major security breaches, system failures
     * Immediate escalation and response required
     */
    CRITICAL("Critical", "Critical events requiring immediate escalation", 4);

    private final String displayName;
    private final String description;
    private final int level;

    AuditSeverity(String displayName, String description, int level) {
        this.displayName = displayName;
        this.description = description;
        this.level = level;
    }

    public String getDisplayName() {
        return displayName;
    }

    public String getDescription() {
        return description;
    }

    public int getLevel() {
        return level;
    }

    /**
     * Check if this severity requires immediate attention
     */
    public boolean requiresImmediateAttention() {
        return this == HIGH || this == CRITICAL;
    }

    /**
     * Check if this severity requires alerting
     */
    public boolean requiresAlerting() {
        return this.level >= MEDIUM.level;
    }

    /**
     * Check if this severity requires escalation
     */
    public boolean requiresEscalation() {
        return this == CRITICAL;
    }

    /**
     * Get severity by name (case-insensitive)
     */
    public static AuditSeverity fromString(String name) {
        if (name == null) {
            return LOW; // Default to low severity
        }

        try {
            return AuditSeverity.valueOf(name.toUpperCase());
        } catch (IllegalArgumentException e) {
            return LOW; // Default to low severity for unknown values
        }
    }

    /**
     * Get severity by level
     */
    public static AuditSeverity fromLevel(int level) {
        for (AuditSeverity severity : values()) {
            if (severity.level == level) {
                return severity;
            }
        }
        return LOW; // Default to low severity
    }

    /**
     * Get the next higher severity level
     */
    public AuditSeverity escalate() {
        switch (this) {
            case LOW:
                return MEDIUM;
            case MEDIUM:
                return HIGH;
            case HIGH:
            case CRITICAL:
                return CRITICAL;
            default:
                return CRITICAL;
        }
    }

    /**
     * Get appropriate severity for an event type
     */
    public static AuditSeverity getSeverityForEventType(AuditEventType eventType) {
        if (eventType == null) {
            return LOW;
        }

        // Critical security events
        if (eventType == AuditEventType.SECURITY_VIOLATION ||
            eventType == AuditEventType.BRUTE_FORCE_ATTEMPT ||
            eventType == AuditEventType.SQL_INJECTION_ATTEMPT ||
            eventType == AuditEventType.PRIVILEGE_ESCALATION ||
            eventType == AuditEventType.DATA_CORRUPTION) {
            return CRITICAL;
        }

        // High severity events
        if (eventType == AuditEventType.AUTH_FAILURE ||
            eventType == AuditEventType.AUTHZ_FAILURE ||
            eventType == AuditEventType.SYSTEM_ERROR ||
            eventType == AuditEventType.DATABASE_CONNECTION_FAILED ||
            eventType == AuditEventType.XSS_ATTEMPT ||
            eventType == AuditEventType.CSRF_ATTEMPT ||
            eventType == AuditEventType.SUSPICIOUS_ACTIVITY) {
            return HIGH;
        }

        // Medium severity events
        if (eventType == AuditEventType.RATE_LIMIT_EXCEEDED ||
            eventType == AuditEventType.ACCOUNT_LOCKED ||
            eventType == AuditEventType.SESSION_TIMEOUT ||
            eventType == AuditEventType.CONFIGURATION_CHANGED ||
            eventType == AuditEventType.COMPLIANCE_VIOLATION) {
            return MEDIUM;
        }

        // Default to low severity for routine operations
        return LOW;
    }

    /**
     * Get color code for UI display
     */
    public String getColorCode() {
        switch (this) {
            case LOW:
                return "#28a745"; // Green
            case MEDIUM:
                return "#ffc107"; // Yellow
            case HIGH:
                return "#fd7e14"; // Orange
            case CRITICAL:
                return "#dc3545"; // Red
            default:
                return "#6c757d"; // Gray
        }
    }

    /**
     * Get icon for UI display
     */
    public String getIcon() {
        switch (this) {
            case LOW:
                return "ℹ️"; // Info
            case MEDIUM:
                return "⚠️"; // Warning
            case HIGH:
                return "🔥"; // Fire
            case CRITICAL:
                return "🚨"; // Alarm
            default:
                return "❓"; // Question
        }
    }
}