package {{packageName}}.audit;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;

/**
 * Audit Service for {{serviceNameTitleCase}}
 *
 * Provides comprehensive audit logging for security and compliance.
 * Tracks user actions, data changes, and system events.
 * Generated by Enterprise CLI - customize according to your audit requirements.
 */
@Service
public class AuditService {

    private final AuditEventRepository auditEventRepository;

    @Autowired
    public AuditService(AuditEventRepository auditEventRepository) {
        this.auditEventRepository = auditEventRepository;
    }

    /**
     * Audit {{domainTitleCase}} creation
     */
    public void audit{{domainTitleCase}}Created(String {{domain}}Id, Object {{domain}}Data) {
        AuditEvent event = AuditEvent.builder()
                .eventType(AuditEventType.{{domainTitleCase.toUpperCase()}}_CREATED)
                .resourceType("{{domainTitleCase}}")
                .resourceId({{domain}}Id)
                .action("CREATE")
                .details(createAuditDetails("{{domain}}_created", {{domain}}Data))
                .build();

        recordAuditEvent(event);
    }

    /**
     * Audit {{domainTitleCase}} update
     */
    public void audit{{domainTitleCase}}Updated(String {{domain}}Id, Object oldData, Object newData) {
        Map<String, Object> details = new HashMap<>();
        details.put("action", "{{domain}}_updated");
        details.put("old_data", oldData);
        details.put("new_data", newData);
        details.put("changes", calculateChanges(oldData, newData));

        AuditEvent event = AuditEvent.builder()
                .eventType(AuditEventType.{{domainTitleCase.toUpperCase()}}_UPDATED)
                .resourceType("{{domainTitleCase}}")
                .resourceId({{domain}}Id)
                .action("UPDATE")
                .details(details)
                .build();

        recordAuditEvent(event);
    }

    /**
     * Audit {{domainTitleCase}} deletion
     */
    public void audit{{domainTitleCase}}Deleted(String {{domain}}Id, Object {{domain}}Data) {
        AuditEvent event = AuditEvent.builder()
                .eventType(AuditEventType.{{domainTitleCase.toUpperCase()}}_DELETED)
                .resourceType("{{domainTitleCase}}")
                .resourceId({{domain}}Id)
                .action("DELETE")
                .details(createAuditDetails("{{domain}}_deleted", {{domain}}Data))
                .build();

        recordAuditEvent(event);
    }

    /**
     * Audit {{domainTitleCase}} access
     */
    public void audit{{domainTitleCase}}Accessed(String {{domain}}Id, String accessType) {
        Map<String, Object> details = new HashMap<>();
        details.put("action", "{{domain}}_accessed");
        details.put("access_type", accessType);

        AuditEvent event = AuditEvent.builder()
                .eventType(AuditEventType.{{domainTitleCase.toUpperCase()}}_ACCESSED)
                .resourceType("{{domainTitleCase}}")
                .resourceId({{domain}}Id)
                .action("READ")
                .details(details)
                .build();

        recordAuditEvent(event);
    }

    /**
     * Audit search operations
     */
    public void auditSearch(String searchQuery, int resultCount) {
        Map<String, Object> details = new HashMap<>();
        details.put("action", "search_performed");
        details.put("query", sanitizeSearchQuery(searchQuery));
        details.put("result_count", resultCount);

        AuditEvent event = AuditEvent.builder()
                .eventType(AuditEventType.SEARCH_PERFORMED)
                .resourceType("{{domainTitleCase}}")
                .action("SEARCH")
                .details(details)
                .build();

        recordAuditEvent(event);
    }

    /**
     * Audit authentication events
     */
    public void auditAuthentication(String username, String authType, boolean success, String failureReason) {
        Map<String, Object> details = new HashMap<>();
        details.put("action", "authentication_attempt");
        details.put("auth_type", authType);
        details.put("success", success);
        if (!success && failureReason != null) {
            details.put("failure_reason", failureReason);
        }

        AuditEvent event = AuditEvent.builder()
                .eventType(success ? AuditEventType.AUTH_SUCCESS : AuditEventType.AUTH_FAILURE)
                .resourceType("Authentication")
                .userId(username)
                .action("AUTHENTICATE")
                .details(details)
                .build();

        recordAuditEvent(event);
    }

    /**
     * Audit authorization events
     */
    public void auditAuthorization(String resource, String action, boolean success, String denialReason) {
        Map<String, Object> details = new HashMap<>();
        details.put("action", "authorization_check");
        details.put("requested_resource", resource);
        details.put("requested_action", action);
        details.put("success", success);
        if (!success && denialReason != null) {
            details.put("denial_reason", denialReason);
        }

        AuditEvent event = AuditEvent.builder()
                .eventType(success ? AuditEventType.AUTHZ_SUCCESS : AuditEventType.AUTHZ_FAILURE)
                .resourceType("Authorization")
                .action("AUTHORIZE")
                .details(details)
                .build();

        recordAuditEvent(event);
    }

    /**
     * Audit security violations
     */
    public void auditSecurityViolation(String violationType, String description, String severity) {
        Map<String, Object> details = new HashMap<>();
        details.put("action", "security_violation");
        details.put("violation_type", violationType);
        details.put("description", description);
        details.put("severity", severity);

        AuditEvent event = AuditEvent.builder()
                .eventType(AuditEventType.SECURITY_VIOLATION)
                .resourceType("Security")
                .action("VIOLATION")
                .details(details)
                .severity(AuditSeverity.valueOf(severity.toUpperCase()))
                .build();

        recordAuditEvent(event);
    }

    /**
     * Audit system errors
     */
    public void auditSystemError(String errorType, String errorMessage, Exception exception) {
        Map<String, Object> details = new HashMap<>();
        details.put("action", "system_error");
        details.put("error_type", errorType);
        details.put("error_message", errorMessage);
        if (exception != null) {
            details.put("exception_class", exception.getClass().getSimpleName());
            details.put("stack_trace", getStackTrace(exception));
        }

        AuditEvent event = AuditEvent.builder()
                .eventType(AuditEventType.SYSTEM_ERROR)
                .resourceType("System")
                .action("ERROR")
                .details(details)
                .severity(AuditSeverity.HIGH)
                .build();

        recordAuditEvent(event);
    }

    /**
     * Record audit event
     */
    private void recordAuditEvent(AuditEvent event) {
        // Set common fields
        event.setTimestamp(LocalDateTime.now());
        event.setUserId(getCurrentUserId());
        event.setUserAgent(getCurrentUserAgent());
        event.setIpAddress(getCurrentIpAddress());
        event.setSessionId(getCurrentSessionId());
        event.setCorrelationId(getCurrentCorrelationId());

        // Set default severity if not specified
        if (event.getSeverity() == null) {
            event.setSeverity(determineSeverity(event.getEventType()));
        }

        // Save audit event
        auditEventRepository.save(event);

        // For high-severity events, also send alerts
        if (event.getSeverity() == AuditSeverity.CRITICAL || event.getSeverity() == AuditSeverity.HIGH) {
            sendSecurityAlert(event);
        }
    }

    /**
     * Get current user ID from security context
     */
    private String getCurrentUserId() {
        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
        if (authentication != null && authentication.isAuthenticated()) {
            return authentication.getName();
        }
        return "anonymous";
    }

    /**
     * Get current user agent (placeholder - implement based on request context)
     */
    private String getCurrentUserAgent() {
        // In a real implementation, this would extract from HTTP request
        return "Unknown";
    }

    /**
     * Get current IP address (placeholder - implement based on request context)
     */
    private String getCurrentIpAddress() {
        // In a real implementation, this would extract from HTTP request
        return "Unknown";
    }

    /**
     * Get current session ID (placeholder - implement based on session management)
     */
    private String getCurrentSessionId() {
        // In a real implementation, this would extract from session
        return null;
    }

    /**
     * Get current correlation ID (placeholder - implement based on request tracing)
     */
    private String getCurrentCorrelationId() {
        // In a real implementation, this would extract from MDC or request headers
        return null;
    }

    /**
     * Create audit details map
     */
    private Map<String, Object> createAuditDetails(String action, Object data) {
        Map<String, Object> details = new HashMap<>();
        details.put("action", action);
        details.put("data", sanitizeData(data));
        return details;
    }

    /**
     * Calculate changes between old and new data
     */
    private Map<String, Object> calculateChanges(Object oldData, Object newData) {
        Map<String, Object> changes = new HashMap<>();
        // Implement change detection logic based on your requirements
        changes.put("has_changes", !oldData.equals(newData));
        return changes;
    }

    /**
     * Sanitize search query for audit logging
     */
    private String sanitizeSearchQuery(String query) {
        // Remove or mask sensitive information from search queries
        if (query == null) return null;
        return query.replaceAll("password", "***")
                   .replaceAll("secret", "***")
                   .replaceAll("token", "***");
    }

    /**
     * Sanitize data for audit logging
     */
    private Object sanitizeData(Object data) {
        // Remove or mask sensitive fields from audit data
        // This is a placeholder - implement based on your data sensitivity rules
        return data;
    }

    /**
     * Determine severity based on event type
     */
    private AuditSeverity determineSeverity(AuditEventType eventType) {
        switch (eventType) {
            case AUTH_FAILURE:
            case AUTHZ_FAILURE:
                return AuditSeverity.MEDIUM;
            case SECURITY_VIOLATION:
                return AuditSeverity.HIGH;
            case SYSTEM_ERROR:
                return AuditSeverity.HIGH;
            default:
                return AuditSeverity.LOW;
        }
    }

    /**
     * Get stack trace from exception
     */
    private String getStackTrace(Exception exception) {
        java.io.StringWriter sw = new java.io.StringWriter();
        exception.printStackTrace(new java.io.PrintWriter(sw));
        return sw.toString();
    }

    /**
     * Send security alert for high-severity events
     */
    private void sendSecurityAlert(AuditEvent event) {
        // Implement alerting mechanism (email, Slack, SIEM, etc.)
        // This is a placeholder for security team notifications
    }
}