/*
 * Copyright (c) {{year}} {{packageName}}
 * All rights reserved.
 */
package {{packageName}}.mapper;

import {{packageName}}.dto.{{domainTitleCase}}Request;
import {{packageName}}.dto.{{domainTitleCase}}Response;
import {{packageName}}.entity.{{domainTitleCase}};
import {{packageName}}.enterprise.framework.dto.EntityMapper;
import org.springframework.stereotype.Component;

/**
 * {{domainTitleCase}} Mapper
 *
 * <p>Implements EntityMapper interface for entity/DTO conversions.
 *
 * <p><strong>Framework provides default method:</strong>
 * <ul>
 *   <li>{@code toResponseList(List<Entity>)} - Converts list of entities to responses</li>
 * </ul>
 *
 * <p><strong>Maps:</strong>
 * <ul>
 *   <li>{@code toEntity(Request)} - Request DTO → Entity (for create)</li>
 *   <li>{@code toResponse(Entity)} - Entity → Response DTO (for read)</li>
 *   <li>{@code updateEntity(Entity, Request)} - Apply Request to existing Entity (for update)</li>
 * </ul>
 *
 * @author Enterprise CLI
 * @version {{frameworkVersion}}
 */
@Component
public class {{domainTitleCase}}Mapper implements EntityMapper<{{domainTitleCase}}, {{domainTitleCase}}Request, {{domainTitleCase}}Response> {

    /**
     * Converts Request DTO to Entity.
     * Used for CREATE operations.
     *
     * <p><strong>IMPORTANT:</strong> Do NOT set:
     * <ul>
     *   <li>id - Will be generated by database</li>
     *   <li>Audit fields - Will be set by framework</li>
     *   <li>Soft delete fields - Will be managed by framework</li>
     * </ul>
     *
     * @param request the request DTO
     * @return new entity instance
     */
    @Override
    public {{domainTitleCase}} toEntity({{domainTitleCase}}Request request) {
        if (request == null) {
            return null;
        }

        {{domainTitleCase}} entity = new {{domainTitleCase}}();

        // Map business fields only
        entity.setName(request.getName());
        entity.setDescription(request.getDescription());

        // Set default status if not provided
        if (request.getStatus() != null && !request.getStatus().isEmpty()) {
            entity.setStatus(request.getStatus());
        } else {
            entity.setStatus("ACTIVE"); // Default status
        }

        // DO NOT set:
        // - id (auto-generated)
        // - audit fields (set by framework)
        // - soft delete fields (managed by framework)
        // - version (managed by JPA)

        return entity;
    }

    /**
     * Converts Entity to Response DTO.
     * Used for READ operations.
     *
     * @param entity the entity
     * @return response DTO with all fields
     */
    @Override
    public {{domainTitleCase}}Response toResponse({{domainTitleCase}} entity) {
        if (entity == null) {
            return null;
        }

        {{domainTitleCase}}Response response = new {{domainTitleCase}}Response();

        // Primary key
        response.setId(entity.getId());

        // Business fields
        response.setName(entity.getName());
        response.setDescription(entity.getDescription());
        response.setStatus(entity.getStatus());

        // Audit fields
        response.setCreatedBy(entity.getCreatedBy());
        response.setCreatedAt(entity.getCreatedAt());
        response.setUpdatedBy(entity.getUpdatedBy());
        response.setUpdatedAt(entity.getUpdatedAt());
        response.setVersion(entity.getVersion());

        // Soft delete fields
        response.setDeleted(entity.isDeleted());
        response.setDeletedAt(entity.getDeletedAt());
        response.setDeletedBy(entity.getDeletedBy());

        return response;
    }

    /**
     * Updates existing Entity with Request DTO data.
     * Used for UPDATE (PUT/PATCH) operations.
     *
     * <p><strong>IMPORTANT:</strong> Do NOT update:
     * <ul>
     *   <li>id - Never changes</li>
     *   <li>createdBy, createdAt - Set once, never updated</li>
     *   <li>updatedBy, updatedAt - Updated by framework</li>
     *   <li>Soft delete fields - Managed by delete operations</li>
     * </ul>
     *
     * @param entity  the existing entity
     * @param request the request DTO with new data
     */
    @Override
    public void updateEntity({{domainTitleCase}} entity, {{domainTitleCase}}Request request) {
        if (request == null) {
            return;
        }

        // Update only the fields present in request
        if (request.getName() != null) {
            entity.setName(request.getName());
        }

        if (request.getDescription() != null) {
            entity.setDescription(request.getDescription());
        }

        if (request.getStatus() != null) {
            entity.setStatus(request.getStatus());
        }

        // DO NOT update:
        // - id
        // - audit fields (framework handles these)
        // - soft delete fields
        // - version
    }
}
