package {{packageName}}.mapper;

import {{packageName}}.dto.{{domainTitleCase}}Request;
import {{packageName}}.dto.{{domainTitleCase}}Response;
import {{packageName}}.entity.{{domainTitleCase}};
import org.mapstruct.*;
import org.springframework.stereotype.Component;

import java.util.List;

/**
 * MapStruct mapper for {{domainTitleCase}} entity and DTOs
 *
 * Provides high-performance mapping between entity and DTO objects.
 * Generated by Enterprise CLI - customize mapping logic as needed.
 *
 * Note: To use MapStruct, add this dependency to pom.xml:
 * <dependency>
 *   <groupId>org.mapstruct</groupId>
 *   <artifactId>mapstruct</artifactId>
 *   <version>1.5.5.Final</version>
 * </dependency>
 */
@Mapper(
    componentModel = "spring",
    unmappedTargetPolicy = ReportingPolicy.WARN,
    nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE
)
@Component
public interface {{domainTitleCase}}Mapper {

    /**
     * Convert {{domainTitleCase}} entity to response DTO
     */
    @Mapping(target = "id", source = "id")
    @Mapping(target = "name", source = "name")
    @Mapping(target = "description", source = "description")
    @Mapping(target = "createdAt", source = "createdAt")
    @Mapping(target = "updatedAt", source = "updatedAt")
    {{domainTitleCase}}Response toResponse({{domainTitleCase}} entity);

    /**
     * Convert list of {{domainTitleCase}} entities to response DTOs
     */
    List<{{domainTitleCase}}Response> toResponseList(List<{{domainTitleCase}}> entities);

    /**
     * Convert request DTO to {{domainTitleCase}} entity
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    @Mapping(target = "version", ignore = true)
    @Mapping(target = "name", source = "name")
    @Mapping(target = "description", source = "description")
    {{domainTitleCase}} toEntity({{domainTitleCase}}Request request);

    /**
     * Update entity from request DTO (partial update)
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    @Mapping(target = "version", ignore = true)
    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    void updateEntityFromRequest({{domainTitleCase}}Request request, @MappingTarget {{domainTitleCase}} entity);

    /**
     * Create a copy of entity (for audit purposes)
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "version", ignore = true)
    {{domainTitleCase}} copy({{domainTitleCase}} entity);

    /**
     * Convert entity to a summary DTO (minimal fields)
     */
    @Mapping(target = "id", source = "id")
    @Mapping(target = "name", source = "name")
    @Mapping(target = "createdAt", source = "createdAt")
    {{domainTitleCase}}Summary toSummary({{domainTitleCase}} entity);

    /**
     * Convert list of entities to summary DTOs
     */
    List<{{domainTitleCase}}Summary> toSummaryList(List<{{domainTitleCase}}> entities);

    /**
     * Custom mapping for complex business logic
     */
    @AfterMapping
    default void afterMappingToResponse({{domainTitleCase}} entity, @MappingTarget {{domainTitleCase}}Response response) {
        // Add custom post-processing logic here
        // Example: Calculate derived fields, apply business rules, etc.

        // Set display name (example of derived field)
        if (entity.getName() != null) {
            response.setDisplayName(entity.getName().toUpperCase());
        }

        // Set status based on business rules (example)
        if (entity.getDescription() != null && !entity.getDescription().trim().isEmpty()) {
            response.setStatus("ACTIVE");
        } else {
            response.setStatus("INCOMPLETE");
        }
    }

    /**
     * Custom mapping before converting request to entity
     */
    @BeforeMapping
    default void beforeMappingToEntity({{domainTitleCase}}Request request) {
        // Add custom pre-processing logic here
        // Example: Normalize data, validate business rules, etc.

        // Normalize name (example)
        if (request.getName() != null) {
            request.setName(request.getName().trim());
        }

        // Normalize description (example)
        if (request.getDescription() != null) {
            request.setDescription(request.getDescription().trim());
        }
    }

    /**
     * Summary DTO for lightweight operations
     */
    class {{domainTitleCase}}Summary {
        private String id;
        private String name;
        private String displayName;
        private String status;
        private java.time.LocalDateTime createdAt;

        // Constructors
        public {{domainTitleCase}}Summary() {}

        // Getters and Setters
        public String getId() { return id; }
        public void setId(String id) { this.id = id; }

        public String getName() { return name; }
        public void setName(String name) { this.name = name; }

        public String getDisplayName() { return displayName; }
        public void setDisplayName(String displayName) { this.displayName = displayName; }

        public String getStatus() { return status; }
        public void setStatus(String status) { this.status = status; }

        public java.time.LocalDateTime getCreatedAt() { return createdAt; }
        public void setCreatedAt(java.time.LocalDateTime createdAt) { this.createdAt = createdAt; }
    }
}