package {{packageName}}.client;

import {{packageName}}.service.ExternalIntegrationService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;
import org.springframework.web.reactive.function.client.WebClient;
import reactor.core.publisher.Mono;

import java.util.List;
import java.util.Map;

/**
 * Client for User Service Integration
 *
 * Handles all communication with the User microservice.
 * Example of how to create specific external service clients.
 * Generated by Enterprise CLI - customize according to your integration needs.
 */
@Component
public class UserServiceClient {

    private static final Logger logger = LoggerFactory.getLogger(UserServiceClient.class);

    private final WebClient userServiceWebClient;
    private final ExternalIntegrationService externalIntegrationService;

    @Value("${app.external.user-service.base-url:http://localhost:8081}")
    private String userServiceBaseUrl;

    @Autowired
    public UserServiceClient(WebClient userServiceWebClient,
                           ExternalIntegrationService externalIntegrationService) {
        this.userServiceWebClient = userServiceWebClient;
        this.externalIntegrationService = externalIntegrationService;
    }

    /**
     * Get user by ID
     */
    public UserDto getUserById(String userId) {
        logger.info("Fetching user with ID: {}", userId);

        String url = userServiceBaseUrl + "/api/v1/users/" + userId;
        return externalIntegrationService.getFromExternalService(url, UserDto.class);
    }

    /**
     * Get user by ID (reactive)
     */
    public Mono<UserDto> getUserByIdReactive(String userId) {
        logger.info("Fetching user reactively with ID: {}", userId);

        return userServiceWebClient
                .get()
                .uri("/api/v1/users/{id}", userId)
                .retrieve()
                .bodyToMono(UserDto.class);
    }

    /**
     * Get users by IDs
     */
    public List<UserDto> getUsersByIds(List<String> userIds) {
        logger.info("Fetching users with IDs: {}", userIds);

        String url = userServiceBaseUrl + "/api/v1/users/batch";
        return externalIntegrationService.postToExternalService(url, userIds, UserListResponse.class).getUsers();
    }

    /**
     * Create user
     */
    public UserDto createUser(CreateUserRequest request) {
        logger.info("Creating user with email: {}", request.getEmail());

        String url = userServiceBaseUrl + "/api/v1/users";
        return externalIntegrationService.postToExternalService(url, request, UserDto.class);
    }

    /**
     * Update user
     */
    public UserDto updateUser(String userId, UpdateUserRequest request) {
        logger.info("Updating user with ID: {}", userId);

        return userServiceWebClient
                .put()
                .uri("/api/v1/users/{id}", userId)
                .bodyValue(request)
                .retrieve()
                .bodyToMono(UserDto.class)
                .block(); // For synchronous operation
    }

    /**
     * Check if user exists
     */
    public boolean userExists(String userId) {
        logger.debug("Checking if user exists with ID: {}", userId);

        try {
            String url = userServiceBaseUrl + "/api/v1/users/" + userId + "/exists";
            Boolean exists = externalIntegrationService.getFromExternalService(url, Boolean.class);
            return exists != null && exists;
        } catch (ExternalIntegrationService.ExternalServiceException e) {
            logger.warn("Error checking user existence for ID: {}", userId, e);
            return false;
        }
    }

    /**
     * Get user permissions
     */
    public List<String> getUserPermissions(String userId) {
        logger.debug("Fetching permissions for user ID: {}", userId);

        String url = userServiceBaseUrl + "/api/v1/users/" + userId + "/permissions";
        PermissionsResponse response = externalIntegrationService.getFromExternalService(url, PermissionsResponse.class);
        return response != null ? response.getPermissions() : List.of();
    }

    /**
     * Health check for User Service
     */
    public boolean isUserServiceHealthy() {
        String healthUrl = userServiceBaseUrl + "/actuator/health";
        return externalIntegrationService.isExternalServiceHealthy(healthUrl);
    }

    // DTO Classes

    public static class UserDto {
        private String id;
        private String email;
        private String firstName;
        private String lastName;
        private String status;
        private java.time.LocalDateTime createdAt;

        // Constructors
        public UserDto() {}

        // Getters and Setters
        public String getId() { return id; }
        public void setId(String id) { this.id = id; }

        public String getEmail() { return email; }
        public void setEmail(String email) { this.email = email; }

        public String getFirstName() { return firstName; }
        public void setFirstName(String firstName) { this.firstName = firstName; }

        public String getLastName() { return lastName; }
        public void setLastName(String lastName) { this.lastName = lastName; }

        public String getStatus() { return status; }
        public void setStatus(String status) { this.status = status; }

        public java.time.LocalDateTime getCreatedAt() { return createdAt; }
        public void setCreatedAt(java.time.LocalDateTime createdAt) { this.createdAt = createdAt; }
    }

    public static class CreateUserRequest {
        private String email;
        private String firstName;
        private String lastName;
        private String password;

        // Constructors
        public CreateUserRequest() {}

        public CreateUserRequest(String email, String firstName, String lastName, String password) {
            this.email = email;
            this.firstName = firstName;
            this.lastName = lastName;
            this.password = password;
        }

        // Getters and Setters
        public String getEmail() { return email; }
        public void setEmail(String email) { this.email = email; }

        public String getFirstName() { return firstName; }
        public void setFirstName(String firstName) { this.firstName = firstName; }

        public String getLastName() { return lastName; }
        public void setLastName(String lastName) { this.lastName = lastName; }

        public String getPassword() { return password; }
        public void setPassword(String password) { this.password = password; }
    }

    public static class UpdateUserRequest {
        private String firstName;
        private String lastName;
        private String status;

        // Constructors
        public UpdateUserRequest() {}

        // Getters and Setters
        public String getFirstName() { return firstName; }
        public void setFirstName(String firstName) { this.firstName = firstName; }

        public String getLastName() { return lastName; }
        public void setLastName(String lastName) { this.lastName = lastName; }

        public String getStatus() { return status; }
        public void setStatus(String status) { this.status = status; }
    }

    public static class UserListResponse {
        private List<UserDto> users;

        // Constructors
        public UserListResponse() {}

        public UserListResponse(List<UserDto> users) {
            this.users = users;
        }

        // Getters and Setters
        public List<UserDto> getUsers() { return users; }
        public void setUsers(List<UserDto> users) { this.users = users; }
    }

    public static class PermissionsResponse {
        private List<String> permissions;

        // Constructors
        public PermissionsResponse() {}

        public PermissionsResponse(List<String> permissions) {
            this.permissions = permissions;
        }

        // Getters and Setters
        public List<String> getPermissions() { return permissions; }
        public void setPermissions(List<String> permissions) { this.permissions = permissions; }
    }
}