package {{packageName}}.event;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.stereotype.Component;

/**
 * Domain Event Publisher for {{serviceNameTitleCase}}
 *
 * Centralized service for publishing domain events within the application.
 * Generated by Enterprise CLI - customize with additional event handling as needed.
 */
@Component
public class DomainEventPublisher {

    private static final Logger logger = LoggerFactory.getLogger(DomainEventPublisher.class);

    private final ApplicationEventPublisher applicationEventPublisher;

    @Autowired
    public DomainEventPublisher(ApplicationEventPublisher applicationEventPublisher) {
        this.applicationEventPublisher = applicationEventPublisher;
    }

    /**
     * Publish a domain event
     */
    public void publishEvent(DomainEvent event) {
        try {
            logger.debug("Publishing domain event: {}", event.getEventType());
            applicationEventPublisher.publishEvent(event);
            logger.info("Successfully published domain event: {} for aggregate: {}",
                event.getEventType(), event.getAggregateId());
        } catch (Exception e) {
            logger.error("Failed to publish domain event: {} for aggregate: {}",
                event.getEventType(), event.getAggregateId(), e);
            throw new DomainEventPublishingException("Failed to publish domain event", e);
        }
    }

    /**
     * Publish {{domainTitleCase}} created event
     */
    public void publish{{domainTitleCase}}Created({{packageName}}.entity.{{domainTitleCase}} {{domain}}) {
        {{domainTitleCase}}CreatedEvent event = new {{domainTitleCase}}CreatedEvent({{domain}});
        publishEvent(event);
    }

    /**
     * Publish {{domainTitleCase}} updated event
     */
    public void publish{{domainTitleCase}}Updated({{packageName}}.entity.{{domainTitleCase}} previous{{domainTitleCase}},
                                                {{packageName}}.entity.{{domainTitleCase}} updated{{domainTitleCase}}) {
        {{domainTitleCase}}UpdatedEvent event = new {{domainTitleCase}}UpdatedEvent(previous{{domainTitleCase}}, updated{{domainTitleCase}});
        publishEvent(event);
    }

    /**
     * Publish {{domainTitleCase}} deleted event
     */
    public void publish{{domainTitleCase}}Deleted({{packageName}}.entity.{{domainTitleCase}} {{domain}}) {
        {{domainTitleCase}}DeletedEvent event = new {{domainTitleCase}}DeletedEvent({{domain}});
        publishEvent(event);
    }

    /**
     * Exception thrown when domain event publishing fails
     */
    public static class DomainEventPublishingException extends RuntimeException {
        public DomainEventPublishingException(String message, Throwable cause) {
            super(message, cause);
        }
    }
}