package {{packageName}}.event;

import {{packageName}}.audit.AuditService;
import {{packageName}}.monitoring.{{domainTitleCase}}MetricsService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.event.EventListener;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Component;
import org.springframework.transaction.event.TransactionPhase;
import org.springframework.transaction.event.TransactionalEventListener;

/**
 * Event listener for {{domainTitleCase}} domain events
 *
 * Handles cross-cutting concerns triggered by {{domain}} operations.
 * Generated by Enterprise CLI - customize with your business logic.
 */
@Component
public class {{domainTitleCase}}EventListener {

    private static final Logger logger = LoggerFactory.getLogger({{domainTitleCase}}EventListener.class);

    private final AuditService auditService;
    private final {{domainTitleCase}}MetricsService metricsService;

    @Autowired
    public {{domainTitleCase}}EventListener(AuditService auditService,
                                          {{domainTitleCase}}MetricsService metricsService) {
        this.auditService = auditService;
        this.metricsService = metricsService;
    }

    /**
     * Handle {{domainTitleCase}} created events
     */
    @TransactionalEventListener(phase = TransactionPhase.AFTER_COMMIT)
    @Async
    public void handle{{domainTitleCase}}Created({{domainTitleCase}}CreatedEvent event) {
        logger.info("Handling {{domain}} created event for ID: {}", event.get{{domainTitleCase}}Id());

        try {
            // Record audit event
            auditService.audit{{domainTitleCase}}Created(
                event.get{{domainTitleCase}}Id(),
                createAuditData(event.get{{domainTitleCase}}Name(), event.get{{domainTitleCase}}Description())
            );

            // Record metrics
            metricsService.recordCreation();

            // Add your custom business logic here
            handleCustom{{domainTitleCase}}CreatedLogic(event);

            logger.debug("Successfully handled {{domain}} created event for ID: {}", event.get{{domainTitleCase}}Id());

        } catch (Exception e) {
            logger.error("Error handling {{domain}} created event for ID: {}",
                event.get{{domainTitleCase}}Id(), e);
            metricsService.recordError();
        }
    }

    /**
     * Handle {{domainTitleCase}} updated events
     */
    @TransactionalEventListener(phase = TransactionPhase.AFTER_COMMIT)
    @Async
    public void handle{{domainTitleCase}}Updated({{domainTitleCase}}UpdatedEvent event) {
        logger.info("Handling {{domain}} updated event for ID: {}", event.get{{domainTitleCase}}Id());

        try {
            // Create old and new data for audit
            Object oldData = createAuditData(event.getPreviousName(), event.getPreviousDescription());
            Object newData = createAuditData(event.getNewName(), event.getNewDescription());

            // Record audit event
            auditService.audit{{domainTitleCase}}Updated(
                event.get{{domainTitleCase}}Id(),
                oldData,
                newData
            );

            // Record metrics
            metricsService.recordUpdate();

            // Handle specific field changes
            if (event.isNameChanged()) {
                handleNameChanged(event);
            }

            if (event.isDescriptionChanged()) {
                handleDescriptionChanged(event);
            }

            // Add your custom business logic here
            handleCustom{{domainTitleCase}}UpdatedLogic(event);

            logger.debug("Successfully handled {{domain}} updated event for ID: {}", event.get{{domainTitleCase}}Id());

        } catch (Exception e) {
            logger.error("Error handling {{domain}} updated event for ID: {}",
                event.get{{domainTitleCase}}Id(), e);
            metricsService.recordError();
        }
    }

    /**
     * Handle {{domainTitleCase}} deleted events
     */
    @TransactionalEventListener(phase = TransactionPhase.AFTER_COMMIT)
    @Async
    public void handle{{domainTitleCase}}Deleted({{domainTitleCase}}DeletedEvent event) {
        logger.info("Handling {{domain}} deleted event for ID: {}", event.get{{domainTitleCase}}Id());

        try {
            // Record audit event
            auditService.audit{{domainTitleCase}}Deleted(
                event.get{{domainTitleCase}}Id(),
                createAuditData(event.get{{domainTitleCase}}Name(), event.get{{domainTitleCase}}Description())
            );

            // Record metrics
            metricsService.recordDeletion();

            // Add your custom business logic here
            handleCustom{{domainTitleCase}}DeletedLogic(event);

            logger.debug("Successfully handled {{domain}} deleted event for ID: {}", event.get{{domainTitleCase}}Id());

        } catch (Exception e) {
            logger.error("Error handling {{domain}} deleted event for ID: {}",
                event.get{{domainTitleCase}}Id(), e);
            metricsService.recordError();
        }
    }

    /**
     * Generic domain event handler for logging and monitoring
     */
    @EventListener
    public void handleDomainEvent(DomainEvent event) {
        logger.debug("Domain event occurred: {} for aggregate: {}",
            event.getEventType(), event.getAggregateId());

        // Record general event metrics
        metricsService.recordBusinessMetric("domain_events_total", 1);
    }

    // Private helper methods

    private Object createAuditData(String name, String description) {
        return new {{domainTitleCase}}AuditData(name, description);
    }

    private void handleNameChanged({{domainTitleCase}}UpdatedEvent event) {
        logger.info("{{domainTitleCase}} name changed from '{}' to '{}' for ID: {}",
            event.getPreviousName(), event.getNewName(), event.get{{domainTitleCase}}Id());

        // Add custom logic for name changes
        // Example: Update search indexes, notify dependent systems, etc.
    }

    private void handleDescriptionChanged({{domainTitleCase}}UpdatedEvent event) {
        logger.info("{{domainTitleCase}} description changed for ID: {}", event.get{{domainTitleCase}}Id());

        // Add custom logic for description changes
        // Example: Update content analysis, trigger notifications, etc.
    }

    // Custom business logic methods (implement based on your requirements)

    private void handleCustom{{domainTitleCase}}CreatedLogic({{domainTitleCase}}CreatedEvent event) {
        // Implement your custom business logic for {{domain}} creation
        // Examples:
        // - Send welcome notifications
        // - Initialize related data structures
        // - Integrate with external systems
        // - Trigger workflows
    }

    private void handleCustom{{domainTitleCase}}UpdatedLogic({{domainTitleCase}}UpdatedEvent event) {
        // Implement your custom business logic for {{domain}} updates
        // Examples:
        // - Send update notifications
        // - Sync with external systems
        // - Update search indexes
        // - Trigger approval workflows
    }

    private void handleCustom{{domainTitleCase}}DeletedLogic({{domainTitleCase}}DeletedEvent event) {
        // Implement your custom business logic for {{domain}} deletion
        // Examples:
        // - Cleanup related data
        // - Send deletion notifications
        // - Archive data
        // - Update external systems
    }

    /**
     * Audit data structure for {{domainTitleCase}} events
     */
    private static class {{domainTitleCase}}AuditData {
        private final String name;
        private final String description;

        public {{domainTitleCase}}AuditData(String name, String description) {
            this.name = name;
            this.description = description;
        }

        public String getName() { return name; }
        public String getDescription() { return description; }

        @Override
        public String toString() {
            return "{{domainTitleCase}}AuditData{" +
                    "name='" + name + '\'' +
                    ", description='" + description + '\'' +
                    '}';
        }
    }
}