package {{packageName}}.monitoring;

import {{packageName}}.monitoring.{{domainTitleCase}}MetricsService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Lazy;
import org.springframework.stereotype.Component;
import org.springframework.web.servlet.HandlerInterceptor;
import org.springframework.web.servlet.ModelAndView;

import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Performance Monitoring Interceptor for {{serviceNameTitleCase}}
 *
 * Monitors HTTP request performance and provides detailed metrics.
 * Tracks response times, throughput, and identifies slow operations.
 * Generated by Enterprise CLI - customize according to your performance requirements.
 */
@Component
@Lazy
public class PerformanceInterceptor implements HandlerInterceptor {

    private static final Logger logger = LoggerFactory.getLogger(PerformanceInterceptor.class);

    private final {{domainTitleCase}}MetricsService metricsService;
    private final Map<String, Long> requestStartTimes = new ConcurrentHashMap<>();

    // Performance thresholds
    private static final long SLOW_REQUEST_THRESHOLD_MS = 1000; // 1 second
    private static final long VERY_SLOW_REQUEST_THRESHOLD_MS = 5000; // 5 seconds

    @Autowired
    public PerformanceInterceptor(@Lazy {{domainTitleCase}}MetricsService metricsService) {
        this.metricsService = metricsService;
    }

    @Override
    public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler) {
        String requestId = getRequestId(request);
        long startTime = System.currentTimeMillis();

        // Store start time for this request
        requestStartTimes.put(requestId, startTime);

        // Add performance headers
        response.setHeader("X-Request-ID", requestId);
        response.setHeader("X-Service-Name", "{{serviceName}}");

        // Log request start
        if (logger.isDebugEnabled()) {
            logger.debug("Request started: {} {} from {}",
                request.getMethod(),
                request.getRequestURI(),
                getClientIpAddress(request));
        }

        return true;
    }

    @Override
    public void postHandle(HttpServletRequest request, HttpServletResponse response,
                          Object handler, ModelAndView modelAndView) {
        // This method is called after the handler method has been executed
        // but before the view is rendered
    }

    @Override
    public void afterCompletion(HttpServletRequest request, HttpServletResponse response,
                               Object handler, Exception ex) {
        String requestId = getRequestId(request);
        Long startTime = requestStartTimes.remove(requestId);

        if (startTime != null) {
            long duration = System.currentTimeMillis() - startTime;

            // Record performance metrics
            recordPerformanceMetrics(request, response, duration, ex);

            // Log performance information
            logPerformanceInfo(request, response, duration, ex);

            // Check for performance issues
            checkPerformanceThresholds(request, duration);
        }
    }

    private void recordPerformanceMetrics(HttpServletRequest request, HttpServletResponse response,
                                        long duration, Exception ex) {
        String method = request.getMethod();
        String endpoint = getEndpointPattern(request);
        int statusCode = response.getStatus();

        // Record API usage metrics
        metricsService.recordAPIUsage(endpoint, method, statusCode);

        // Record performance timing
        metricsService.recordPerformanceMetric("http_request_duration", duration);

        // Record error metrics if applicable
        if (ex != null || statusCode >= 400) {
            metricsService.recordError();
            metricsService.recordPerformanceMetric("http_request_error", 1);
        }

        // Record specific operation metrics
        if (endpoint.contains("{{domain}}")) {
            recordDomainSpecificMetrics(method, endpoint, duration);
        }
    }

    private void recordDomainSpecificMetrics(String method, String endpoint, long duration) {
        switch (method.toUpperCase()) {
            case "GET":
                if (endpoint.contains("/search")) {
                    metricsService.recordSearch();
                }
                break;
            case "POST":
                metricsService.recordCreation();
                break;
            case "PUT":
            case "PATCH":
                metricsService.recordUpdate();
                break;
            case "DELETE":
                metricsService.recordDeletion();
                break;
        }
    }

    private void logPerformanceInfo(HttpServletRequest request, HttpServletResponse response,
                                   long duration, Exception ex) {
        String logLevel = determineLogLevel(duration, response.getStatus(), ex);
        String message = String.format(
            "Request completed: %s %s | Status: %d | Duration: %dms | IP: %s | User-Agent: %s",
            request.getMethod(),
            request.getRequestURI(),
            response.getStatus(),
            duration,
            getClientIpAddress(request),
            request.getHeader("User-Agent")
        );

        switch (logLevel) {
            case "ERROR":
                logger.error(message, ex);
                break;
            case "WARN":
                logger.warn(message);
                break;
            case "INFO":
                logger.info(message);
                break;
            default:
                logger.debug(message);
                break;
        }
    }

    private String determineLogLevel(long duration, int statusCode, Exception ex) {
        if (ex != null || statusCode >= 500) {
            return "ERROR";
        } else if (statusCode >= 400 || duration > VERY_SLOW_REQUEST_THRESHOLD_MS) {
            return "WARN";
        } else if (duration > SLOW_REQUEST_THRESHOLD_MS) {
            return "INFO";
        } else {
            return "DEBUG";
        }
    }

    private void checkPerformanceThresholds(HttpServletRequest request, long duration) {
        if (duration > VERY_SLOW_REQUEST_THRESHOLD_MS) {
            logger.warn("Very slow request detected: {} {} took {}ms",
                request.getMethod(), request.getRequestURI(), duration);

            metricsService.recordPerformanceMetric("very_slow_requests", 1);
        } else if (duration > SLOW_REQUEST_THRESHOLD_MS) {
            logger.info("Slow request detected: {} {} took {}ms",
                request.getMethod(), request.getRequestURI(), duration);

            metricsService.recordPerformanceMetric("slow_requests", 1);
        }
    }

    private String getRequestId(HttpServletRequest request) {
        String requestId = request.getHeader("X-Request-ID");
        if (requestId == null) {
            requestId = java.util.UUID.randomUUID().toString();
        }
        return requestId;
    }

    private String getClientIpAddress(HttpServletRequest request) {
        String xForwardedFor = request.getHeader("X-Forwarded-For");
        if (xForwardedFor != null && !xForwardedFor.isEmpty()) {
            return xForwardedFor.split(",")[0].trim();
        }

        String xRealIp = request.getHeader("X-Real-IP");
        if (xRealIp != null && !xRealIp.isEmpty()) {
            return xRealIp;
        }

        return request.getRemoteAddr();
    }

    private String getEndpointPattern(HttpServletRequest request) {
        String uri = request.getRequestURI();
        String contextPath = request.getContextPath();

        if (contextPath != null && !contextPath.isEmpty()) {
            uri = uri.substring(contextPath.length());
        }

        // Replace dynamic path variables with placeholders for better grouping
        uri = uri.replaceAll("/\\d+", "/{id}");
        uri = uri.replaceAll("/[a-fA-F0-9-]{36}", "/{uuid}");

        return uri;
    }

    /**
     * Performance statistics collection
     */
    public static class PerformanceStats {
        private long totalRequests = 0;
        private long totalDuration = 0;
        private long slowRequests = 0;
        private long errorRequests = 0;

        public void recordRequest(long duration, boolean isError) {
            totalRequests++;
            totalDuration += duration;

            if (duration > SLOW_REQUEST_THRESHOLD_MS) {
                slowRequests++;
            }

            if (isError) {
                errorRequests++;
            }
        }

        public double getAverageResponseTime() {
            return totalRequests > 0 ? (double) totalDuration / totalRequests : 0;
        }

        public double getSlowRequestPercentage() {
            return totalRequests > 0 ? (double) slowRequests / totalRequests * 100 : 0;
        }

        public double getErrorRate() {
            return totalRequests > 0 ? (double) errorRequests / totalRequests * 100 : 0;
        }

        // Getters
        public long getTotalRequests() { return totalRequests; }
        public long getTotalDuration() { return totalDuration; }
        public long getSlowRequests() { return slowRequests; }
        public long getErrorRequests() { return errorRequests; }
    }
}