package {{packageName}}.service.impl;

import {{packageName}}.dto.{{domainTitleCase}}Request;
import {{packageName}}.dto.{{domainTitleCase}}Response;
import {{packageName}}.entity.{{domainTitleCase}};
import {{packageName}}.repository.{{domainTitleCase}}Repository;
import {{packageName}}.service.{{domainTitleCase}}Service;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

/**
 * Service implementation for {{domainTitleCase}} business operations
 *
 * This is a sample service implementation generated by Enterprise CLI.
 * Implement business logic according to your requirements.
 */
@Service
@Transactional
public class {{domainTitleCase}}ServiceImpl implements {{domainTitleCase}}Service {

    private static final Logger logger = LoggerFactory.getLogger({{domainTitleCase}}ServiceImpl.class);

    private final {{domainTitleCase}}Repository {{domain}}Repository;

    @Autowired
    public {{domainTitleCase}}ServiceImpl({{domainTitleCase}}Repository {{domain}}Repository) {
        this.{{domain}}Repository = {{domain}}Repository;
    }

    @Override
    public {{domainTitleCase}}Response create{{domainTitleCase}}({{domainTitleCase}}Request request) {
        logger.info("Creating new {{domain}} with name: {}", request.getName());

        // Check if {{domain}} with same name already exists
        if ({{domain}}Repository.existsByNameIgnoreCase(request.getName())) {
            throw new IllegalArgumentException("{{domainTitleCase}} with name '" + request.getName() + "' already exists");
        }

        {{domainTitleCase}} entity = convertToEntity(request);
        {{domainTitleCase}} savedEntity = {{domain}}Repository.save(entity);

        logger.info("Successfully created {{domain}} with ID: {}", savedEntity.getId());
        return convertToResponse(savedEntity);
    }

    @Override
    @Transactional(readOnly = true)
    public Optional<{{domainTitleCase}}Response> get{{domainTitleCase}}ById(String id) {
        logger.debug("Fetching {{domain}} with ID: {}", id);

        return {{domain}}Repository.findById(id)
                .map(this::convertToResponse);
    }

    @Override
    @Transactional(readOnly = true)
    public Page<{{domainTitleCase}}Response> getAll{{domainTitleCase}}s(Pageable pageable) {
        logger.debug("Fetching all {{domain}}s with pagination: {}", pageable);

        return {{domain}}Repository.findAll(pageable)
                .map(this::convertToResponse);
    }

    @Override
    @Transactional(readOnly = true)
    public List<{{domainTitleCase}}Response> getAll{{domainTitleCase}}s() {
        logger.debug("Fetching all {{domain}}s");

        return {{domain}}Repository.findAll()
                .stream()
                .map(this::convertToResponse)
                .collect(Collectors.toList());
    }

    @Override
    public Optional<{{domainTitleCase}}Response> update{{domainTitleCase}}(String id, {{domainTitleCase}}Request request) {
        logger.info("Updating {{domain}} with ID: {}", id);

        return {{domain}}Repository.findById(id)
                .map(existingEntity -> {
                    // Check if name is being changed and new name doesn't conflict
                    if (!existingEntity.getName().equalsIgnoreCase(request.getName()) &&
                        {{domain}}Repository.existsByNameIgnoreCase(request.getName())) {
                        throw new IllegalArgumentException("{{domainTitleCase}} with name '" + request.getName() + "' already exists");
                    }

                    existingEntity.setName(request.getName());
                    existingEntity.setDescription(request.getDescription());

                    {{domainTitleCase}} updatedEntity = {{domain}}Repository.save(existingEntity);
                    logger.info("Successfully updated {{domain}} with ID: {}", id);

                    return convertToResponse(updatedEntity);
                });
    }

    @Override
    public boolean delete{{domainTitleCase}}(String id) {
        logger.info("Deleting {{domain}} with ID: {}", id);

        if ({{domain}}Repository.existsById(id)) {
            {{domain}}Repository.deleteById(id);
            logger.info("Successfully deleted {{domain}} with ID: {}", id);
            return true;
        }

        logger.warn("{{domainTitleCase}} with ID {} not found for deletion", id);
        return false;
    }

    @Override
    @Transactional(readOnly = true)
    public List<{{domainTitleCase}}Response> search{{domainTitleCase}}s(String searchText) {
        logger.debug("Searching {{domain}}s with text: {}", searchText);

        return {{domain}}Repository.findByNameOrDescriptionContaining(searchText)
                .stream()
                .map(this::convertToResponse)
                .collect(Collectors.toList());
    }

    @Override
    @Transactional(readOnly = true)
    public List<{{domainTitleCase}}Response> find{{domainTitleCase}}sByName(String namePattern) {
        logger.debug("Finding {{domain}}s by name pattern: {}", namePattern);

        return {{domain}}Repository.findByNameContainingIgnoreCase(namePattern)
                .stream()
                .map(this::convertToResponse)
                .collect(Collectors.toList());
    }

    @Override
    @Transactional(readOnly = true)
    public List<{{domainTitleCase}}Response> get{{domainTitleCase}}sCreatedAfter(LocalDateTime date) {
        logger.debug("Finding {{domain}}s created after: {}", date);

        return {{domain}}Repository.findByCreatedAtAfter(date)
                .stream()
                .map(this::convertToResponse)
                .collect(Collectors.toList());
    }

    @Override
    @Transactional(readOnly = true)
    public boolean exists{{domainTitleCase}}ByName(String name) {
        logger.debug("Checking if {{domain}} exists with name: {}", name);

        return {{domain}}Repository.existsByNameIgnoreCase(name);
    }

    @Override
    @Transactional(readOnly = true)
    public long count{{domainTitleCase}}sCreatedAfter(LocalDateTime date) {
        logger.debug("Counting {{domain}}s created after: {}", date);

        return {{domain}}Repository.countByCreatedAtAfter(date);
    }

    @Override
    @Transactional(readOnly = true)
    public List<{{domainTitleCase}}Response> getActive{{domainTitleCase}}s() {
        logger.debug("Fetching active {{domain}}s");

        return {{domain}}Repository.findActive{{domainTitleCase}}s()
                .stream()
                .map(this::convertToResponse)
                .collect(Collectors.toList());
    }

    @Override
    public {{domainTitleCase}}Response convertToResponse({{domainTitleCase}} entity) {
        {{domainTitleCase}}Response response = new {{domainTitleCase}}Response();
        response.setId(entity.getId());
        response.setName(entity.getName());
        response.setDescription(entity.getDescription());
        response.setCreatedAt(entity.getCreatedAt());
        response.setUpdatedAt(entity.getUpdatedAt());
        return response;
    }

    @Override
    public {{domainTitleCase}} convertToEntity({{domainTitleCase}}Request request) {
        {{domainTitleCase}} entity = new {{domainTitleCase}}();
        entity.setName(request.getName());
        entity.setDescription(request.getDescription());
        return entity;
    }
}