package {{packageName}}.service.impl;

import {{packageName}}.dto.{{domainTitleCase}}Request;
import {{packageName}}.dto.{{domainTitleCase}}Response;
import {{packageName}}.entity.{{domainTitleCase}};
import {{packageName}}.event.DomainEventPublisher;
import {{packageName}}.mapper.{{domainTitleCase}}Mapper;
import {{packageName}}.monitoring.{{domainTitleCase}}MetricsService;
import {{packageName}}.repository.{{domainTitleCase}}Repository;
import {{packageName}}.service.{{domainTitleCase}}Service;
import {{packageName}}.validation.{{domainTitleCase}}Validator;
import io.micrometer.core.instrument.Timer;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.cache.annotation.CacheEvict;
import org.springframework.cache.annotation.CachePut;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

/**
 * Service implementation for {{domainTitleCase}} business operations
 *
 * Enterprise-grade service with integrated caching, metrics, events, and audit.
 * Generated by Enterprise CLI - add your business logic where indicated.
 */
@Service
@Transactional
public class {{domainTitleCase}}ServiceImpl implements {{domainTitleCase}}Service {

    private static final Logger logger = LoggerFactory.getLogger({{domainTitleCase}}ServiceImpl.class);

    private final {{domainTitleCase}}Repository {{domain}}Repository;
    private final {{domainTitleCase}}Mapper {{domain}}Mapper;
    private final DomainEventPublisher eventPublisher;
    private final {{domainTitleCase}}MetricsService metricsService;
    private final {{domainTitleCase}}Validator {{domain}}Validator;

    @Autowired
    public {{domainTitleCase}}ServiceImpl({{domainTitleCase}}Repository {{domain}}Repository,
                                        {{domainTitleCase}}Mapper {{domain}}Mapper,
                                        DomainEventPublisher eventPublisher,
                                        {{domainTitleCase}}MetricsService metricsService,
                                        {{domainTitleCase}}Validator {{domain}}Validator) {
        this.{{domain}}Repository = {{domain}}Repository;
        this.{{domain}}Mapper = {{domain}}Mapper;
        this.eventPublisher = eventPublisher;
        this.metricsService = metricsService;
        this.{{domain}}Validator = {{domain}}Validator;
    }

    @Override
    @CacheEvict(value = "{{domain}}s", allEntries = true)
    public {{domainTitleCase}}Response create{{domainTitleCase}}({{domainTitleCase}}Request request) {
        Timer.Sample timer = metricsService.startCreationTimer();
        logger.info("Creating new {{domain}} with name: {}", request.getName());

        try {
            // Validate request using custom validator
            {{domainTitleCase}}Validator.ValidationResult validationResult = {{domain}}Validator.validateCreateRequest(request);
            if (!validationResult.isValid()) {
                throw new IllegalArgumentException(validationResult.getErrorMessage());
            }

            // Check if {{domain}} with same name already exists
            if ({{domain}}Repository.existsByNameIgnoreCase(request.getName())) {
                throw new IllegalArgumentException("{{domainTitleCase}} with name '" + request.getName() + "' already exists");
            }

            {{domainTitleCase}} entity = {{domain}}Mapper.toEntity(request);
            {{domainTitleCase}} savedEntity = {{domain}}Repository.save(entity);

            // Publish domain event
            eventPublisher.publish{{domainTitleCase}}Created(savedEntity);

            // Record metrics
            metricsService.recordCreation();

            logger.info("Successfully created {{domain}} with ID: {}", savedEntity.getId());
            return {{domain}}Mapper.toResponse(savedEntity);

        } catch (Exception e) {
            metricsService.recordError();
            logger.error("Failed to create {{domain}} with name: {}", request.getName(), e);
            throw e;
        } finally {
            metricsService.stopCreationTimer(timer);
        }
    }

    @Override
    @Transactional(readOnly = true)
    @Cacheable(value = "{{domain}}s", key = "#id")
    public Optional<{{domainTitleCase}}Response> get{{domainTitleCase}}ById(String id) {
        logger.debug("Fetching {{domain}} with ID: {}", id);

        return {{domain}}Repository.findById(id)
                .map({{domain}}Mapper::toResponse);
    }

    @Override
    @Transactional(readOnly = true)
    @Cacheable(value = "{{domain}}-search", key = "#pageable.pageNumber + '_' + #pageable.pageSize")
    public Page<{{domainTitleCase}}Response> getAll{{domainTitleCase}}s(Pageable pageable) {
        logger.debug("Fetching all {{domain}}s with pagination: {}", pageable);

        return {{domain}}Repository.findAll(pageable)
                .map({{domain}}Mapper::toResponse);
    }

    @Override
    @Transactional(readOnly = true)
    @Cacheable(value = "{{domain}}s", key = "'all'")
    public List<{{domainTitleCase}}Response> getAll{{domainTitleCase}}s() {
        logger.debug("Fetching all {{domain}}s");

        return {{domain}}Mapper.toResponseList({{domain}}Repository.findAll());
    }

    @Override
    @CachePut(value = "{{domain}}s", key = "#id")
    @CacheEvict(value = {"{{domain}}-search", "{{domain}}-count"}, allEntries = true)
    public Optional<{{domainTitleCase}}Response> update{{domainTitleCase}}(String id, {{domainTitleCase}}Request request) {
        Timer.Sample timer = metricsService.startUpdateTimer();
        logger.info("Updating {{domain}} with ID: {}", id);

        try {
            return {{domain}}Repository.findById(id)
                    .map(existingEntity -> {
                        // Validate request using custom validator
                        {{domainTitleCase}}Validator.ValidationResult validationResult = {{domain}}Validator.validateUpdateRequest(id, request);
                        if (!validationResult.isValid()) {
                            throw new IllegalArgumentException(validationResult.getErrorMessage());
                        }

                        // Store previous state for event
                        {{domainTitleCase}} previousEntity = {{domain}}Mapper.copy(existingEntity);

                        // Check if name is being changed and new name doesn't conflict
                        if (!existingEntity.getName().equalsIgnoreCase(request.getName()) &&
                            {{domain}}Repository.existsByNameIgnoreCase(request.getName())) {
                            throw new IllegalArgumentException("{{domainTitleCase}} with name '" + request.getName() + "' already exists");
                        }

                        // Update entity using mapper
                        {{domain}}Mapper.updateEntityFromRequest(request, existingEntity);

                        {{domainTitleCase}} updatedEntity = {{domain}}Repository.save(existingEntity);

                        // Publish domain event
                        eventPublisher.publish{{domainTitleCase}}Updated(previousEntity, updatedEntity);

                        // Record metrics
                        metricsService.recordUpdate();

                        logger.info("Successfully updated {{domain}} with ID: {}", id);
                        return {{domain}}Mapper.toResponse(updatedEntity);
                    });

        } catch (Exception e) {
            metricsService.recordError();
            logger.error("Failed to update {{domain}} with ID: {}", id, e);
            throw e;
        } finally {
            metricsService.stopUpdateTimer(timer);
        }
    }

    @Override
    @CacheEvict(value = {"{{domain}}s", "{{domain}}-search", "{{domain}}-count"}, allEntries = true)
    public boolean delete{{domainTitleCase}}(String id) {
        logger.info("Deleting {{domain}} with ID: {}", id);

        try {
            return {{domain}}Repository.findById(id)
                    .map(entityToDelete -> {
                        // Validate deletion using custom validator
                        {{domainTitleCase}}Validator.ValidationResult validationResult = {{domain}}Validator.validateDeleteRequest(id);
                        if (!validationResult.isValid()) {
                            throw new IllegalArgumentException(validationResult.getErrorMessage());
                        }

                        {{domain}}Repository.deleteById(id);

                        // Publish domain event
                        eventPublisher.publish{{domainTitleCase}}Deleted(entityToDelete);

                        // Record metrics
                        metricsService.recordDeletion();

                        logger.info("Successfully deleted {{domain}} with ID: {}", id);
                        return true;
                    })
                    .orElseGet(() -> {
                        logger.warn("{{domainTitleCase}} with ID {} not found for deletion", id);
                        return false;
                    });

        } catch (Exception e) {
            metricsService.recordError();
            logger.error("Failed to delete {{domain}} with ID: {}", id, e);
            throw e;
        }
    }

    @Override
    @Transactional(readOnly = true)
    @Cacheable(value = "{{domain}}-search", key = "#searchText")
    public List<{{domainTitleCase}}Response> search{{domainTitleCase}}s(String searchText) {
        Timer.Sample timer = metricsService.startSearchTimer();
        logger.debug("Searching {{domain}}s with text: {}", searchText);

        try {
            List<{{domainTitleCase}}> results = {{domain}}Repository.findByNameOrDescriptionContaining(searchText);

            // Record search metrics
            metricsService.recordSearch();
            metricsService.recordBusinessMetric("search_results_count", results.size());

            return {{domain}}Mapper.toResponseList(results);

        } finally {
            metricsService.stopSearchTimer(timer);
        }
    }

    @Override
    @Transactional(readOnly = true)
    @Cacheable(value = "{{domain}}-search", key = "'name:' + #namePattern")
    public List<{{domainTitleCase}}Response> find{{domainTitleCase}}sByName(String namePattern) {
        logger.debug("Finding {{domain}}s by name pattern: {}", namePattern);

        return {{domain}}Mapper.toResponseList(
            {{domain}}Repository.findByNameContainingIgnoreCase(namePattern)
        );
    }

    @Override
    @Transactional(readOnly = true)
    @Cacheable(value = "{{domain}}-search", key = "'created_after:' + #date")
    public List<{{domainTitleCase}}Response> get{{domainTitleCase}}sCreatedAfter(LocalDateTime date) {
        logger.debug("Finding {{domain}}s created after: {}", date);

        return {{domain}}Mapper.toResponseList(
            {{domain}}Repository.findByCreatedAtAfter(date)
        );
    }

    @Override
    @Transactional(readOnly = true)
    @Cacheable(value = "{{domain}}-count", key = "'exists:' + #name")
    public boolean exists{{domainTitleCase}}ByName(String name) {
        logger.debug("Checking if {{domain}} exists with name: {}", name);

        return {{domain}}Repository.existsByNameIgnoreCase(name);
    }

    @Override
    @Transactional(readOnly = true)
    @Cacheable(value = "{{domain}}-count", key = "'count_after:' + #date")
    public long count{{domainTitleCase}}sCreatedAfter(LocalDateTime date) {
        logger.debug("Counting {{domain}}s created after: {}", date);

        return {{domain}}Repository.countByCreatedAtAfter(date);
    }

    @Override
    @Transactional(readOnly = true)
    @Cacheable(value = "{{domain}}s", key = "'active'")
    public List<{{domainTitleCase}}Response> getActive{{domainTitleCase}}s() {
        logger.debug("Fetching active {{domain}}s");

        return {{domain}}Mapper.toResponseList(
            {{domain}}Repository.findActive{{domainTitleCase}}s()
        );
    }

    @Override
    public {{domainTitleCase}}Response convertToResponse({{domainTitleCase}} entity) {
        return {{domain}}Mapper.toResponse(entity);
    }

    @Override
    public {{domainTitleCase}} convertToEntity({{domainTitleCase}}Request request) {
        return {{domain}}Mapper.toEntity(request);
    }

    // ================================
    // Additional Business Logic Methods
    // ================================
    // Add your domain-specific business methods here
    // Custom validation is now handled by {{domainTitleCase}}Validator

    /**
     * Additional business logic can be added here
     * All validation is handled by {{domainTitleCase}}Validator
     */
    // Example:
    // private boolean hasSpecialBusinessRules({{domainTitleCase}}Request request) {
    //     return false; // Implement your specific business logic
    // }
}