package {{packageName}}.security;

import io.github.bucket4j.Bandwidth;
import io.github.bucket4j.Bucket;
import io.github.bucket4j.Bucket4j;
import io.github.bucket4j.Refill;
import org.springframework.cache.CacheManager;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.web.servlet.HandlerInterceptor;
import org.springframework.web.servlet.config.annotation.InterceptorRegistry;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;

import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.time.Duration;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Rate Limiting Configuration for {{serviceNameTitleCase}}
 *
 * Implements token bucket algorithm for API rate limiting.
 * Protects against abuse and ensures fair usage of resources.
 * Generated by Enterprise CLI - customize according to your requirements.
 */
@Configuration
public class RateLimitingConfig implements WebMvcConfigurer {

    private final CacheManager cacheManager;
    private final Map<String, Bucket> buckets = new ConcurrentHashMap<>();

    public RateLimitingConfig(CacheManager cacheManager) {
        this.cacheManager = cacheManager;
    }

    @Override
    public void addInterceptors(InterceptorRegistry registry) {
        registry.addInterceptor(rateLimitingInterceptor())
                .addPathPatterns("/{{domain}}s/**")
                .excludePathPatterns("/{{domain}}s/hello"); // Exclude health check endpoints
    }

    @Bean
    public HandlerInterceptor rateLimitingInterceptor() {
        return new RateLimitingInterceptor();
    }

    /**
     * Rate Limiting Interceptor
     */
    public class RateLimitingInterceptor implements HandlerInterceptor {

        @Override
        public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler) {
            String clientId = getClientIdentifier(request);
            Bucket bucket = getBucket(clientId, request);

            if (bucket.tryConsume(1)) {
                // Add rate limit headers for client information
                addRateLimitHeaders(response, bucket);
                return true;
            } else {
                // Rate limit exceeded
                response.setStatus(429); // Too Many Requests
                response.setHeader("Content-Type", "application/json");
                response.setHeader("Retry-After", "60");

                addRateLimitHeaders(response, bucket);

                try {
                    response.getWriter().write(
                        "{\"error\":\"Rate limit exceeded\",\"message\":\"Too many requests. Please try again later.\",\"code\":\"RATE_LIMIT_EXCEEDED\"}"
                    );
                } catch (Exception e) {
                    // Log error
                }
                return false;
            }
        }

        private String getClientIdentifier(HttpServletRequest request) {
            // Try to get user ID from authentication context
            String userId = getUserIdFromAuth(request);
            if (userId != null) {
                return "user:" + userId;
            }

            // Fall back to IP address
            String clientIp = getClientIpAddress(request);
            return "ip:" + clientIp;
        }

        private String getUserIdFromAuth(HttpServletRequest request) {
            // Extract user ID from JWT token or authentication context
            // This is a placeholder - implement based on your authentication mechanism
            return request.getHeader("X-User-ID");
        }

        private String getClientIpAddress(HttpServletRequest request) {
            String xForwardedFor = request.getHeader("X-Forwarded-For");
            if (xForwardedFor != null && !xForwardedFor.isEmpty()) {
                return xForwardedFor.split(",")[0].trim();
            }

            String xRealIp = request.getHeader("X-Real-IP");
            if (xRealIp != null && !xRealIp.isEmpty()) {
                return xRealIp;
            }

            return request.getRemoteAddr();
        }

        private Bucket getBucket(String clientId, HttpServletRequest request) {
            return buckets.computeIfAbsent(clientId, k -> createBucket(clientId, request));
        }

        private Bucket createBucket(String clientId, HttpServletRequest request) {
            RateLimitConfig config = getRateLimitConfig(clientId, request);

            Bandwidth bandwidth = Bandwidth.classic(
                config.getCapacity(),
                Refill.intervally(config.getRefillTokens(), config.getRefillDuration())
            );

            return Bucket4j.builder()
                    .addLimit(bandwidth)
                    .build();
        }

        private RateLimitConfig getRateLimitConfig(String clientId, HttpServletRequest request) {
            // Different rate limits based on client type and endpoint

            if (clientId.startsWith("user:")) {
                // Authenticated users get higher limits
                if (isWriteOperation(request)) {
                    return new RateLimitConfig(20, 20, Duration.ofMinutes(1)); // 20 writes per minute
                } else {
                    return new RateLimitConfig(100, 100, Duration.ofMinutes(1)); // 100 reads per minute
                }
            } else {
                // IP-based limits (anonymous users)
                if (isWriteOperation(request)) {
                    return new RateLimitConfig(5, 5, Duration.ofMinutes(1)); // 5 writes per minute
                } else {
                    return new RateLimitConfig(30, 30, Duration.ofMinutes(1)); // 30 reads per minute
                }
            }
        }

        private boolean isWriteOperation(HttpServletRequest request) {
            String method = request.getMethod();
            return "POST".equals(method) || "PUT".equals(method) || "DELETE".equals(method) || "PATCH".equals(method);
        }

        private void addRateLimitHeaders(HttpServletResponse response, Bucket bucket) {
            long availableTokens = bucket.getAvailableTokens();
            response.setHeader("X-RateLimit-Remaining", String.valueOf(availableTokens));
            response.setHeader("X-RateLimit-Retry-After", "60");
        }
    }

    /**
     * Rate Limit Configuration
     */
    public static class RateLimitConfig {
        private final long capacity;
        private final long refillTokens;
        private final Duration refillDuration;

        public RateLimitConfig(long capacity, long refillTokens, Duration refillDuration) {
            this.capacity = capacity;
            this.refillTokens = refillTokens;
            this.refillDuration = refillDuration;
        }

        public long getCapacity() {
            return capacity;
        }

        public long getRefillTokens() {
            return refillTokens;
        }

        public Duration getRefillDuration() {
            return refillDuration;
        }
    }

    /**
     * Advanced Rate Limiting Strategies
     */
    public static class AdvancedRateLimitStrategies {

        /**
         * Sliding window rate limiter
         */
        public static Bucket createSlidingWindowBucket(int requestsPerWindow, Duration windowDuration) {
            Bandwidth bandwidth = Bandwidth.simple(requestsPerWindow, windowDuration);
            return Bucket4j.builder().addLimit(bandwidth).build();
        }

        /**
         * Burst-aware rate limiter
         */
        public static Bucket createBurstAwareBucket(int burstCapacity, int sustainedRate, Duration period) {
            Bandwidth burstBandwidth = Bandwidth.classic(burstCapacity, Refill.intervally(sustainedRate, period));
            return Bucket4j.builder().addLimit(burstBandwidth).build();
        }

        /**
         * Hierarchical rate limiter (per-user and global limits)
         */
        public static Bucket createHierarchicalBucket(int userLimit, int globalLimit, Duration period) {
            Bandwidth userBandwidth = Bandwidth.classic(userLimit, Refill.intervally(userLimit, period));
            Bandwidth globalBandwidth = Bandwidth.classic(globalLimit, Refill.intervally(globalLimit, period));

            return Bucket4j.builder()
                    .addLimit(userBandwidth)
                    .addLimit(globalBandwidth)
                    .build();
        }
    }

    /**
     * Rate Limiting Metrics
     */
    @Bean
    public RateLimitingMetrics rateLimitingMetrics() {
        return new RateLimitingMetrics();
    }

    public static class RateLimitingMetrics {

        public void recordRateLimitHit(String clientId, String endpoint) {
            // Record rate limit hit for monitoring
            // This would typically use Micrometer metrics
        }

        public void recordRateLimitExceeded(String clientId, String endpoint) {
            // Record rate limit exceeded for alerting
        }

        public void recordBucketUsage(String clientId, long remainingTokens, long capacity) {
            // Record bucket usage statistics
        }
    }
}