package {{packageName}}.security;

import {{packageName}}.audit.AuditService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.event.EventListener;
import org.springframework.security.authentication.event.AbstractAuthenticationEvent;
import org.springframework.security.authentication.event.AuthenticationFailureBadCredentialsEvent;
import org.springframework.security.authentication.event.AuthenticationSuccessEvent;
import org.springframework.security.authorization.event.AuthorizationDeniedEvent;
import org.springframework.security.core.Authentication;
import org.springframework.stereotype.Component;

import jakarta.servlet.http.HttpServletRequest;

/**
 * Security Event Listener for {{serviceNameTitleCase}}
 *
 * Captures and audits security events for compliance and monitoring.
 * Integrates with audit system for comprehensive security tracking.
 * Generated by Enterprise CLI - customize according to your security requirements.
 */
@Component
public class SecurityEventListener {

    private final AuditService auditService;
    private final HttpServletRequest request;

    @Autowired
    public SecurityEventListener(AuditService auditService, HttpServletRequest request) {
        this.auditService = auditService;
        this.request = request;
    }

    /**
     * Handle successful authentication events
     */
    @EventListener
    public void handleAuthenticationSuccess(AuthenticationSuccessEvent event) {
        Authentication authentication = event.getAuthentication();
        String username = authentication.getName();
        String authType = authentication.getClass().getSimpleName();

        auditService.auditAuthentication(username, authType, true, null);
    }

    /**
     * Handle failed authentication events
     */
    @EventListener
    public void handleAuthenticationFailure(AuthenticationFailureBadCredentialsEvent event) {
        String username = event.getAuthentication().getName();
        String authType = event.getAuthentication().getClass().getSimpleName();
        String failureReason = event.getException().getMessage();

        auditService.auditAuthentication(username, authType, false, failureReason);

        // Log potential security threats
        if (isRepeatedFailure(username)) {
            auditService.auditSecurityViolation(
                "REPEATED_LOGIN_FAILURES",
                "Multiple failed login attempts for user: " + username,
                "HIGH"
            );
        }
    }

    /**
     * Handle authorization denied events
     */
    @EventListener
    public void handleAuthorizationDenied(AuthorizationDeniedEvent event) {
        String username = event.getAuthentication().get().getName();
        String resource = extractResourceFromEvent(event);
        String action = extractActionFromEvent(event);
        String denialReason = "Insufficient privileges";

        auditService.auditAuthorization(resource, action, false, denialReason);

        // Check for privilege escalation attempts
        if (isPrivilegeEscalationAttempt(event)) {
            auditService.auditSecurityViolation(
                "PRIVILEGE_ESCALATION_ATTEMPT",
                "User " + username + " attempted to access restricted resource: " + resource,
                "CRITICAL"
            );
        }
    }

    /**
     * Handle session creation events
     */
    public void handleSessionCreated(String sessionId, String username) {
        auditService.auditAuthentication(username, "SESSION_CREATED", true, null);
    }

    /**
     * Handle session destruction events
     */
    public void handleSessionDestroyed(String sessionId, String username) {
        auditService.auditAuthentication(username, "SESSION_DESTROYED", true, null);
    }

    /**
     * Handle suspicious activity
     */
    public void handleSuspiciousActivity(String activityType, String description, String severity) {
        auditService.auditSecurityViolation(activityType, description, severity);
    }

    // Helper methods

    private boolean isRepeatedFailure(String username) {
        // Check if there have been multiple recent failures for this user
        // This would typically query the audit log or maintain a failure cache
        return false; // Placeholder implementation
    }

    private String extractResourceFromEvent(AuthorizationDeniedEvent event) {
        // Extract the resource being accessed from the authorization event
        return event.getAuthorizationDecision().toString();
    }

    private String extractActionFromEvent(AuthorizationDeniedEvent event) {
        // Extract the action being attempted from the authorization event
        return "ACCESS";
    }

    private boolean isPrivilegeEscalationAttempt(AuthorizationDeniedEvent event) {
        // Determine if this represents a privilege escalation attempt
        // This would analyze the requested resource and user's current privileges
        return false; // Placeholder implementation
    }

    /**
     * Security threat detection
     */
    public static class ThreatDetector {

        /**
         * Detect SQL injection attempts
         */
        public static boolean detectSQLInjection(String input) {
            if (input == null) return false;

            String lowercaseInput = input.toLowerCase();
            String[] sqlKeywords = {"select", "insert", "update", "delete", "drop", "union", "script"};

            for (String keyword : sqlKeywords) {
                if (lowercaseInput.contains(keyword)) {
                    return true;
                }
            }
            return false;
        }

        /**
         * Detect XSS attempts
         */
        public static boolean detectXSS(String input) {
            if (input == null) return false;

            String lowercaseInput = input.toLowerCase();
            return lowercaseInput.contains("<script") ||
                   lowercaseInput.contains("javascript:") ||
                   lowercaseInput.contains("onerror=") ||
                   lowercaseInput.contains("onload=");
        }

        /**
         * Detect path traversal attempts
         */
        public static boolean detectPathTraversal(String input) {
            if (input == null) return false;

            return input.contains("../") ||
                   input.contains("..\\") ||
                   input.contains("%2e%2e") ||
                   input.contains("..%2f") ||
                   input.contains("..%5c");
        }
    }
}