package {{packageName}}.integration;

import {{packageName}}.dto.{{domainTitleCase}}Request;
import {{packageName}}.dto.{{domainTitleCase}}Response;
import {{packageName}}.entity.{{domainTitleCase}};
import {{packageName}}.repository.{{domainTitleCase}}Repository;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureWebMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.transaction.annotation.Transactional;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import static org.assertj.core.api.Assertions.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

/**
 * Integration tests for {{domainTitleCase}} functionality
 *
 * Uses TestContainers with real PostgreSQL database for comprehensive testing.
 * Tests complete application stack from HTTP requests to database persistence.
 * Generated by Enterprise CLI - customize according to your business requirements.
 */
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@AutoConfigureWebMvc
@Testcontainers
@ActiveProfiles("integration-test")
@DisplayName("{{domainTitleCase}} Integration Tests")
class {{domainTitleCase}}IntegrationTest {

    @Container
    static PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>("postgres:15-alpine")
            .withDatabaseName("{{serviceName}}_integration_test")
            .withUsername("test_user")
            .withPassword("test_password")
            .withReuse(true);

    @DynamicPropertySource
    static void configureProperties(DynamicPropertyRegistry registry) {
        registry.add("spring.datasource.url", postgres::getJdbcUrl);
        registry.add("spring.datasource.username", postgres::getUsername);
        registry.add("spring.datasource.password", postgres::getPassword);
        registry.add("spring.jpa.hibernate.ddl-auto", () -> "create-drop");
        registry.add("spring.flyway.enabled", () -> "false");
    }

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private ObjectMapper objectMapper;

    @Autowired
    private {{domainTitleCase}}Repository {{domain}}Repository;

    private {{domainTitleCase}}Request test{{domainTitleCase}}Request;

    @BeforeEach
    void setUp() {
        // Clear database before each test
        {{domain}}Repository.deleteAll();

        // Setup test data
        test{{domainTitleCase}}Request = new {{domainTitleCase}}Request();
        test{{domainTitleCase}}Request.setName("Integration Test {{domainTitleCase}}");
        test{{domainTitleCase}}Request.setDescription("Integration test description");
    }

    @Test
    @DisplayName("Should create, retrieve, update and delete {{domain}} successfully")
    @Transactional
    void shouldPerformFullCrudOperationsSuccessfully() throws Exception {
        // CREATE: Create a new {{domain}}
        String createResponse = mockMvc.perform(post("/{{domain}}s")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(test{{domainTitleCase}}Request)))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.name").value("Integration Test {{domainTitleCase}}"))
                .andExpect(jsonPath("$.description").value("Integration test description"))
                .andExpect(jsonPath("$.id").exists())
                .andReturn()
                .getResponse()
                .getContentAsString();

        {{domainTitleCase}}Response created{{domainTitleCase}} = objectMapper.readValue(createResponse, {{domainTitleCase}}Response.class);
        String {{domain}}Id = created{{domainTitleCase}}.getId();

        // Verify {{domain}} was persisted to database
        assertThat({{domain}}Repository.findById({{domain}}Id)).isPresent();

        // READ: Retrieve the created {{domain}}
        mockMvc.perform(get("/{{domain}}s/{id}", {{domain}}Id))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.id").value({{domain}}Id))
                .andExpect(jsonPath("$.name").value("Integration Test {{domainTitleCase}}"));

        // READ: Get all {{domain}}s
        mockMvc.perform(get("/{{domain}}s"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$").isArray())
                .andExpect(jsonPath("$.length()").value(1))
                .andExpect(jsonPath("$[0].id").value({{domain}}Id));

        // UPDATE: Update the {{domain}}
        {{domainTitleCase}}Request updateRequest = new {{domainTitleCase}}Request();
        updateRequest.setName("Updated Integration Test {{domainTitleCase}}");
        updateRequest.setDescription("Updated integration test description");

        mockMvc.perform(put("/{{domain}}s/{id}", {{domain}}Id)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(updateRequest)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.id").value({{domain}}Id))
                .andExpect(jsonPath("$.name").value("Updated Integration Test {{domainTitleCase}}"))
                .andExpect(jsonPath("$.description").value("Updated integration test description"));

        // Verify update was persisted
        {{domainTitleCase}} updated{{domainTitleCase}} = {{domain}}Repository.findById({{domain}}Id).orElseThrow();
        assertThat(updated{{domainTitleCase}}.getName()).isEqualTo("Updated Integration Test {{domainTitleCase}}");

        // DELETE: Delete the {{domain}}
        mockMvc.perform(delete("/{{domain}}s/{id}", {{domain}}Id))
                .andExpect(status().isNoContent());

        // Verify deletion was persisted
        assertThat({{domain}}Repository.findById({{domain}}Id)).isEmpty();

        // Verify {{domain}} no longer accessible
        mockMvc.perform(get("/{{domain}}s/{id}", {{domain}}Id))
                .andExpect(status().isNotFound());
    }

    @Test
    @DisplayName("Should handle search functionality end-to-end")
    void shouldHandleSearchFunctionalityEndToEnd() throws Exception {
        // Create test data
        {{domainTitleCase}}Request first{{domainTitleCase}} = new {{domainTitleCase}}Request();
        first{{domainTitleCase}}.setName("Apple Product");
        first{{domainTitleCase}}.setDescription("Fresh apple from orchard");

        {{domainTitleCase}}Request second{{domainTitleCase}} = new {{domainTitleCase}}Request();
        second{{domainTitleCase}}.setName("Orange Product");
        second{{domainTitleCase}}.setDescription("Sweet orange fruit");

        // Create both {{domain}}s
        mockMvc.perform(post("/{{domain}}s")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(first{{domainTitleCase}})))
                .andExpect(status().isCreated());

        mockMvc.perform(post("/{{domain}}s")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(second{{domainTitleCase}})))
                .andExpect(status().isCreated());

        // Search by name
        mockMvc.perform(get("/{{domain}}s/search")
                        .param("searchText", "Apple"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$").isArray())
                .andExpect(jsonPath("$.length()").value(1))
                .andExpect(jsonPath("$[0].name").value("Apple Product"));

        // Search by description
        mockMvc.perform(get("/{{domain}}s/search")
                        .param("searchText", "fruit"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$").isArray())
                .andExpect(jsonPath("$.length()").value(1))
                .andExpect(jsonPath("$[0].name").value("Orange Product"));

        // Search for common term
        mockMvc.perform(get("/{{domain}}s/search")
                        .param("searchText", "Product"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$").isArray())
                .andExpect(jsonPath("$.length()").value(2));

        // Search with no results
        mockMvc.perform(get("/{{domain}}s/search")
                        .param("searchText", "NonExistent"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$").isArray())
                .andExpect(jsonPath("$.length()").value(0));
    }

    @Test
    @DisplayName("Should handle pagination correctly")
    void shouldHandlePaginationCorrectly() throws Exception {
        // Create multiple {{domain}}s
        for (int i = 1; i <= 15; i++) {
            {{domainTitleCase}}Request request = new {{domainTitleCase}}Request();
            request.setName("{{domainTitleCase}} " + i);
            request.setDescription("Description for {{domain}} " + i);

            mockMvc.perform(post("/{{domain}}s")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content(objectMapper.writeValueAsString(request)))
                    .andExpect(status().isCreated());
        }

        // Test first page
        mockMvc.perform(get("/{{domain}}s/paged")
                        .param("page", "0")
                        .param("size", "5"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.content").isArray())
                .andExpect(jsonPath("$.content.length()").value(5))
                .andExpect(jsonPath("$.totalElements").value(15))
                .andExpect(jsonPath("$.totalPages").value(3))
                .andExpect(jsonPath("$.first").value(true))
                .andExpect(jsonPath("$.last").value(false));

        // Test middle page
        mockMvc.perform(get("/{{domain}}s/paged")
                        .param("page", "1")
                        .param("size", "5"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.content.length()").value(5))
                .andExpect(jsonPath("$.first").value(false))
                .andExpect(jsonPath("$.last").value(false));

        // Test last page
        mockMvc.perform(get("/{{domain}}s/paged")
                        .param("page", "2")
                        .param("size", "5"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.content.length()").value(5))
                .andExpect(jsonPath("$.first").value(false))
                .andExpect(jsonPath("$.last").value(true));
    }

    @Test
    @DisplayName("Should enforce unique constraint on {{domain}} name")
    void shouldEnforceUniqueConstraintOn{{domainTitleCase}}Name() throws Exception {
        // Create first {{domain}}
        mockMvc.perform(post("/{{domain}}s")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(test{{domainTitleCase}}Request)))
                .andExpect(status().isCreated());

        // Try to create {{domain}} with same name
        {{domainTitleCase}}Request duplicateRequest = new {{domainTitleCase}}Request();
        duplicateRequest.setName("Integration Test {{domainTitleCase}}"); // Same name
        duplicateRequest.setDescription("Different description");

        mockMvc.perform(post("/{{domain}}s")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(duplicateRequest)))
                .andExpect(status().isConflict());

        // Verify only one {{domain}} exists
        assertThat({{domain}}Repository.count()).isEqualTo(1);
    }

    @Test
    @DisplayName("Should handle validation errors properly")
    void shouldHandleValidationErrorsProperly() throws Exception {
        // Test empty name
        {{domainTitleCase}}Request invalidRequest = new {{domainTitleCase}}Request();
        invalidRequest.setName(""); // Invalid: empty name
        invalidRequest.setDescription("Valid description");

        mockMvc.perform(post("/{{domain}}s")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(invalidRequest)))
                .andExpect(status().isBadRequest());

        // Test name too short
        invalidRequest.setName("A"); // Invalid: too short
        mockMvc.perform(post("/{{domain}}s")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(invalidRequest)))
                .andExpect(status().isBadRequest());

        // Test description too long
        invalidRequest.setName("Valid Name");
        invalidRequest.setDescription("x".repeat(501)); // Invalid: too long

        mockMvc.perform(post("/{{domain}}s")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(invalidRequest)))
                .andExpect(status().isBadRequest());

        // Verify no {{domain}}s were created
        assertThat({{domain}}Repository.count()).isEqualTo(0);
    }

    @Test
    @DisplayName("Should handle concurrent access correctly")
    void shouldHandleConcurrentAccessCorrectly() throws Exception {
        // Create a {{domain}}
        String createResponse = mockMvc.perform(post("/{{domain}}s")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(test{{domainTitleCase}}Request)))
                .andExpect(status().isCreated())
                .andReturn()
                .getResponse()
                .getContentAsString();

        {{domainTitleCase}}Response created{{domainTitleCase}} = objectMapper.readValue(createResponse, {{domainTitleCase}}Response.class);
        String {{domain}}Id = created{{domainTitleCase}}.getId();

        // Simulate concurrent updates (optimistic locking should handle this)
        {{domainTitleCase}}Request updateRequest1 = new {{domainTitleCase}}Request();
        updateRequest1.setName("Update 1");
        updateRequest1.setDescription("First concurrent update");

        {{domainTitleCase}}Request updateRequest2 = new {{domainTitleCase}}Request();
        updateRequest2.setName("Update 2");
        updateRequest2.setDescription("Second concurrent update");

        // First update should succeed
        mockMvc.perform(put("/{{domain}}s/{id}", {{domain}}Id)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(updateRequest1)))
                .andExpect(status().isOk());

        // Second update should also succeed (in this simple case)
        mockMvc.perform(put("/{{domain}}s/{id}", {{domain}}Id)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(updateRequest2)))
                .andExpect(status().isOk());

        // Verify final state
        {{domainTitleCase}} final{{domainTitleCase}} = {{domain}}Repository.findById({{domain}}Id).orElseThrow();
        assertThat(final{{domainTitleCase}}.getName()).isEqualTo("Update 2");
        assertThat(final{{domainTitleCase}}.getVersion()).isGreaterThan(0L);
    }

    @Test
    @DisplayName("Should maintain audit fields correctly")
    void shouldMaintainAuditFieldsCorrectly() throws Exception {
        // Create {{domain}}
        String createResponse = mockMvc.perform(post("/{{domain}}s")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(test{{domainTitleCase}}Request)))
                .andExpect(status().isCreated())
                .andReturn()
                .getResponse()
                .getContentAsString();

        {{domainTitleCase}}Response created{{domainTitleCase}} = objectMapper.readValue(createResponse, {{domainTitleCase}}Response.class);

        // Verify audit fields are set
        assertThat(created{{domainTitleCase}}.getCreatedAt()).isNotNull();
        assertThat(created{{domainTitleCase}}.getUpdatedAt()).isNotNull();

        // Wait a moment to ensure different timestamps
        Thread.sleep(10);

        // Update {{domain}}
        {{domainTitleCase}}Request updateRequest = new {{domainTitleCase}}Request();
        updateRequest.setName("Updated Name");
        updateRequest.setDescription("Updated description");

        String updateResponse = mockMvc.perform(put("/{{domain}}s/{id}", created{{domainTitleCase}}.getId())
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(updateRequest)))
                .andExpect(status().isOk())
                .andReturn()
                .getResponse()
                .getContentAsString();

        {{domainTitleCase}}Response updated{{domainTitleCase}} = objectMapper.readValue(updateResponse, {{domainTitleCase}}Response.class);

        // Verify audit fields are maintained correctly
        assertThat(updated{{domainTitleCase}}.getCreatedAt()).isEqualTo(created{{domainTitleCase}}.getCreatedAt());
        assertThat(updated{{domainTitleCase}}.getUpdatedAt()).isAfter(created{{domainTitleCase}}.getUpdatedAt());
    }
}