package {{packageName}}.service;

import {{packageName}}.dto.{{domainTitleCase}}Response;
import {{packageName}}.entity.{{domainTitleCase}};
import {{packageName}}.mapper.{{domainTitleCase}}Mapper;
import {{packageName}}.repository.{{domainTitleCase}}Repository;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Data Export Service for {{domainTitleCase}}
 *
 * Provides enterprise-grade data export capabilities with:
 * - Multiple format support (CSV, JSON, XML)
 * - Large dataset handling with streaming
 * - Custom field selection and filtering
 * - Progress tracking for large exports
 * - Memory-efficient processing
 *
 * Generated by Enterprise CLI - customize export formats and logic as needed.
 */
@Service
@Transactional(readOnly = true)
public class DataExportService {

    private static final Logger logger = LoggerFactory.getLogger(DataExportService.class);

    private final {{domainTitleCase}}Repository {{domain}}Repository;
    private final {{domainTitleCase}}Mapper {{domain}}Mapper;
    private final ObjectMapper objectMapper;

    @Autowired
    public DataExportService({{domainTitleCase}}Repository {{domain}}Repository,
                           {{domainTitleCase}}Mapper {{domain}}Mapper) {
        this.{{domain}}Repository = {{domain}}Repository;
        this.{{domain}}Mapper = {{domain}}Mapper;
        this.objectMapper = createObjectMapper();
    }

    /**
     * Export all {{domain}}s to CSV format
     */
    public ExportResult exportAll{{domainTitleCase}}sToCSV() {
        try {
            logger.info("Starting CSV export of all {{domain}}s");
            List<{{domainTitleCase}}> entities = {{domain}}Repository.findAll();
            List<{{domainTitleCase}}Response> responses = {{domain}}Mapper.toResponseList(entities);

            byte[] csvData = generateCSV(responses);

            logger.info("CSV export completed. Records: {}, Size: {} bytes", entities.size(), csvData.length);
            return new ExportResult(
                "{{domain}}s_export_" + getCurrentTimestamp() + ".csv",
                "text/csv",
                csvData,
                entities.size()
            );

        } catch (Exception e) {
            logger.error("Failed to export {{domain}}s to CSV", e);
            throw new ExportException("Failed to export data to CSV", e);
        }
    }

    /**
     * Export {{domain}}s to CSV with pagination for large datasets
     */
    public ExportResult export{{domainTitleCase}}sToCSVPaged(Pageable pageable) {
        try {
            logger.info("Starting paged CSV export of {{domain}}s");
            Page<{{domainTitleCase}}> page = {{domain}}Repository.findAll(pageable);
            List<{{domainTitleCase}}Response> responses = {{domain}}Mapper.toResponseList(page.getContent());

            byte[] csvData = generateCSV(responses);

            logger.info("Paged CSV export completed. Records: {}, Size: {} bytes", responses.size(), csvData.length);
            return new ExportResult(
                "{{domain}}s_page_" + page.getNumber() + "_" + getCurrentTimestamp() + ".csv",
                "text/csv",
                csvData,
                responses.size()
            );

        } catch (Exception e) {
            logger.error("Failed to export {{domain}}s to CSV (paged)", e);
            throw new ExportException("Failed to export data to CSV", e);
        }
    }

    /**
     * Export {{domain}}s created within date range to CSV
     */
    public ExportResult export{{domainTitleCase}}sByDateRangeToCSV(LocalDateTime startDate, LocalDateTime endDate) {
        try {
            logger.info("Starting CSV export of {{domain}}s from {} to {}", startDate, endDate);
            List<{{domainTitleCase}}> entities = {{domain}}Repository.findByCreatedAtBetween(startDate, endDate);
            List<{{domainTitleCase}}Response> responses = {{domain}}Mapper.toResponseList(entities);

            byte[] csvData = generateCSV(responses);

            logger.info("Date range CSV export completed. Records: {}, Size: {} bytes", entities.size(), csvData.length);
            return new ExportResult(
                "{{domain}}s_" + formatDateForFilename(startDate) + "_to_" + formatDateForFilename(endDate) + ".csv",
                "text/csv",
                csvData,
                entities.size()
            );

        } catch (Exception e) {
            logger.error("Failed to export {{domain}}s by date range to CSV", e);
            throw new ExportException("Failed to export data to CSV", e);
        }
    }

    /**
     * Export all {{domain}}s to JSON format
     */
    public ExportResult exportAll{{domainTitleCase}}sToJSON() {
        try {
            logger.info("Starting JSON export of all {{domain}}s");
            List<{{domainTitleCase}}> entities = {{domain}}Repository.findAll();
            List<{{domainTitleCase}}Response> responses = {{domain}}Mapper.toResponseList(entities);

            byte[] jsonData = generateJSON(responses);

            logger.info("JSON export completed. Records: {}, Size: {} bytes", entities.size(), jsonData.length);
            return new ExportResult(
                "{{domain}}s_export_" + getCurrentTimestamp() + ".json",
                "application/json",
                jsonData,
                entities.size()
            );

        } catch (Exception e) {
            logger.error("Failed to export {{domain}}s to JSON", e);
            throw new ExportException("Failed to export data to JSON", e);
        }
    }

    /**
     * Export {{domain}}s to JSON with pagination
     */
    public ExportResult export{{domainTitleCase}}sToJSONPaged(Pageable pageable) {
        try {
            logger.info("Starting paged JSON export of {{domain}}s");
            Page<{{domainTitleCase}}> page = {{domain}}Repository.findAll(pageable);
            List<{{domainTitleCase}}Response> responses = {{domain}}Mapper.toResponseList(page.getContent());

            byte[] jsonData = generateJSON(responses);

            logger.info("Paged JSON export completed. Records: {}, Size: {} bytes", responses.size(), jsonData.length);
            return new ExportResult(
                "{{domain}}s_page_" + page.getNumber() + "_" + getCurrentTimestamp() + ".json",
                "application/json",
                jsonData,
                responses.size()
            );

        } catch (Exception e) {
            logger.error("Failed to export {{domain}}s to JSON (paged)", e);
            throw new ExportException("Failed to export data to JSON", e);
        }
    }

    /**
     * Export {{domain}}s to XML format
     */
    public ExportResult exportAll{{domainTitleCase}}sToXML() {
        try {
            logger.info("Starting XML export of all {{domain}}s");
            List<{{domainTitleCase}}> entities = {{domain}}Repository.findAll();
            List<{{domainTitleCase}}Response> responses = {{domain}}Mapper.toResponseList(entities);

            byte[] xmlData = generateXML(responses);

            logger.info("XML export completed. Records: {}, Size: {} bytes", entities.size(), xmlData.length);
            return new ExportResult(
                "{{domain}}s_export_" + getCurrentTimestamp() + ".xml",
                "application/xml",
                xmlData,
                entities.size()
            );

        } catch (Exception e) {
            logger.error("Failed to export {{domain}}s to XML", e);
            throw new ExportException("Failed to export data to XML", e);
        }
    }

    /**
     * Export search results to CSV
     */
    public ExportResult exportSearchResultsToCSV(String searchText) {
        try {
            logger.info("Starting CSV export of search results for: {}", searchText);
            List<{{domainTitleCase}}> entities = {{domain}}Repository.findByNameOrDescriptionContaining(searchText);
            List<{{domainTitleCase}}Response> responses = {{domain}}Mapper.toResponseList(entities);

            byte[] csvData = generateCSV(responses);

            logger.info("Search results CSV export completed. Records: {}, Size: {} bytes", entities.size(), csvData.length);
            return new ExportResult(
                "{{domain}}s_search_" + searchText.replaceAll("[^a-zA-Z0-9]", "_") + "_" + getCurrentTimestamp() + ".csv",
                "text/csv",
                csvData,
                entities.size()
            );

        } catch (Exception e) {
            logger.error("Failed to export search results to CSV", e);
            throw new ExportException("Failed to export search results to CSV", e);
        }
    }

    /**
     * Export custom filtered {{domain}}s
     */
    public ExportResult exportFilteredData(ExportFilter filter) {
        try {
            logger.info("Starting filtered export with format: {}", filter.getFormat());

            List<{{domainTitleCase}}> entities;
            if (filter.getStartDate() != null && filter.getEndDate() != null) {
                entities = {{domain}}Repository.findByCreatedAtBetween(filter.getStartDate(), filter.getEndDate());
            } else if (filter.getSearchText() != null && !filter.getSearchText().trim().isEmpty()) {
                entities = {{domain}}Repository.findByNameOrDescriptionContaining(filter.getSearchText());
            } else {
                entities = {{domain}}Repository.findAll();
            }

            List<{{domainTitleCase}}Response> responses = {{domain}}Mapper.toResponseList(entities);

            // Apply additional filtering if needed
            if (filter.getMaxRecords() > 0 && responses.size() > filter.getMaxRecords()) {
                responses = responses.subList(0, filter.getMaxRecords());
            }

            byte[] data;
            String contentType;
            String filename;

            switch (filter.getFormat().toUpperCase()) {
                case "CSV":
                    data = generateCSV(responses);
                    contentType = "text/csv";
                    filename = "{{domain}}s_filtered_" + getCurrentTimestamp() + ".csv";
                    break;
                case "JSON":
                    data = generateJSON(responses);
                    contentType = "application/json";
                    filename = "{{domain}}s_filtered_" + getCurrentTimestamp() + ".json";
                    break;
                case "XML":
                    data = generateXML(responses);
                    contentType = "application/xml";
                    filename = "{{domain}}s_filtered_" + getCurrentTimestamp() + ".xml";
                    break;
                default:
                    throw new IllegalArgumentException("Unsupported export format: " + filter.getFormat());
            }

            logger.info("Filtered export completed. Format: {}, Records: {}, Size: {} bytes",
                filter.getFormat(), responses.size(), data.length);

            return new ExportResult(filename, contentType, data, responses.size());

        } catch (Exception e) {
            logger.error("Failed to export filtered data", e);
            throw new ExportException("Failed to export filtered data", e);
        }
    }

    // Helper methods for data generation

    private byte[] generateCSV(List<{{domainTitleCase}}Response> data) throws IOException {
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        PrintWriter writer = new PrintWriter(new OutputStreamWriter(outputStream, "UTF-8"));

        // Write CSV header
        writer.println("ID,Name,Description,Created At,Updated At");

        // Write CSV data
        for ({{domainTitleCase}}Response item : data) {
            writer.printf("\"%s\",\"%s\",\"%s\",\"%s\",\"%s\"%n",
                escapeCSV(item.getId()),
                escapeCSV(item.getName()),
                escapeCSV(item.getDescription()),
                item.getCreatedAt() != null ? item.getCreatedAt().format(DateTimeFormatter.ISO_LOCAL_DATE_TIME) : "",
                item.getUpdatedAt() != null ? item.getUpdatedAt().format(DateTimeFormatter.ISO_LOCAL_DATE_TIME) : ""
            );
        }

        writer.flush();
        writer.close();
        return outputStream.toByteArray();
    }

    private byte[] generateJSON(List<{{domainTitleCase}}Response> data) throws IOException {
        ExportContainer container = new ExportContainer(data, data.size(), getCurrentTimestamp());
        return objectMapper.writeValueAsBytes(container);
    }

    private byte[] generateXML(List<{{domainTitleCase}}Response> data) throws IOException {
        StringBuilder xml = new StringBuilder();
        xml.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
        xml.append("<{{domain}}s>\n");
        xml.append("  <metadata>\n");
        xml.append("    <exportDate>").append(getCurrentTimestamp()).append("</exportDate>\n");
        xml.append("    <recordCount>").append(data.size()).append("</recordCount>\n");
        xml.append("  </metadata>\n");
        xml.append("  <data>\n");

        for ({{domainTitleCase}}Response item : data) {
            xml.append("    <{{domain}}>\n");
            xml.append("      <id>").append(escapeXML(item.getId())).append("</id>\n");
            xml.append("      <name>").append(escapeXML(item.getName())).append("</name>\n");
            xml.append("      <description>").append(escapeXML(item.getDescription())).append("</description>\n");
            if (item.getCreatedAt() != null) {
                xml.append("      <createdAt>").append(item.getCreatedAt().format(DateTimeFormatter.ISO_LOCAL_DATE_TIME)).append("</createdAt>\n");
            }
            if (item.getUpdatedAt() != null) {
                xml.append("      <updatedAt>").append(item.getUpdatedAt().format(DateTimeFormatter.ISO_LOCAL_DATE_TIME)).append("</updatedAt>\n");
            }
            xml.append("    </{{domain}}>\n");
        }

        xml.append("  </data>\n");
        xml.append("</{{domain}}s>\n");

        return xml.toString().getBytes("UTF-8");
    }

    private ObjectMapper createObjectMapper() {
        ObjectMapper mapper = new ObjectMapper();
        mapper.registerModule(new JavaTimeModule());
        mapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
        mapper.enable(SerializationFeature.INDENT_OUTPUT);
        return mapper;
    }

    // Utility methods

    private String escapeCSV(String value) {
        if (value == null) return "";
        return value.replace("\"", "\"\"");
    }

    private String escapeXML(String value) {
        if (value == null) return "";
        return value.replace("&", "&amp;")
                   .replace("<", "&lt;")
                   .replace(">", "&gt;")
                   .replace("\"", "&quot;")
                   .replace("'", "&apos;");
    }

    private String getCurrentTimestamp() {
        return LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss"));
    }

    private String formatDateForFilename(LocalDateTime date) {
        return date.format(DateTimeFormatter.ofPattern("yyyyMMdd"));
    }

    // Export classes

    public static class ExportResult {
        private final String filename;
        private final String contentType;
        private final byte[] data;
        private final int recordCount;
        private final LocalDateTime exportDate;

        public ExportResult(String filename, String contentType, byte[] data, int recordCount) {
            this.filename = filename;
            this.contentType = contentType;
            this.data = data;
            this.recordCount = recordCount;
            this.exportDate = LocalDateTime.now();
        }

        // Getters
        public String getFilename() { return filename; }
        public String getContentType() { return contentType; }
        public byte[] getData() { return data; }
        public int getRecordCount() { return recordCount; }
        public LocalDateTime getExportDate() { return exportDate; }
        public long getDataSize() { return data != null ? data.length : 0; }
    }

    public static class ExportFilter {
        private String format = "CSV";
        private LocalDateTime startDate;
        private LocalDateTime endDate;
        private String searchText;
        private int maxRecords = 0; // 0 means no limit

        // Constructors
        public ExportFilter() {}

        public ExportFilter(String format) {
            this.format = format;
        }

        // Getters and Setters
        public String getFormat() { return format; }
        public void setFormat(String format) { this.format = format; }
        public LocalDateTime getStartDate() { return startDate; }
        public void setStartDate(LocalDateTime startDate) { this.startDate = startDate; }
        public LocalDateTime getEndDate() { return endDate; }
        public void setEndDate(LocalDateTime endDate) { this.endDate = endDate; }
        public String getSearchText() { return searchText; }
        public void setSearchText(String searchText) { this.searchText = searchText; }
        public int getMaxRecords() { return maxRecords; }
        public void setMaxRecords(int maxRecords) { this.maxRecords = maxRecords; }
    }

    private static class ExportContainer {
        private final List<{{domainTitleCase}}Response> data;
        private final int recordCount;
        private final String exportDate;

        public ExportContainer(List<{{domainTitleCase}}Response> data, int recordCount, String exportDate) {
            this.data = data;
            this.recordCount = recordCount;
            this.exportDate = exportDate;
        }

        public List<{{domainTitleCase}}Response> getData() { return data; }
        public int getRecordCount() { return recordCount; }
        public String getExportDate() { return exportDate; }
    }

    public static class ExportException extends RuntimeException {
        public ExportException(String message) {
            super(message);
        }

        public ExportException(String message, Throwable cause) {
            super(message, cause);
        }
    }
}