package {{packageName}}.service;

import {{packageName}}.monitoring.{{domainTitleCase}}MetricsService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.*;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;
import org.springframework.web.reactive.function.client.WebClient;
import reactor.core.publisher.Mono;
import reactor.util.retry.Retry;

import java.time.Duration;
import java.util.Map;

/**
 * External Integration Service for {{serviceNameTitleCase}}
 *
 * Handles communication with external services and APIs.
 * Includes error handling, retry logic, and metrics collection.
 * Generated by Enterprise CLI - customize integration methods as needed.
 */
@Service
public class ExternalIntegrationService {

    private static final Logger logger = LoggerFactory.getLogger(ExternalIntegrationService.class);

    private final RestTemplate restTemplate;
    private final WebClient webClient;
    private final {{domainTitleCase}}MetricsService metricsService;

    @Autowired
    public ExternalIntegrationService(RestTemplate restTemplate,
                                    WebClient webClient,
                                    {{domainTitleCase}}MetricsService metricsService) {
        this.restTemplate = restTemplate;
        this.webClient = webClient;
        this.metricsService = metricsService;
    }

    /**
     * Generic HTTP GET request using RestTemplate
     */
    public <T> T getFromExternalService(String url, Class<T> responseType) {
        logger.info("Making GET request to external service: {}", url);

        try {
            HttpHeaders headers = createDefaultHeaders();
            HttpEntity<String> entity = new HttpEntity<>(headers);

            ResponseEntity<T> response = restTemplate.exchange(
                url, HttpMethod.GET, entity, responseType);

            if (response.getStatusCode().is2xxSuccessful()) {
                logger.debug("Successfully received response from: {}", url);
                metricsService.recordBusinessMetric("external_service_success", 1);
                return response.getBody();
            } else {
                logger.warn("Non-successful response from {}: {}", url, response.getStatusCode());
                metricsService.recordBusinessMetric("external_service_error", 1);
                throw new ExternalServiceException("Non-successful response: " + response.getStatusCode());
            }

        } catch (Exception e) {
            logger.error("Error calling external service: {}", url, e);
            metricsService.recordError();
            throw new ExternalServiceException("Failed to call external service", e);
        }
    }

    /**
     * Generic HTTP POST request using RestTemplate
     */
    public <T, R> R postToExternalService(String url, T requestBody, Class<R> responseType) {
        logger.info("Making POST request to external service: {}", url);

        try {
            HttpHeaders headers = createDefaultHeaders();
            HttpEntity<T> entity = new HttpEntity<>(requestBody, headers);

            ResponseEntity<R> response = restTemplate.exchange(
                url, HttpMethod.POST, entity, responseType);

            if (response.getStatusCode().is2xxSuccessful()) {
                logger.debug("Successfully posted to: {}", url);
                metricsService.recordBusinessMetric("external_service_success", 1);
                return response.getBody();
            } else {
                logger.warn("Non-successful response from {}: {}", url, response.getStatusCode());
                metricsService.recordBusinessMetric("external_service_error", 1);
                throw new ExternalServiceException("Non-successful response: " + response.getStatusCode());
            }

        } catch (Exception e) {
            logger.error("Error posting to external service: {}", url, e);
            metricsService.recordError();
            throw new ExternalServiceException("Failed to post to external service", e);
        }
    }

    /**
     * Reactive HTTP GET request using WebClient with retry
     */
    public <T> Mono<T> getFromExternalServiceReactive(String url, Class<T> responseType) {
        logger.info("Making reactive GET request to external service: {}", url);

        return webClient
                .get()
                .uri(url)
                .retrieve()
                .bodyToMono(responseType)
                .retryWhen(Retry.backoff(3, Duration.ofSeconds(1))
                    .maxBackoff(Duration.ofSeconds(10))
                    .filter(this::isRetryableException))
                .doOnSuccess(result -> {
                    logger.debug("Successfully received reactive response from: {}", url);
                    metricsService.recordBusinessMetric("external_service_success", 1);
                })
                .doOnError(error -> {
                    logger.error("Error in reactive call to external service: {}", url, error);
                    metricsService.recordError();
                });
    }

    /**
     * Reactive HTTP POST request using WebClient with retry
     */
    public <T, R> Mono<R> postToExternalServiceReactive(String url, T requestBody, Class<R> responseType) {
        logger.info("Making reactive POST request to external service: {}", url);

        return webClient
                .post()
                .uri(url)
                .bodyValue(requestBody)
                .retrieve()
                .bodyToMono(responseType)
                .retryWhen(Retry.backoff(3, Duration.ofSeconds(1))
                    .maxBackoff(Duration.ofSeconds(10))
                    .filter(this::isRetryableException))
                .doOnSuccess(result -> {
                    logger.debug("Successfully posted reactive request to: {}", url);
                    metricsService.recordBusinessMetric("external_service_success", 1);
                })
                .doOnError(error -> {
                    logger.error("Error in reactive post to external service: {}", url, error);
                    metricsService.recordError();
                });
    }

    /**
     * Call external service with custom headers
     */
    public <T> T callWithCustomHeaders(String url, Map<String, String> customHeaders, Class<T> responseType) {
        logger.info("Making request with custom headers to: {}", url);

        try {
            HttpHeaders headers = createDefaultHeaders();
            customHeaders.forEach(headers::set);

            HttpEntity<String> entity = new HttpEntity<>(headers);

            ResponseEntity<T> response = restTemplate.exchange(
                url, HttpMethod.GET, entity, responseType);

            if (response.getStatusCode().is2xxSuccessful()) {
                metricsService.recordBusinessMetric("external_service_success", 1);
                return response.getBody();
            } else {
                metricsService.recordBusinessMetric("external_service_error", 1);
                throw new ExternalServiceException("Non-successful response: " + response.getStatusCode());
            }

        } catch (Exception e) {
            logger.error("Error calling external service with custom headers: {}", url, e);
            metricsService.recordError();
            throw new ExternalServiceException("Failed to call external service with custom headers", e);
        }
    }

    // Helper methods

    private HttpHeaders createDefaultHeaders() {
        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);
        headers.set(HttpHeaders.USER_AGENT, "{{serviceNameTitleCase}}/1.0");
        headers.set("X-Service-Name", "{{serviceName}}");
        return headers;
    }

    private boolean isRetryableException(Throwable throwable) {
        // Define which exceptions should trigger a retry
        return throwable instanceof org.springframework.web.client.ResourceAccessException ||
               throwable instanceof java.net.SocketTimeoutException ||
               throwable instanceof java.net.ConnectException;
    }

    /**
     * Health check for external service
     */
    public boolean isExternalServiceHealthy(String healthCheckUrl) {
        try {
            HttpHeaders headers = createDefaultHeaders();
            HttpEntity<String> entity = new HttpEntity<>(headers);

            ResponseEntity<String> response = restTemplate.exchange(
                healthCheckUrl, HttpMethod.GET, entity, String.class);

            boolean isHealthy = response.getStatusCode().is2xxSuccessful();

            if (isHealthy) {
                metricsService.recordBusinessMetric("external_service_health_check_success", 1);
            } else {
                metricsService.recordBusinessMetric("external_service_health_check_failure", 1);
            }

            return isHealthy;

        } catch (Exception e) {
            logger.warn("Health check failed for external service: {}", healthCheckUrl, e);
            metricsService.recordBusinessMetric("external_service_health_check_failure", 1);
            return false;
        }
    }

    /**
     * Custom exception for external service errors
     */
    public static class ExternalServiceException extends RuntimeException {
        public ExternalServiceException(String message) {
            super(message);
        }

        public ExternalServiceException(String message, Throwable cause) {
            super(message, cause);
        }
    }
}