package {{packageName}}.service;

import io.github.resilience4j.circuitbreaker.annotation.CircuitBreaker;
import io.github.resilience4j.retry.annotation.Retry;
import io.github.resilience4j.timelimiter.annotation.TimeLimiter;
import {{packageName}}.monitoring.{{domainTitleCase}}MetricsService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.concurrent.CompletableFuture;
import java.util.concurrent.TimeUnit;

/**
 * Resilient External Service for {{serviceNameTitleCase}}
 *
 * Demonstrates resilience patterns using Resilience4j annotations.
 * Includes circuit breaker, retry, and timeout implementations.
 * Generated by Enterprise CLI - customize according to your integration needs.
 */
@Service
public class ResilientExternalService {

    private static final Logger logger = LoggerFactory.getLogger(ResilientExternalService.class);

    private final {{domainTitleCase}}MetricsService metricsService;

    @Autowired
    public ResilientExternalService({{domainTitleCase}}MetricsService metricsService) {
        this.metricsService = metricsService;
    }

    /**
     * Call external service with circuit breaker and retry
     */
    @CircuitBreaker(name = "external-service", fallbackMethod = "externalServiceFallback")
    @Retry(name = "external-service", fallbackMethod = "externalServiceFallback")
    public String callExternalService(String request) {
        logger.info("Calling external service with request: {}", request);

        // Simulate external service call
        if (Math.random() < 0.3) { // 30% failure rate for demonstration
            throw new RuntimeException("External service temporarily unavailable");
        }

        metricsService.recordBusinessMetric("external_call_success", 1);
        return "Success: " + request;
    }

    /**
     * Fallback method for external service
     */
    public String externalServiceFallback(String request, Exception ex) {
        logger.warn("External service call failed, using fallback. Error: {}", ex.getMessage());
        metricsService.recordBusinessMetric("external_call_fallback", 1);

        // Return cached or default response
        return "Fallback response for: " + request;
    }

    /**
     * Async call with timeout
     */
    @TimeLimiter(name = "external-service", fallbackMethod = "asyncServiceTimeoutFallback")
    @CircuitBreaker(name = "external-service")
    public CompletableFuture<String> callAsyncService(String request) {
        logger.info("Calling async service with request: {}", request);

        return CompletableFuture.supplyAsync(() -> {
            try {
                // Simulate long-running operation
                TimeUnit.SECONDS.sleep(2);
                return "Async Success: " + request;
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                throw new RuntimeException("Async operation interrupted", e);
            }
        });
    }

    /**
     * Fallback for async timeout
     */
    public CompletableFuture<String> asyncServiceTimeoutFallback(String request, Exception ex) {
        logger.warn("Async service timed out, using fallback. Error: {}", ex.getMessage());
        return CompletableFuture.completedFuture("Timeout fallback for: " + request);
    }

    /**
     * Database operation with circuit breaker
     */
    @CircuitBreaker(name = "database", fallbackMethod = "databaseFallback")
    @Retry(name = "database-retry")
    public String performDatabaseOperation(String query) {
        logger.debug("Performing database operation: {}", query);

        // Simulate database operation
        if (Math.random() < 0.1) { // 10% failure rate
            throw new RuntimeException("Database connection error");
        }

        return "Database result for: " + query;
    }

    /**
     * Database fallback method
     */
    public String databaseFallback(String query, Exception ex) {
        logger.error("Database operation failed, using fallback. Error: {}", ex.getMessage());
        metricsService.recordBusinessMetric("database_fallback", 1);

        // Return cached data or empty result
        return "Cached result for: " + query;
    }

    /**
     * Critical operation with custom circuit breaker
     */
    @CircuitBreaker(name = "critical-operation", fallbackMethod = "criticalOperationFallback")
    public String performCriticalOperation(String data) {
        logger.info("Performing critical operation with data: {}", data);

        // Critical business logic here
        if (Math.random() < 0.05) { // 5% failure rate
            throw new RuntimeException("Critical operation failed");
        }

        metricsService.recordBusinessMetric("critical_operation_success", 1);
        return "Critical operation completed: " + data;
    }

    /**
     * Fallback for critical operations
     */
    public String criticalOperationFallback(String data, Exception ex) {
        logger.error("CRITICAL: Operation failed! Data: {}, Error: {}", data, ex.getMessage());
        metricsService.recordBusinessMetric("critical_operation_failure", 1);

        // Implement compensating transaction or manual intervention
        notifyAdministrators(data, ex);

        return "Critical operation failed - manual intervention required";
    }

    /**
     * Retry-only operation (no circuit breaker)
     */
    @Retry(name = "external-api", fallbackMethod = "retryOnlyFallback")
    public String callWithRetryOnly(String request) {
        logger.debug("Calling service with retry only: {}", request);

        // Simulate transient failure
        if (Math.random() < 0.4) { // 40% failure rate
            throw new RuntimeException("Transient error");
        }

        return "Retry success: " + request;
    }

    /**
     * Fallback for retry-only operations
     */
    public String retryOnlyFallback(String request, Exception ex) {
        logger.warn("All retry attempts exhausted for request: {}", request);
        metricsService.recordBusinessMetric("retry_exhausted", 1);
        return "Retry exhausted for: " + request;
    }

    /**
     * Chained resilience patterns
     */
    @TimeLimiter(name = "external-service")
    @CircuitBreaker(name = "external-service")
    @Retry(name = "external-service")
    public CompletableFuture<String> callWithFullResilience(String request) {
        logger.info("Calling with full resilience stack: {}", request);

        return CompletableFuture.supplyAsync(() -> {
            // Complex operation with multiple resilience patterns
            try {
                // Simulate processing
                TimeUnit.MILLISECONDS.sleep(500);

                if (Math.random() < 0.2) { // 20% failure rate
                    throw new RuntimeException("Service error");
                }

                metricsService.recordBusinessMetric("full_resilience_success", 1);
                return "Full resilience success: " + request;

            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                throw new RuntimeException("Operation interrupted", e);
            }
        });
    }

    // Helper methods

    private void notifyAdministrators(String data, Exception ex) {
        // Implement notification logic
        logger.error("NOTIFICATION: Critical failure for data: {}, error: {}", data, ex.getMessage());
        // Send email, SMS, or trigger alert
    }

    /**
     * Health check for resilience monitoring
     */
    public boolean checkResilienceHealth() {
        // Check circuit breaker states
        // Return true if all circuits are healthy
        return true;
    }
}