package {{packageName}}.service;

import {{packageName}}.dto.{{domainTitleCase}}Request;
import {{packageName}}.dto.{{domainTitleCase}}Response;
import {{packageName}}.entity.{{domainTitleCase}};
import {{packageName}}.enterprise.base.AbstractEnterpriseService;

import java.time.LocalDateTime;
import java.util.List;

/**
 * 👨‍💻 BUSINESS SERVICE CLASS
 *
 * Service class for {{domainTitleCase}} business operations.
 * Extends AbstractEnterpriseService for infrastructure methods (create, findById, update, delete, findAll).
 *
 * The AbstractEnterpriseService provides:
 * - create({{domainTitleCase}}Request) -> {{domainTitleCase}}Response
 * - findById(String) -> Optional<{{domainTitleCase}}Response>
 * - update(String, {{domainTitleCase}}Request) -> Optional<{{domainTitleCase}}Response>
 * - delete(String) -> boolean
 * - findAll(Pageable) -> Page<{{domainTitleCase}}Response>
 *
 * Focus only on business-specific methods below.
 * Generated by Enterprise CLI - Business layer
 */
public abstract class {{domainTitleCase}}Service extends AbstractEnterpriseService<{{domainTitleCase}}, String, {{domainTitleCase}}Request, {{domainTitleCase}}Request, {{domainTitleCase}}Response> {

    // ================================
    // 👨‍💻 BUSINESS-SPECIFIC METHODS
    // ================================

    /**
     * Search {{domain}}s by text in name or description
     */
    public abstract List<{{domainTitleCase}}Response> search{{domainTitleCase}}s(String searchText);

    /**
     * Find {{domain}}s by name pattern
     */
    public abstract List<{{domainTitleCase}}Response> find{{domainTitleCase}}sByName(String namePattern);

    /**
     * Get {{domain}}s created after specified date
     */
    public abstract List<{{domainTitleCase}}Response> get{{domainTitleCase}}sCreatedAfter(LocalDateTime date);

    /**
     * Check if {{domain}} exists by name
     */
    public abstract boolean exists{{domainTitleCase}}ByName(String name);

    /**
     * Get count of {{domain}}s created after specified date
     */
    public abstract long count{{domainTitleCase}}sCreatedAfter(LocalDateTime date);

    /**
     * Get active {{domain}}s (business logic example)
     */
    public abstract List<{{domainTitleCase}}Response> getActive{{domainTitleCase}}s();
}