package {{packageName}}.service;

import {{packageName}}.dto.{{domainTitleCase}}Request;
import {{packageName}}.dto.{{domainTitleCase}}Response;
import {{packageName}}.entity.{{domainTitleCase}};
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

/**
 * Service interface for {{domainTitleCase}} business operations
 *
 * This is a sample service interface generated by Enterprise CLI.
 * Define business methods according to your requirements.
 */
public interface {{domainTitleCase}}Service {

    /**
     * Create a new {{domain}}
     */
    {{domainTitleCase}}Response create{{domainTitleCase}}({{domainTitleCase}}Request request);

    /**
     * Get {{domain}} by ID
     */
    Optional<{{domainTitleCase}}Response> get{{domainTitleCase}}ById(String id);

    /**
     * Get all {{domain}}s with pagination
     */
    Page<{{domainTitleCase}}Response> getAll{{domainTitleCase}}s(Pageable pageable);

    /**
     * Get all {{domain}}s as list
     */
    List<{{domainTitleCase}}Response> getAll{{domainTitleCase}}s();

    /**
     * Update existing {{domain}}
     */
    Optional<{{domainTitleCase}}Response> update{{domainTitleCase}}(String id, {{domainTitleCase}}Request request);

    /**
     * Delete {{domain}} by ID
     */
    boolean delete{{domainTitleCase}}(String id);

    /**
     * Search {{domain}}s by text in name or description
     */
    List<{{domainTitleCase}}Response> search{{domainTitleCase}}s(String searchText);

    /**
     * Find {{domain}}s by name pattern
     */
    List<{{domainTitleCase}}Response> find{{domainTitleCase}}sByName(String namePattern);

    /**
     * Get {{domain}}s created after specified date
     */
    List<{{domainTitleCase}}Response> get{{domainTitleCase}}sCreatedAfter(LocalDateTime date);

    /**
     * Check if {{domain}} exists by name
     */
    boolean exists{{domainTitleCase}}ByName(String name);

    /**
     * Get count of {{domain}}s created after specified date
     */
    long count{{domainTitleCase}}sCreatedAfter(LocalDateTime date);

    /**
     * Get active {{domain}}s (business logic example)
     */
    List<{{domainTitleCase}}Response> getActive{{domainTitleCase}}s();


    /**
     * Convert request DTO to entity
     */
    {{domainTitleCase}} convertToEntity({{domainTitleCase}}Request request);
}